[sel YESNO_SEL top]
[f 0 5 65278][f 2 1]Yes[e]
[f 0 5 65278][f 2 1]No[e]

[msg ESCAPE_BAN]
[f 0 5 65278][f 2 1]> Something is preventing it from[n]working...[n][f 1 1][e]

[msg DEATH_WAIT]
[f 0 5 65278][f 2 1][f 0 4 255]> ...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 4 255]> ......[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 4 255]> .........[n][f 1 1][e]

[msg DEATH_BOX]
[f 0 5 65278][f 2 1]> You sense an intensely terrifying[n]presence...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> Open this chest?[n][f 1 1][e]

[msg DEATH_KUMA [Teddie]]
[f 0 5 65278][f 2 1]*shudder*[n][f 1 1][e]
[f 0 5 65278][f 2 1]D-Don't open that![n][f 1 1][e]
[f 0 5 65278][f 2 1]That should never be opened![n][f 1 1][e]

[msg DEATH_RISE [Rise]]
[f 0 5 65278][f 2 1]What's this? I have a really bad feeling[n]about this...[n][f 1 1][e]
[f 0 5 65278][f 2 1]You shouldn't open that![n][f 1 1][e]
[f 0 5 65278][f 2 1]You got that, Senpai?[n]Don't ever open that![n][f 1 1][e]

[msg DEATH_BOX_OPEN_OK]
[f 0 5 65278][f 2 1]> Will you really open it?[n][f 1 1][e]

[msg DEATH_ENCOUNT]
[f 0 5 65278][f 2 1]> Something jumped out of the chest![n][f 1 1][e]

[msg LOCK_BOX]
[f 0 5 65278][f 2 1]> The treasure chest is locked...[n][f 1 1][e]

[msg USE_MUGI_OK]
[f 0 5 65278][f 2 1]> Open the treasure chest with Crack Wheat?[n]    (Crack Wheat remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg USE_KEY_OK]
[f 0 5 65278][f 2 1]> Open the treasure chest with a key?[n]    (Chest Keys remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg TRAPBOX_ENCOUNT]
[f 0 5 65278][f 2 1]> A Shadow jumped out of the chest![n][f 1 1][e]

[msg GET_ITEM_MES]
[f 0 5 65278][f 2 1]> Obtained [f 2 4 1] [f 2 5 3 65535 0].[n][f 1 1][e]

[msg GET_MONEY_MES]
[f 0 5 65278][f 2 1]> Obtained [f 2 4 0] yen.[n][f 1 1][e]

[msg HELP_STAIR_KUMA [Teddie]]
[f 0 5 65278][f 2 1]We found the stairs![n][f 1 1][e]
[f 0 5 65278][f 2 1]I can lead you there anytime![n][f 1 1][e]

[msg HELP_STAIR_NAVI]
[f 0 5 65278][f 2 1]Once you locate the stairway, you can move on[n]to the next floor instantly from the menu[n]accessed with the [f 0 1 2]Sub Menu button[f 0 1 0].[n][f 1 1][e]

[msg FIND_BOX_YOSUKE_01]
[f 0 5 65278][f 2 1]Ooh. We found a chest![n][f 1 6 50][e]

[msg FIND_BOX_YOSUKE_02]
[f 0 5 65278][f 2 1]Huh? A treasure chest![n]Let's open it![n][f 1 6 50][e]

[msg FIND_BOX_YOSUKE_03]
[f 0 5 65278][f 2 1]Huh? Isn't that[n]a chest there?[n][f 1 6 50][e]

[msg FIND_STAIR_YOSUKE_01]
[f 0 5 65278][f 2 1]Ooh! Stairs here![n][f 1 6 50][e]

[msg FIND_STAIR_YOSUKE_02]
[f 0 5 65278][f 2 1]We found the stairs![n]Let's move on![n][f 1 6 50][e]

[msg FIND_STAIR_YOSUKE_03]
[f 0 5 65278][f 2 1]All right, the stairs![n]Let's go![n][f 1 6 50][e]

[msg FIND_ENEMY_YOSUKE_01]
[f 0 5 65278][f 2 1]Whoa, a Shadow![n][f 1 6 50][e]

[msg FIND_ENEMY_YOSUKE_02]
[f 0 5 65278][f 2 1]We found a Shadow![n][f 1 6 50][e]

[msg FIND_ENEMY_YOSUKE_03]
[f 0 5 65278][f 2 1]Ugh... Another one...[n][f 1 6 50][e]

[msg FIND_PLAYER_YOSUKE_01]
[f 0 5 65278][f 2 1]Hey, my man![n][f 1 6 50][e]

[msg FIND_PLAYER_YOSUKE_02]
[f 0 5 65278][f 2 1]Hey![n]How's it going there?[n][f 1 6 50][e]

[msg FIND_CHIE_YOSUKE_01]
[f 0 5 65278][f 2 1]Oh, it's Chie![n]You doin' okay?[n][f 1 6 50][e]

[msg FIND_CHIE_YOSUKE_02]
[f 0 5 65278][f 2 1]Yo, Chie![n][f 1 6 50][e]

[msg FIND_YUKIKO_YOSUKE_01]
[f 0 5 65278][f 2 1]Ah, it's Yukiko...[n]What're you doing?[n][f 1 6 50][e]

[msg FIND_YUKIKO_YOSUKE_02]
[f 0 5 65278][f 2 1]'Sup, Yukiko![n][f 1 6 50][e]

[msg FIND_KANJI_YOSUKE_01]
[f 0 5 65278][f 2 1]Ooh, we found a punk![n][f 1 6 50][e]

[msg FIND_KANJI_YOSUKE_02]
[f 0 5 65278][f 2 1]Yo, Kanji![n][f 1 6 50][e]

[msg FIND_NAOTO_YOSUKE_01]
[f 0 5 65278][f 2 1]Hey, Naoto![n]What're ya doing there?[n][f 1 6 50][e]

[msg FIND_NAOTO_YOSUKE_02]
[f 0 5 65278][f 2 1]Yo, kid![n][f 1 6 50][e]

[msg FIND_KUMA_YOSUKE_01]
[f 0 5 65278][f 2 1]Hey, Teddie![n]Same as always?[n][f 1 6 50][e]

[msg FIND_KUMA_YOSUKE_02]
[f 0 5 65278][f 2 1]Oh, Ted![n][f 1 6 50][e]

[msg FIND_FIX_YOSUKE_01]
[f 0 5 65278][f 2 1]Hey, it's the fox![n]What're you doing here?[n][f 1 6 50][e]

[msg FIND_FIX_YOSUKE_02]
[f 0 5 65278][f 2 1]Oh, the fox![n][f 1 6 50][e]

[msg FIND_BOX_CHIE_01]
[f 0 5 65278][f 2 1]Oh, a treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_CHIE_02]
[f 0 5 65278][f 2 1]Treasure spotted![n][f 1 6 50][e]

[msg FIND_BOX_CHIE_03]
[f 0 5 65278][f 2 1]Ooh, a treasure chest![n]Try opening it![n][f 1 6 50][e]

[msg FIND_STAIR_CHIE_01]
[f 0 5 65278][f 2 1]We found the stairs![n][f 1 6 50][e]

[msg FIND_STAIR_CHIE_02]
[f 0 5 65278][f 2 1]We found the stairs! Let's[n]hurry to the next floor.[n][f 1 6 50][e]

[msg FIND_STAIR_CHIE_03]
[f 0 5 65278][f 2 1]Ooh, stairs right here![n]Why don't we go on ahead?[n][f 1 6 50][e]

[msg FIND_ENEMY_CHIE_01]
[f 0 5 65278][f 2 1]Sheesh, a Shadow![n][f 1 6 50][e]

[msg FIND_ENEMY_CHIE_02]
[f 0 5 65278][f 2 1]Argh! There's a Shadow![n][f 1 6 50][e]

[msg FIND_ENEMY_CHIE_03]
[f 0 5 65278][f 2 1]There's a Shadow here,[n]too...[n][f 1 6 50][e]

[msg FIND_PLAYER_CHIE_01]
[f 0 5 65278][f 2 1]Hey there![n][f 1 6 50][e]

[msg FIND_PLAYER_CHIE_02]
[f 0 5 65278][f 2 1]Oh, doing okay?[n][f 1 6 50][e]

[msg FIND_YOSUKE_CHIE_01]
[f 0 5 65278][f 2 1]Oh, Yosuke![n]Are you just chilling here?[n][f 1 6 50][e]

[msg FIND_YOSUKE_CHIE_02]
[f 0 5 65278][f 2 1]Hey, it's Yosuke![n][f 1 6 50][e]

[msg FIND_YUKIKO_CHIE_01]
[f 0 5 65278][f 2 1]Oh, Yukiko![n]What're you doing?[n][f 1 6 50][e]

[msg FIND_YUKIKO_CHIE_02]
[f 0 5 65278][f 2 1]Ooh, Yukiko![n][f 1 6 50][e]

[msg FIND_KANJI_CHIE_01]
[f 0 5 65278][f 2 1]Hey, Kanji-kun![n]What are you doing here?[n][f 1 6 50][e]

[msg FIND_KANJI_CHIE_02]
[f 0 5 65278][f 2 1]What's up, Kanji-kun?[n][f 1 6 50][e]

[msg FIND_NAOTO_CHIE_01]
[f 0 5 65278][f 2 1]Naoto-kun's here![n]Is something wrong?[n][f 1 6 50][e]

[msg FIND_NAOTO_CHIE_02]
[f 0 5 65278][f 2 1]Oh, it's Naoto-kun![n][f 1 6 50][e]

[msg FIND_KUMA_CHIE_01]
[f 0 5 65278][f 2 1]Teddie![n]Keep up the good work![n][f 1 6 50][e]

[msg FIND_KUMA_CHIE_02]
[f 0 5 65278][f 2 1]Teddie![n][f 1 6 50][e]

[msg FIND_FOX_CHIE_01]
[f 0 5 65278][f 2 1]Hey, Foxy![n]Whatcha doin'?[n][f 1 6 50][e]

[msg FIND_FOX_CHIE_02]
[f 0 5 65278][f 2 1]Look, it's the fox![n][f 1 6 50][e]

[msg FIND_BOX_YUKIKO_01]
[f 0 5 65278][f 2 1]Oh, we found a[n]treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_YUKIKO_02]
[f 0 5 65278][f 2 1]Is this treasure?[n][f 1 6 50][e]

[msg FIND_BOX_YUKIKO_03]
[f 0 5 65278][f 2 1]A treasure chest![n]Do you want to open it?[n][f 1 6 50][e]

[msg FIND_STAIR_YUKIKO_01]
[f 0 5 65278][f 2 1]Ah, so here's the stairway.[n][f 1 6 50][e]

[msg FIND_STAIR_YUKIKO_02]
[f 0 5 65278][f 2 1]There's the stairway![n]Let's hurry ahead![n][f 1 6 50][e]

[msg FIND_STAIR_YUKIKO_03]
[f 0 5 65278][f 2 1]We found the stairway.[n]Shall we go on?[n][f 1 6 50][e]

[msg FIND_ENEMY_YUKIKO_01]
[f 0 5 65278][f 2 1]An enemy! Be careful![n][f 1 6 50][e]

[msg FIND_ENEMY_YUKIKO_02]
[f 0 5 65278][f 2 1]We found a Shadow![n]Are you ready?[n][f 1 6 50][e]

[msg FIND_ENEMY_YUKIKO_03]
[f 0 5 65278][f 2 1]Shadows here, too...?[n][f 1 6 50][e]

[msg FIND_PLAYER_YUKIKO_01]
[f 0 5 65278][f 2 1]Oh, there you are![n][f 1 6 50][e]

[msg FIND_PLAYER_YUKIKO_02]
[f 0 5 65278][f 2 1]Good work![n]Are you feeling all right?[n][f 1 6 50][e]

[msg FIND_YOSUKE_YUKIKO_01]
[f 0 5 65278][f 2 1]Yosuke-kun![n]Did you come all this way?[n][f 1 6 50][e]

[msg FIND_YOSUKE_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, Yosuke-kun![n][f 1 6 50][e]

[msg FIND_CHIE_YUKIKO_01]
[f 0 5 65278][f 2 1]Chie! I'm so happy[n]to see you here![n][f 1 6 50][e]

[msg FIND_CHIE_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, Chie![n][f 1 6 50][e]

[msg FIND_KANJI_YUKIKO_01]
[f 0 5 65278][f 2 1]Oh, Kanji-kun![n]You've been working hard![n][f 1 6 50][e]

[msg FIND_KANJI_YUKIKO_02]
[f 0 5 65278][f 2 1]Hello, Kanji-kun![n][f 1 6 50][e]

[msg FIND_NAOTO_YUKIKO_01]
[f 0 5 65278][f 2 1]Naoto-kun![n]What's wrong?[n][f 1 6 50][e]

[msg FIND_NAOTO_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, Naoto-kun![n][f 1 6 50][e]

[msg FIND_KUMA_YUKIKO_01]
[f 0 5 65278][f 2 1]Teddie, are you all right?[n][f 1 6 50][e]

[msg FIND_KUMA_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, it's Teddie![n][f 1 6 50][e]

[msg FIND_FOX_YUKIKO_01]
[f 0 5 65278][f 2 1]What are you doing[n]here, fox-san?[n][f 1 6 50][e]

[msg FIND_FOX_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, it's the fox![n][f 1 6 50][e]

[msg FIND_BOX_KANJI_01]
[f 0 5 65278][f 2 1]Treasure![n][f 1 6 50][e]

[msg FIND_BOX_KANJI_02]
[f 0 5 65278][f 2 1]We found a treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_KANJI_03]
[f 0 5 65278][f 2 1]Hey, we found a chest.[n]Let's pop this sucker open![n][f 1 6 50][e]

[msg FIND_STAIR_KANJI_01]
[f 0 5 65278][f 2 1]Stairs here![n][f 1 6 50][e]

[msg FIND_STAIR_KANJI_02]
[f 0 5 65278][f 2 1]Ooh, the stairs![n]Let's go![n][f 1 6 50][e]

[msg FIND_STAIR_KANJI_03]
[f 0 5 65278][f 2 1]It's the stairs.[n]Ready to move on?[n][f 1 6 50][e]

[msg FIND_ENEMY_KANJI_01]
[f 0 5 65278][f 2 1]We found a Shadow![n]Let's crush it![n][f 1 6 50][e]

[msg FIND_ENEMY_KANJI_02]
[f 0 5 65278][f 2 1]All right, an enemy![n][f 1 6 50][e]

[msg FIND_ENEMY_KANJI_03]
[f 0 5 65278][f 2 1]There's one...[n][f 1 6 50][e]

[msg FIND_PLAYER_KANJI_01]
[f 0 5 65278][f 2 1]Oh, hey.[n][f 1 6 50][e]

[msg FIND_PLAYER_KANJI_02]
[f 0 5 65278][f 2 1]Are you doing okay?[n][f 1 6 50][e]

[msg FIND_YOSUKE_KANJI_01]
[f 0 5 65278][f 2 1]Hey, Yosuke-senpai![n][f 1 6 50][e]

[msg FIND_YOSUKE_KANJI_02]
[f 0 5 65278][f 2 1]Oh, it's Yosuke-senpai![n][f 1 6 50][e]

[msg FIND_CHIE_KANJI_01]
[f 0 5 65278][f 2 1]Chie-senpai, what's up![n][f 1 6 50][e]

[msg FIND_CHIE_KANJI_02]
[f 0 5 65278][f 2 1]Yo, Chie-senpai![n][f 1 6 50][e]

[msg FIND_YUKIKO_KANJI_01]
[f 0 5 65278][f 2 1]Yukiko-senpai, keep[n]up the good work![n][f 1 6 50][e]

[msg FIND_YUKIKO_KANJI_02]
[f 0 5 65278][f 2 1]Hey Yukiko-senpai![n][f 1 6 50][e]

[msg FIND_NAOTO_KANJI_01]
[f 0 5 65278][f 2 1]O-Oh, it's Naoto...[n]What're ya doin'?[n][f 1 6 50][e]

[msg FIND_NAOTO_KANJI_02]
[f 0 5 65278][f 2 1]Oh, h-hi there, Naoto![n][f 1 6 50][e]

[msg FIND_KUMA_KANJI_01]
[f 0 5 65278][f 2 1]Yo, Teddie![n][f 1 6 50][e]

[msg FIND_KUMA_KANJI_02]
[f 0 5 65278][f 2 1]Oh, it's just you, Ted...[n][f 1 6 50][e]

[msg FIND_FOX_KANJI_01]
[f 0 5 65278][f 2 1]Ooh! It's the fox![n][f 1 6 50][e]

[msg FIND_FOX_KANJI_02]
[f 0 5 65278][f 2 1]Well, hello there, fox.[n][f 1 6 50][e]

[msg FIND_BOX_KUMA_01]
[f 0 5 65278][f 2 1]Wooo, we found a chest![n][f 1 6 50][e]

[msg FIND_BOX_KUMA_02]
[f 0 5 65278][f 2 1]Treasure ahoy![n][f 1 6 50][e]

[msg FIND_BOX_KUMA_03]
[f 0 5 65278][f 2 1]A treasure chest![n]Let's open it![n][f 1 6 50][e]

[msg FIND_STAIR_KUMA_01]
[f 0 5 65278][f 2 1]Stairs! Should we[n]go on ahead?[n][f 1 6 50][e]

[msg FIND_STAIR_KUMA_02]
[f 0 5 65278][f 2 1]Stairs right here![n][f 1 6 50][e]

[msg FIND_STAIR_KUMA_03]
[f 0 5 65278][f 2 1]We found the stairs![n][f 1 6 50][e]

[msg FIND_ENEMY_KUMA_01]
[f 0 5 65278][f 2 1]We found the enemy![n]Be careful![n][f 1 6 50][e]

[msg FIND_ENEMY_KUMA_02]
[f 0 5 65278][f 2 1]Shadows![n]Let's get 'em![n][f 1 6 50][e]

[msg FIND_ENEMY_KUMA_03]
[f 0 5 65278][f 2 1]We found a Shadow![n]I'll take'em on![n][f 1 6 50][e]

[msg FIND_PLAYER_KUMA_01]
[f 0 5 65278][f 2 1]Huh? We found you![n][f 1 6 50][e]

[msg FIND_PLAYER_KUMA_02]
[f 0 5 65278][f 2 1]How are you doing?[n][f 1 6 50][e]

[msg FIND_YOSUKE_KUMA_01]
[f 0 5 65278][f 2 1]Yosuke, you okay?[n][f 1 6 50][e]

[msg FIND_YOSUKE_KUMA_02]
[f 0 5 65278][f 2 1]Ooh, Yosuke![n][f 1 6 50][e]

[msg FIND_CHIE_KUMA_01]
[f 0 5 65278][f 2 1]Chie-chan![n]How long's it been![n][f 1 6 50][e]

[msg FIND_CHIE_KUMA_02]
[f 0 5 65278][f 2 1]Ooh, it's Chie-chan![n][f 1 6 50][e]

[msg FIND_YUKIKO_KUMA_01]
[f 0 5 65278][f 2 1]Yuki-chan! Konnichiwa![n][f 1 6 50][e]

[msg FIND_YUKIKO_KUMA_02]
[f 0 5 65278][f 2 1]Ooh, Yuki-chan![n][f 1 6 50][e]

[msg FIND_KANJI_KUMA_01]
[f 0 5 65278][f 2 1]Kanji! Nice work![n][f 1 6 50][e]

[msg FIND_KANJI_KUMA_02]
[f 0 5 65278][f 2 1]Hey, it's Kanji![n][f 1 6 50][e]

[msg FIND_NAOTO_KUMA_01]
[f 0 5 65278][f 2 1]Nao-chan! Doing good?[n][f 1 6 50][e]

[msg FIND_NAOTO_KUMA_02]
[f 0 5 65278][f 2 1]Ooh, Nao-chan![n][f 1 6 50][e]

[msg FIND_FOX_KUMA_01]
[f 0 5 65278][f 2 1]Heya, Kitsu-chan![n][f 1 6 50][e]

[msg FIND_FOX_KUMA_02]
[f 0 5 65278][f 2 1]Hey, Foxy![n][f 1 6 50][e]

[msg FIND_BOX_RISE_01]
[f 0 5 65278][f 2 1]We found a chest![n][f 1 6 50][e]

[msg FIND_BOX_RISE_02]
[f 0 5 65278][f 2 1]It's a treasure chest![n]Why don't you open it?[n][f 1 6 50][e]

[msg FIND_BOX_RISE_03]
[f 0 5 65278][f 2 1]Oh, treasure![n][f 1 6 50][e]

[msg FIND_STAIR_RISE_01]
[f 0 5 65278][f 2 1]It's the stairway![n]Wanna go on ahead?[n][f 1 6 50][e]

[msg FIND_STAIR_RISE_02]
[f 0 5 65278][f 2 1]Hey, it's the stairs![n][f 1 6 50][e]

[msg FIND_STAIR_RISE_03]
[f 0 5 65278][f 2 1]Stairs located![n]Let's go![n][f 1 6 50][e]

[msg FIND_ENEMY_RISE_01]
[f 0 5 65278][f 2 1]There's enemies over[n]there! Be careful![n][f 1 6 50][e]

[msg FIND_ENEMY_RISE_02]
[f 0 5 65278][f 2 1]Enemy Shadows![n]Take care![n][f 1 6 50][e]

[msg FIND_ENEMY_RISE_03]
[f 0 5 65278][f 2 1]There are enemies over[n]there. Be careful![n][f 1 6 50][e]

[msg FIND_YOSUKE_RISE_01]
[f 0 5 65278][f 2 1]It's Yosuke-senpai![n]What are you doing?[n][f 1 6 50][e]

[msg FIND_YOSUKE_RISE_02]
[f 0 5 65278][f 2 1]Oh, Yosuke-senpai![n][f 1 6 50][e]

[msg FIND_CHIE_RISE_01]
[f 0 5 65278][f 2 1]Chie-senpai, hello![n][f 1 6 50][e]

[msg FIND_CHIE_RISE_02]
[f 0 5 65278][f 2 1]Hi there, Chie-senpai![n][f 1 6 50][e]

[msg FIND_YUKIKO_RISE_01]
[f 0 5 65278][f 2 1]Yukiko-senpai![n]Are you all right?[n][f 1 6 50][e]

[msg FIND_YUKIKO_RISE_02]
[f 0 5 65278][f 2 1]Hi there, Yukiko-senpai![n][f 1 6 50][e]

[msg FIND_KANJI_RISE_01]
[f 0 5 65278][f 2 1]Kanji, how are you?[n][f 1 6 50][e]

[msg FIND_KANJI_RISE_02]
[f 0 5 65278][f 2 1]Oh, it's Kanji![n][f 1 6 50][e]

[msg FIND_NAOTO_RISE_01]
[f 0 5 65278][f 2 1]Naoto, how are you doing?[n][f 1 6 50][e]

[msg FIND_NAOTO_RISE_02]
[f 0 5 65278][f 2 1]Ooh, it's Naoto![n][f 1 6 50][e]

[msg FIND_KUMA_RISE_01]
[f 0 5 65278][f 2 1]Teddie, still have[n]energy in you?[n][f 1 6 50][e]

[msg FIND_KUMA_RISE_02]
[f 0 5 65278][f 2 1]Ooh, we found Teddie![n][f 1 6 50][e]

[msg FIND_FOX_RISE_01]
[f 0 5 65278][f 2 1]Oh, Fox-kun![n]What's up?[n][f 1 6 50][e]

[msg FIND_FOX_RISE_02]
[f 0 5 65278][f 2 1]Look, it's Fox-kun![n][f 1 6 50][e]

[msg FIND_BOX_NAOTO_01]
[f 0 5 65278][f 2 1]Oh, a treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_NAOTO_02]
[f 0 5 65278][f 2 1]We found a treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_NAOTO_03]
[f 0 5 65278][f 2 1]It looks like a treasure chest.[n]Are you going to open it?[n][f 1 6 50][e]

[msg FIND_STAIR_NAOTO_01]
[f 0 5 65278][f 2 1]Stairs have been located![n]Let's proceed ahead![n][f 1 6 50][e]

[msg FIND_STAIR_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, it's the stairway![n][f 1 6 50][e]

[msg FIND_STAIR_NAOTO_03]
[f 0 5 65278][f 2 1]We found the stairs![n][f 1 6 50][e]

[msg FIND_ENEMY_NAOTO_01]
[f 0 5 65278][f 2 1]Hostile Shadows![n]Be careful![n][f 1 6 50][e]

[msg FIND_ENEMY_NAOTO_02]
[f 0 5 65278][f 2 1]Enemy Shadows... Shall we[n]wait to see what they'll do?[n][f 1 6 50][e]

[msg FIND_ENEMY_NAOTO_03]
[f 0 5 65278][f 2 1]Shadows are here,[n]as well...[n][f 1 6 50][e]

[msg FIND_PLAYER_NAOTO_01]
[f 0 5 65278][f 2 1]Oh, hello![n]Let's keep up the work![n][f 1 6 50][e]

[msg FIND_PLAYER_NAOTO_02]
[f 0 5 65278][f 2 1]How are you doing[n]on your end?[n][f 1 6 50][e]

[msg FIND_YOSUKE_NAOTO_01]
[f 0 5 65278][f 2 1]Yosuke-senpai, hello.[n][f 1 6 50][e]

[msg FIND_YOSUKE_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Yosuke-senpai![n][f 1 6 50][e]

[msg FIND_CHIE_NAOTO_01]
[f 0 5 65278][f 2 1]Chie-senpai, how is it going?[n][f 1 6 50][e]

[msg FIND_CHIE_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Chie-senpai![n][f 1 6 50][e]

[msg FIND_YUKIKO_NAOTO_01]
[f 0 5 65278][f 2 1]Yukiko-senpai, hello![n][f 1 6 50][e]

[msg FIND_YUKIKO_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Yukiko-senpai![n][f 1 6 50][e]

[msg FIND_KANJI_NAOTO_01]
[f 0 5 65278][f 2 1]Kanji-kun![n]How are you doing?[n][f 1 6 50][e]

[msg FIND_KANJI_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Kanji-kun![n][f 1 6 50][e]

[msg FIND_KUMA_NAOTO_01]
[f 0 5 65278][f 2 1]Teddie![n]You're here already?[n][f 1 6 50][e]

[msg FIND_KUMA_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Teddie![n][f 1 6 50][e]

[msg FIND_FOX_NAOTO_01]
[f 0 5 65278][f 2 1]Oh, Fox-san![n]What's wrong?[n][f 1 6 50][e]

[msg FIND_FOX_NAOTO_02]
[f 0 5 65278][f 2 1]Look, it's Fox-san![n][f 1 6 50][e]

[msg DOOR_LOCK]
[f 0 5 65278][f 2 1]> The door seems to be locked...[n][f 1 1][e]

[msg DOOR_KUMA [Teddie]]
[f 0 5 65278][f 2 1]I sense something beyond this door...[n][f 1 1][e]

[msg OPEN_DOOR_OK]
[f 0 5 65278][f 2 1]> Open the door and enter?[n][f 1 1][e]

[msg OPEN_DOOR_PH_OK]
[f 0 5 65278][f 2 1]> Open the curtain and enter?[n][f 1 1][e]

[msg OPEN_NOT_DOOR_OK]
[f 0 5 65278][f 2 1]> Continue through?[n][f 1 1][e]

[msg OPEN_DOOR_LOCK]
[f 0 5 65278][f 2 1]> Used the [f 2 5 3 65535 0] to open.[n][f 1 1][e]

[msg GET_KEY]
[f 0 5 65278][f 2 1]> Obtained [f 2 5 3 65535 0].[n][f 1 1][e]

[msg DOOR_CASTLE [Teddie]]
[f 0 5 65278][f 2 1]I sense someone beyond this door...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's that girl's scent![n][f 1 1][e]

[msg CASTLE_ENC_1 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 37 1 0 1]*chuckle*[n][f 1 1][e]
[f 0 5 65278][f 2 1]My Prince wouldn't lose to guards such[n]as this, correct?[n][f 1 1][e]

[msg CASTLE_ENC_2 [Teddie]]
[f 0 5 65278][f 2 1]Gyaaaaaah! I've never seen such a[n]strong one before![n][f 1 1][e]
[f 0 5 65278][f 2 1]I-It's attacking us![n][f 1 1][e]

[msg CASTLE_ENC_WIN_1 [Yukiko's voice]]
[f 0 5 65278][f 2 1]*chuckle*[n][f 1 1][e]
[f 0 5 65278][f 2 1]If you really are my Prince, then we[n]will surely meet again.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I am but a trapped soul... I cannot[n]leave this place even if I wished...[n][f 1 1][e]
[f 0 5 65278][f 2 1]*chuckle*[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]

[msg CASTLE_ENC_WIN_2 [Teddie]]
[f 0 5 65278][f 2 1]I don't sense her anymore...[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh! Are you okay, Sensei?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm sure we've got a long ways to go.[n]Don't push yourself too hard![n][f 1 1][e]
[f 0 5 65278][f 2 1]If you're tired, you should head back![n][f 1 1][e]

[msg DOOR_SAUNA [Teddie]]
[f 0 5 65278][f 2 1]Ooh, this presence...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Could it be Kanji-kun...?[n][f 1 1][e]

[msg SAUNA_ENC_DOOR_27]
[f 0 5 65278][f 2 1]> A vast amount of steam is drifting[n]in from the other side of the door...[n][f 1 1][e]

[msg SAUNA_ENC_1 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 39 1 0 1]Welcome to Man's World![n][f 1 1][e]
[f 0 5 65278][f 2 1]This place is heating up from the sudden[n]entry of a fine young man![n][f 1 1][e]
[f 0 5 65278][f 2 1]To celebrate this encounter, I've prepared[n]a special stage tonight![n][f 1 1][e]
[f 0 5 65278][f 2 1]A single match with no time limit![n]Who will be left standing in the end?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Now, pour out your hot blood and guts![n][f 1 1][e]

[msg SAUNA_ENC_2 [Teddie]]
[f 0 5 65278][f 2 1]Ooh! Don't lose, Sensei![n][f 1 1][e]

[msg SAUNA_ENC_WIN [Teddie]]
[f 0 5 65278][f 2 1]That's our Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]I knew you would win![n][f 1 1][e]

[msg DOOR_PLAYHOUSE [Teddie]]
[f 0 5 65278][f 2 1]The smell's coming from here![n][f 1 1][e]

[msg PLAYHOUSE_DOOR_STOP [Rise's voice]]
[f 0 5 65278][f 2 1]Awwww! You're so impatient![n][f 1 1][e]
[f 0 5 65278][f 2 1]You can't go in yet, mmm?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Over here, over here! Hurry![n][f 1 1][e]

[msg PLAYHOUSE_ENC_DOOR_1]
[f 0 5 65278][f 2 1]> You can hear voices from beyond[n]the curtain...[n][f 1 1][e]

[msg PLAYHOUSE_ENC_DOOR_2 [Rise's voice]]
[f 0 5 65278][f 2 1]You came![n][f 1 1][e]
[f 0 5 65278][f 2 1]Okay. I'm ready for anything...[n][f 1 1][e]

[msg PLAYHOUSE_ENC_DOOR_3 [Teddie]]
[f 0 5 65278][f 2 1]*gulp*[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Are you ready, Sensei?[n][f 1 1][e]

[msg PLAYHOUSE_ENC_1 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 38 1 0 1]It's my first time...[n]Please be gentle.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm turning on the lights, okay?[n][f 1 1][e]

[msg PLAYHOUSE_ENC_2 [Teddie]]
[f 0 5 65278][f 2 1]Whooooooa!?[n][f 1 1][e]

[msg PLAYHOUSE_ENC_WIN [Teddie]]
[f 0 5 65278][f 2 1]What is this immense feeling[n]of... disappointment?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I didn't even get a chance to choose![n]Have I been fooled?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's just go home now, Sensei...[n][f 1 1][e]

[msg GAMEWORLD_ENC_DOOR [Rise]]
[f 0 5 65278][f 2 1]There's something beyond this door![n]Are you ready?[n][f 1 1][e]

[msg GAMEWORLD_ENC]
[f 0 5 65278][f 2 1]A Shadow approaches![n][f 1 1][e]

[msg GAMEWORLD_ENC_WIN [Rise]]
[f 0 5 65278][f 2 1]Phew... Well done![n][f 1 1][e]
[f 0 5 65278][f 2 1]Are you okay, Senpai? Don't push[n]yourself too hard, okay?[n][f 1 1][e]

[msg DOOR_LOCK_084 [Gate check]]
[f 0 5 65278][f 2 1]THE RESEARCH AREA IS BEYOND[n]THIS POINT.[n][f 1 1][e]
[f 0 5 65278][f 2 1]ENTRY IS FORBIDDEN TO ORDINARY[n]COMBATANTS.[n][f 1 1][e]
[f 0 5 65278][f 2 1]PLEASE PRESENT YOUR ID.[n][f 1 1][e]

[msg BASE_ENC_DOOR [Rise]]
[f 0 5 65278][f 2 1]Be careful! I sense a strong presence[n]beyond this door![n][f 1 1][e]

[msg BASE_ENC [Guard]]
[f 0 5 65278][f 2 1]INTRUDER DETECTED WITHIN THE[n]RESEARCH AREA. ELIMINATION[n]PROCEEDING.[n][f 1 1][e]

[msg BASE_ENC_WIN [Rise]]
[f 0 5 65278][f 2 1]Yes! You did it, Senpai![n][f 1 1][e]

[msg DOOR_LOCK_086 [Gate check]]
[f 0 5 65278][f 2 1]BEYOND THIS POINT IS CONFIDENTIAL.[n][f 1 1][e]
[f 0 5 65278][f 2 1]ENTRY IS FORBIDDEN FOR ORDINARY[n]COMBATANTS AND RESEARCHERS.[n][f 1 1][e]
[f 0 5 65278][f 2 1]PLEASE PRESENT YOUR ID.[n][f 1 1][e]

[msg NOT_OPEN_DOOR_LOCK]
[f 0 5 65278][f 2 1]> The door won't open with the[n][f 2 5 3 65535 0]...[n][f 1 1][e]

[msg HEAVEN_ENC_DOOR [Man's voice]]
[f 0 5 65278][f 2 1]Turn back![n][f 1 1][e]
[f 0 5 65278][f 2 1]Stop getting in my way![n][f 1 1][e]

[msg HEAVEN_ENC_1 [Man's voice]]
[f 0 5 65278][f 2 1]Why are you getting in my way!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm going to save this girl![n][f 1 1][e]

[msg HEAVEN_ENC_WIN [Rise]]
[f 0 5 65278][f 2 1]I'm worried about Nanako-chan...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Senpai, let's hurry on![n][f 1 1][e]

[msg CITY_2F_LOCK_DOOR]
[f 0 5 65278][f 2 1]> It's sealed by some strong force...[n][f 1 1][e]

[msg CITY_2F_LOCK_DOOR_A [Adachi's voice]]
[f 0 5 65278][f 2 1]Ahaha![n][f 1 1][e]
[f 0 5 65278][f 2 1]That's right! As you have guessed, I'm[n]waiting for you just beyond here.[n][f 1 1][e]
[f 0 5 65278][f 2 1]But did you really think I'd just let you[n]through?[n][f 1 1][e]

[msg CITY_2F_LOCK_NOTOPEN_A [Rise]]
[f 0 5 65278][f 2 1]Grrr...![n][f 1 1][e]
[f 0 5 65278][f 2 1]There has to be a way to open this![n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's look around for clues, Senpai![n][f 1 1][e]

[msg CITY_2F_LOCK_NOTOPEN [Rise]]
[f 0 5 65278][f 2 1]There has to be a way to open this[n]somewhere![n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's look for it, Senpai![n][f 1 1][e]

[msg CITY_2F_LOCK_OPEN_1 [Rise]]
[f 0 5 65278][f 2 1]Please open...![n][f 1 1][e]

[msg CITY_2F_LOCK_OPEN_2 [Rise]]
[f 0 5 65278][f 2 1]We did it, Senpai! It's open![n][f 1 1][e]
[f 0 5 65278][f 2 1]Alright, now we've got him cornered![n]Let's get him![n][f 1 1][e]

[msg ENC_GIMMIC_MISS [Adachi's voice]]
[f 0 5 65278][f 2 1]Awww, that's no good...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Didn't you listen to the rules I made?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I told you that you can't get caught by[n]the Shadows here, remember?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Better luck next time![n][f 1 1][e]

[msg CITY_ENC_5F_DOOR [Adachi's voice]]
[f 0 5 65278][f 2 1]Wow... I'm surprised you made it this far.[n][f 1 1][e]
[f 0 5 65278][f 2 1]As your reward, I'll fight you![n][f 1 1][e]

[msg CITY_ENC_5F [Adachi's voice]]
[f 0 5 65278][f 2 1]I'm lying, of course. Like I'd ever do[n]something like that.[n][f 1 1][e]
[f 0 5 65278][f 2 1]The only thing you deserve is to fight[n]against Shadows.[n][f 1 1][e]

[msg CITY_ENC_5F_WIN_1 [Adachi's voice]]
[f 0 5 65278][f 2 1]Huh, you're better than I thought...[n][f 1 1][e]
[f 0 5 65278][f 2 1]But how long can you keep it up?[n][f 1 1][e]

[msg CITY_ENC_5F_WIN_2 [Rise]]
[f 0 5 65278][f 2 1]Hmph, like that had any chance of stopping[n]us. Let's go, Senpai![n][f 1 1][e]

[msg CITY_ENC_8F_DOOR [Rise]]
[f 0 5 65278][f 2 1]Something's beyond here![n]Senpai, are you ready?[n][f 1 1][e]

[msg CITY_ENC_8F_1 [Rise]]
[f 0 5 65278][f 2 1]This is it! If we beat this, it should[n]do the trick![n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's go, Senpai![n][f 1 1][e]

[msg CITY_ENC_8F_WIN [Rise]]
[f 0 5 65278][f 2 1]Yes, the power's getting weaker![n]We might be able to pass through[n]that place now![n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's go back, Senpai![n][f 1 1][e]

[msg LAST_ENC_3F_DOOR [Rise]]
[f 0 5 65278][f 2 1]Be careful, Senpai! I sense something[n]up ahead of you![n][f 1 1][e]

[msg LAST_ENC_3F [Izanami's voice]]
[f 0 5 65278][f 2 1]The power that you have attained...[n]And your determination to face me...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's see how strong they are...[n][f 1 1][e]

[msg LAST_ENC_3F_WIN [Izanami's voice]]
[f 0 5 65278][f 2 1]*chuckle* So that wasn't enough to break[n]your will.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Come, then... Though you may accomplish[n]nothing but to needlessly prolong your[n]suffering.[n][f 1 1][e]

[msg LAST_ENC_6F_DOOR [Rise]]
[f 0 5 65278][f 2 1]This feeling...[n][f 1 1][e]
[f 0 5 65278][f 2 1]There's something past here again![n]Be careful, Senpai![n][f 1 1][e]

[msg LAST_ENC_6F [Izanami's voice]]
[f 0 5 65278][f 2 1]All of this has been chosen by mankind.[n]And whatever strength you possess is still[n]within man's scope...[n][f 1 1][e]
[f 0 5 65278][f 2 1]You cannot surpass me... Learn that![n][f 1 1][e]

[msg LAST_ENC_6F_WIN [Rise]]
[f 0 5 65278][f 2 1]Who'd want our world to be covered in[n]fog!? We sure don't![n][f 1 1][e]
[f 0 5 65278][f 2 1]And I know Nanako-chan and Dojima-san[n]would agree![n][f 1 1][e]
[f 0 5 65278][f 2 1]We're not gonna let her do whatever she[n]wants! Right, Senpai!?[n][f 1 1][e]

[msg SP_ZERO_HELP_PLAYER [Rise]]
[f 0 5 65278][f 2 1]Huh? Hold on! Why is your spirit so[n]depleted, Senpai?[n][f 1 1][e]

[msg SP_ZERO_HELP_ALL [Rise]]
[f 0 5 65278][f 2 1]Huh? Hold on! Everyone's spirit is[n]really depleted...[n][f 1 1][e]

[msg SP_ZERO_HELP]
[f 0 5 65278][f 2 1]Every time you fight in this dungeon,[n]your SP will be drained. [n][f 1 1][e]

[msg SP_ZERO_HELP_COM [Rise]]
[f 0 5 65278][f 2 1]Why...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Why are you so exhausted?[n][f 1 1][e]

[msg TOMB_ENC_1F_DOOR_1 [Rise]]
[f 0 5 65278][f 2 1]Huh? I don't see any Shadows there...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Wait, that's not what I meant.[n]There ARE Shadows.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I can feel them, but I don't see them...[n][f 1 1][e]

[msg TOMB_ENC_1F_DOOR_2 [Rise]]
[f 0 5 65278][f 2 1]Hmmm...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I still don't see any Shadows...[n][f 1 1][e]

[msg TOMB_ENC_1F_DOOR_INFO [Rise]]
[f 0 5 65278][f 2 1]I get it now...[n][f 1 1][e]
[f 0 5 65278][f 2 1]The Shadows can attack when you cut[n]the rope here.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Senpai, stay alert![n][f 1 1][e]

[msg TOMB_ENC_1F_END_1 [Rise]]
[f 0 5 65278][f 2 1]Hey Senpai, have you noticed?[n][f 1 1][e]
[f 0 5 65278][f 2 1]You regain spirit during battle.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Maybe you can use that to stay ahead[n]in the battles to come.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wish you could recover a little more,[n]though...[n][f 1 1][e]

[msg TOMB_ENC_1F_END_2 [Rise]]
[f 0 5 65278][f 2 1]You could fight while waiting to recover,[n]but it's pretty tiring if all the battles[n]are gonna be like this.[n][f 1 1][e]
[f 0 5 65278][f 2 1]What can we do...?[n][f 1 1][e]

[msg TOMB_ENC_1F_END_3_1 [Rise]]
[f 0 5 65278][f 2 1]Oh! I know, Senpai![n][f 1 1][e]
[f 0 5 65278][f 2 1]Why don't you make sure to use the items[n]you get from treasure chests and beating[n]Shadows?[n][f 1 1][e]

[msg TOMB_ENC_1F_END_3_2 [Rise]]
[f 0 5 65278][f 2 1]Check and see if you have anything you[n]can use![n][f 1 1][e]

[msg TOMB_ENC_5F_DOOR [Rise]]
[f 0 5 65278][f 2 1]Hang on! I feel something...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It looks like you can be attacked by Shadows[n]when you cut the ropes here, too...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Are you ready, Senpai?[n][f 1 1][e]

[msg TOMB_ENC_7F_DOOR_1 [Rise]]
[f 0 5 65278][f 2 1]*sigh* Again...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Does she really want us to not come after[n]her that much? Is that what she really thinks?[n][f 1 1][e]

[msg TOMB_ENC_7F_DOOR_2 [Rise]]
[f 0 5 65278][f 2 1]But we've come this far. We're not[n]going to let her have her way here.[n]Right, Senpai!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Are you ready? When you cut this rope,[n]you'll be attacked by Shadows![n][f 1 1][e]

[msg FIRST_DOOR]
[f 0 5 65278][f 2 1]> You sense someone ahead...[n][f 1 1][e]

[msg OPEN_FDOOR_OK]
[f 0 5 65278][f 2 1]> Will you continue?[n][f 1 1][e]

[msg TEST]
[f 0 5 65278][f 2 1]> Test[n][f 1 1][e]

[msg New_Death_Msg]
[f 0 5 65278][f 2 1]> You should hurry to the next floor...[n][f 1 1][e]

[msg HELP_REAPER]
[f 0 5 65278][f 2 1]When 21 chests have been opened, you[n]will begin to hear the sound of an[n]intensely terrifying presence...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Interacting with a chest and moving[n]on to another floor will cause the[n]chain rattling to cease.[n][f 1 1][e]

[msg New_Death_Msg_2]
[f 0 5 65278][f 2 1]> You should hurry to the next floor...[n][f 1 1][e]

[msg HELP_REAPER_2]
[f 0 5 65278][f 2 1]When 21 chests have been opened, you[n]will begin to hear the sound of an[n]intensely terrifying presence...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Interacting with a chest and moving[n]on to another floor will cause the[n]chain rattling to cease.[n][f 1 1][e]

[msg CRACK_KEY]
[f 0 5 65278][f 2 1]> Open the treasure box with Crack Wheat?[n]    (Crack Wheat remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg CHEST_KEY]
[f 0 5 65278][f 2 1]> Open the treasure box with Chest Key?[n]    (Chest Key remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg CUSTOMITEM]
[f 0 5 65278][f 2 1]> Obtained [f 2 5 3 65535 0].[n][f 1 1][e]

[msg CUSTOMITEM2]
[f 0 5 65278][f 2 1]> Obtained [f 2 5 3 65535 0].[n][f 1 1][e]

[msg CUSTOMITEM3]
[f 0 5 65278][f 2 1]> Obtained [f 2 5 3 65535 0] x 1.[n][f 1 1][e]

