[msg CRACK_KEY]
[f 0 5 65278][f 2 1]> Open the treasure box with Crack Wheat?[n]    (Crack Wheat remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg CHEST_KEY]
[f 0 5 65278][f 2 1]> Open the treasure box with Chest Key?[n]    (Chest Key remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg CUSTOMITEM]
[f 0 5 65278][f 2 1]> Obtained [f 2 5 3 65535 0].[n][f 1 1][e]

[msg CUSTOMITEM2]
[f 0 5 65278][f 2 1]> Obtained [f 2 5 3 65535 0].[n][f 1 1][e]

[msg CUSTOMITEM3]
[f 0 5 65278][f 2 1]> Obtained [f 2 5 3 65535 0] x 1.[n][f 1 1][e]