[msg MSG_000 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 20 0 1][f 3 1 1 0 0 1]Agh... Ugh...[n][f 1 3 -1][f 1 1][e]

[sel SEL_001]
[f 0 5 -258][f 2 1]"What are you doing?"[e]
[f 0 5 -258][f 2 1]"Are you all right?"[e]
[f 0 5 -258][f 2 1]"Trying to escape, huh?"[e]

[msg MSG_002 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 20 0 1][f 3 1 1 0 0 2]I-I was scared... So I... I...[n][f 1 3 -1][f 1 1][e]

[msg MSG_003 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 20 0 1][f 3 1 1 0 0 3]Ngh... Urgh...[n][f 1 3 -1][f 1 1][e]

[msg MSG_004 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 20 0 1][f 3 1 1 0 0 4]I-I...[n][f 1 3 -1][f 1 1][e]

[msg MSG_005 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 5]You have your life... and now you want[n]your freedom, too!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_006 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 3 -1 1][f 3 1 1 0 0 6]It's your fault that Nanako-chan's...![n][f 1 3 -1][f 1 1][e]

[msg MSG_007 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 20 0 1][f 3 1 1 0 0 7]I-I, I didn't, I...[n][f 1 3 -1][f 1 1][e]

[msg MSG_008 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 5 -1 1][f 3 1 1 0 0 8]12 o'clock... Is it the Midnight Channel?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 9]Hey, isn't this...!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_009 [Other Namatame]]
[f 0 5 -258][f 2 1][f 4 6 43 2 0 1][f 3 1 1 0 0 10]I failed to save her. It's because you[n]got in my way.[n][f 1 3 -1][f 1 1][e]

[msg MSG_010 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 11]Another Namatame...!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 12]How!? The real one's right here, and we[n]already beat his Shadow...[n][f 1 3 -1][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1][f 3 1 1 0 0 13]No... Come to think of it, Namatame[n]never faced his other self.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 14]And we didn't witness his Shadow returning[n]to his body as a Persona, either...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 15]Perhaps that's why we're seeing this now...[n][f 1 3 -1][f 1 1][e]

[msg MSG_012 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 20 0 1][f 3 1 1 0 0 16]What... the...[n][f 1 3 -1][f 1 1][e]

[msg MSG_013 [Other Namatame]]
[f 0 5 -258][f 2 1][f 4 6 43 1 0 1][f 3 1 1 0 0 17]I failed. But it wasn't my fault.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 18]And the law can't touch me anyway... [n][f 1 3 -1][f 1 1][e]

[msg MSG_014 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 20 0 1][f 3 1 1 0 0 19]Wh-What...!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_015 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 20]Is that what Namatame's really thinking!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 21]Then... he wasn't deranged or anything...[n]He knew what he was doing...![n][f 1 3 -1][f 1 1][e]

[msg MSG_016 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 22]To hell with the law... I won't ever forgive[n]what you did...![n][f 1 3 -1][f 1 1][e]

[msg MSG_017 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 20 0 1][f 3 1 1 0 0 23]Th-This... Please... Stop...[n][f 1 3 -1][f 1 1][e]

[msg MSG_018 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 3 -1 1][f 3 1 1 0 0 24]Huh? Stop what? We ain't even done[n]anything yet...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 25]Or do you want us to do something...?[n]Something fitting for a bastard like you![n][f 1 3 -1][f 1 1][e]

[msg MSG_019 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 26]K-Kanji...[n][f 1 3 -1][f 1 1][e]

[msg MSG_020 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 4 -1 1][f 3 1 1 0 0 27]......[n][f 1 3 -1][f 1 1][e]

[msg MSG_021 [Other Namatame]]
[f 0 5 -258][f 2 1][f 4 6 43 1 0 1][f 3 1 1 0 0 28]Do whatever you want. You hate me[n]because the child died, don't you?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 29]I don't care either way. Living or dying[n]makes no difference to me.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 30]But you... You're different. *chuckle*[n]You can't do such a thing. You wouldn't[n]dare, right?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 31]*chuckle* I'll continue "saving" people...[n]It's my mission...![n][f 1 3 -1][f 1 1][e]

[msg MSG_022 [Yukiko]]
[f 0 5 -258][f 2 1][f 4 6 4 4 -1 1][f 3 1 1 0 0 32]Mission...!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_023 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1][f 3 1 1 0 0 33]My god...[n][f 1 3 -1][f 1 1][e]

[msg MSG_024 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 21 0 1][f 3 1 1 0 0 34]P-Please stop...[n][f 1 3 -1][f 1 1][e]

[msg MSG_025 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 35]He wants us to stop. What should we do?[n][f 1 3 -1][f 1 1][e]

[msg MSG_026 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 36]Wh-What do you mean...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_027 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 3 -1 1][f 3 1 1 0 0 37]We can't let this bastard do whatever[n]he pleases.[n][f 1 3 -1][f 1 1][e]

[msg MSG_028 [Yukiko]]
[f 0 5 -258][f 2 1][f 4 6 4 3 -1 1][f 3 1 1 0 0 38]Still... What are you going to do?[n][f 1 3 -1][f 1 1][e]

[msg MSG_029 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 39]No way I'm gonna walk out of here doing[n]nothing...[n][f 1 3 -1][f 1 1][e]

[msg MSG_030 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 4 -1 1][f 3 1 1 0 0 40]I-I understand, but...[n][f 1 3 -1][f 1 1][e]

[msg MSG_031 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1][f 3 1 1 0 0 41]This must be a luxury suite. Most hospital[n]wards don't have such large televisions...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 42]Why, with something like this in the room,[n]this man could escape at any time...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 43]Although once he enters... he may find[n]there's no way out.[n][f 1 3 -1][f 1 1][e]

[msg MSG_032 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 5 -1 1][f 3 1 1 0 0 44]Wait a second! Y-You don't mean...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 45]Are you... serious...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_033 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 3 -1 1][f 3 1 1 0 0 46]You just gonna turn your back and[n]walk away?[n][f 1 3 -1][f 1 1][e]

[msg MSG_034 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 47]That's... But...![n][f 1 3 -1][f 1 1][e]

[msg MSG_035 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 3 -1 1][f 3 1 1 0 0 48]Wh-What's gotten into you guys!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_036 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 3 -1 1][f 3 1 1 0 0 49]This is crazy! How can we do something[n]like that!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_037 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 50]Chie![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 51]Everyone... Listen to me.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 52]If we're gonna do this... now is our only[n]shot. We won't get a second chance.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 53]At this rate, the guy's gonna get off[n]the hook... And he'll go around "saving"[n]people again![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 54]You just heard what this bastard's[n]really thinking![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 55]If that happens, it'll be just like Nanako-[n]chan and Senpai... Who knows how many[n]innocent people will die this time?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 56][x 0x80 0x87]I cant let something like that go...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 57]Someone close to me died... Her killer[n]can't be convicted... And now I'm gonna[n]let the same thing happen again?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 8 2 11][f 4 9 2 7 5 17 5][f 3 1 1 0 0 58]There's no way I can do that! It's just[n]wrong, isn't it!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_038 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 4 -1 1][f 3 1 1 0 0 59]B-But... Yosuke...[n][f 1 3 -1][f 1 1][e]

[msg MSG_039 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 60]All we have to do is push him inside[n]the TV... That's it. We do that one[n]thing, and this is all over.[n][f 1 3 -1][f 1 1][e]

[msg MSG_040 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 4 -1 1][f 3 1 1 0 0 61]J-Just... push him inside...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_041 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 62]If any of you want no part in this, just leave[n]the room. I'm not gonna force you to stay.[n][f 1 3 -1][f 1 1][e]

[msg MSG_042 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 63]As for me, nothing could make me forgive[n]this bastard... But before we do this, I[n]want to hear what you think.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 64]What do you want to do... Leader?[n][f 1 3 -1][f 1 1][e]

[sel SEL_043]
[f 0 5 -258][f 2 1]"Push the bastard in."[e]
[f 0 5 -258][f 2 1]"I can't stay here."[e]
[f 0 5 -258][f 2 1]"Wait a second here..." *[e]

[msg MSG_044 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 65]Yeah... We'll end this here and now...[n][f 1 3 -1][f 1 1][e]

[msg MSG_045 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 3 -1 1][f 3 1 1 0 0 66]Wait a second...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 67]Do you really understand what you're[n]about to do...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 68]It's the exact same thing Namatame's[n]been doing![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 69]I hate the guy too, but you really[n]wanna go that far!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_046 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 70]Is getting revenge... the right thing[n]to do...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 71]But if we don't do anything, he might...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 72]I... I don't know anymore...[n][f 1 3 -1][f 1 1][e]

[msg MSG_047 [Yukiko]]
[f 0 5 -258][f 2 1][f 4 6 4 1 -1 1][f 3 1 1 0 0 73]Are you sure about this...?[n][f 1 3 -1][f 1 1][e]

[sel SEL_048]
[f 0 5 -258][f 2 1]"Do it already."[e]
[f 0 5 -258][f 2 1]"No... We can't." *[e]

[msg MSG_049 [Yukiko]]
[f 0 5 -258][f 2 1][f 4 6 4 4 -1 1][f 3 1 1 0 0 74]You really mean it...? There's no[n]other way?[n][f 1 3 -1][f 1 1][e]

[msg MSG_050 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 75]What about you guys? Remember, there's[n]no need to stay if you don't want to.[n][f 1 3 -1][f 1 1][e]

[msg MSG_051 [Yukiko]]
[f 0 5 -258][f 2 1][f 4 6 4 4 -1 1][f 3 1 1 0 0 76]...I'll stay.[n][f 1 3 -1][f 1 1][e]

[msg MSG_052 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 4 -1 1][f 3 1 1 0 0 77]Me too.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 78]I won't be the only one to walk out on[n]this... I'd only suffer more that way.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 79]If this is what we've decided...[n]I'll stick with it to the end.[n][f 1 3 -1][f 1 1][e]

[msg MSG_053 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 80]Me too. No matter how we end it...[n]I want to witness it.[n][f 1 3 -1][f 1 1][e]

[msg MSG_054]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> The other world that caused all this[n]to happen will surely take care of[n]the rest...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> The case will be closed by the Shadow[n]that will appear from Namatame...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> With this... everything has come to[n]an end.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You should go back to Nanako...[n][f 1 3 -1][f 1 1][e]

[msg MSG_055 [Yukiko]]
[f 0 5 -258][f 2 1][f 4 6 4 2 -1 1][f 3 1 1 0 0 81]Thank goodness... I knew you'd say so.[n][f 1 3 -1][f 1 1][e]

[msg MSG_056 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 82]How the hell can you be so half-assed[n]about this...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 2 7 5 18 5][f 3 1 1 0 0 83]Are you okay with what this bastard did...!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_057 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 3 -1 1][f 3 1 1 0 0 84]Of course we're not![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 85]But can you look me in the eye and say[n]you're okay with doing the same thing[n]this guy did!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 86]It's just like how you feel right now...[n]that you can't turn your back and do[n]nothing...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 87]We're not gonna sit back and watch while[n]our friend becomes a murderer, you moron![n][f 1 3 -1][f 1 1][e]

[msg MSG_058 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 3 -1 1][f 3 1 1 0 0 88]To kill someone because they killed[n]someone first... I can't decide on[n]something that serious...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 89]But... But still![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 90]If you have it in you to be this angry[n]for someone who was close to you... then[n]you mustn't kill...![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 91]That's something you can never take back![n][f 1 3 -1][f 1 1][e]

[msg MSG_059 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 3 -1 1][f 3 1 1 0 0 92]So we leave it to the cops? You trust[n]them to handle it!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_060 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 4 -1 1][f 3 1 1 0 0 93]Even if we can't trust them, from here[n]on is no longer our battle...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 94]It's Dojima-san and his fellow officers'[n]fight to convict the suspect... Is that[n]what you're trying to say...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_061 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 4 -1 1][f 3 1 1 0 0 95]......[n][f 1 3 -1][f 1 1][e]

[msg MSG_062 [Yukiko]]
[f 0 5 -258][f 2 1][f 4 6 4 4 -1 1][f 3 1 1 0 0 96]I'm proud that I could protect[n]this town with you all.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 97]That's why I don't want to make this[n]terrible situation even worse by doing[n]something like this.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 98]I want to keep going to school with[n]you all... and make more memories[n]with my friends.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 99]I don't want one of those memories to[n]be of us killing someone...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 100]So what if there's another crime!? We can[n]still save people, like we always have![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 101]Nothing has happened yet... Then why[n]assume that our future will be filled[n]with misfortune...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_063 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 4 -1 1][f 3 1 1 0 0 102]Nothing's happened yet...[n]Our future hasn't been decided...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 103]......[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 2 19 5 18 5][f 3 1 1 0 0 104]...Let's go back to Nanako-chan's room.[n][f 1 3 -1][f 1 1][e]

[msg MSG_064 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 105]What...? Are you saying you forgive[n]this bastard!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_065 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1][f 3 1 1 0 0 106]I thought you'd feel the same way[n]we do... Senpai.[n][f 1 3 -1][f 1 1][e]

[msg MSG_066 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 3 -1 1][f 3 1 1 0 0 107]You're gonna let this go!? Didn't you[n]see what happened to Nanako-chan!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_067 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 108]Look, just think about this...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 2 7 5 18 5][f 3 1 1 0 0 109]Are you sure about that?[n][f 1 3 -1][f 1 1][e]

[sel SEL_068]
[f 0 5 -258][f 2 1]"...Push him in."[e]
[f 0 5 -258][f 2 1]"Don't do this." *[e]

[msg MSG_069 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 110]We don't have time to wait! If we don't[n]do this now, the cops'll come back![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 111]What're you trying to say!?[n][f 1 3 -1][f 1 1][e]

[sel SEL_070]
[f 0 5 -258][f 2 1]"We're missing something." *[e]
[f 0 5 -258][f 2 1]"Leave him for the police."[e]
[f 0 5 -258][f 2 1]"This won't change anything."[e]

[msg MSG_071 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 112]Do you seriously think that?[n][f 1 3 -1][f 1 1][e]

[msg MSG_072 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 113]That's bullshit![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 114]At the very least, we can be sure that a[n]tragedy like this will never happen again![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 115]I don't want anybody else to suffer like[n]we did, ever again!![n][f 1 3 -1][f 1 1][e]

[msg MSG_073 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 3 -1 1][f 3 1 1 0 0 116]I didn't think we'd end up like this...[n]I mean, I thought we were all on the[n]same page...[n][f 1 3 -1][f 1 1][e]

[msg MSG_074 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 4 -1 1][f 3 1 1 0 0 117]......[n][f 1 3 -1][f 1 1][e]

[msg MSG_075 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 118]Something we don't know...?[n]What don't we know!?[n][f 1 3 -1][f 1 1][e]

[sel SEL_076]
[f 0 5 -258][f 2 1]"Whether he'll kill again."[e]
[f 0 5 -258][f 2 1]"Whether revenge is right."[e]
[f 0 5 -258][f 2 1]"Namatame's true feelings." *[e]
[f 0 5 -258][f 2 1]"Whether he can be tried."[e]

[msg MSG_077 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 119]How should I know!? What I do know is,[n]if we let it happen again, that'll be[n]too late![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 120]Preventing this from happening again...[n]Nothing's more important than that for[n]me right now.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 121]Sorry... but I don't understand how you[n]can hesitate just because of that.[n][f 1 3 -1][f 1 1][e]

[msg MSG_078 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 122]...It probably isn't.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 123]But if we let him go free, and he claims[n]another victim... is THAT right?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 124]Would it make Nanako-chan happy if we[n]let something like that happen!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 125]Sorry... but I don't understand how you[n]can hesitate just because of that.[n][f 1 3 -1][f 1 1][e]

[msg MSG_079 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 126]Why do you think this bastard killed[n]them the way he did in the first place?[n]He knew full well he couldn't be tried.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 127]Leaving him to trial with no evidence[n]against him... You think a gamble like[n]that would make Nanako-chan happy!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 128]Sorry... but I don't understand how you[n]can hesitate just because of that.[n][f 1 3 -1][f 1 1][e]

[msg MSG_080 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 129]But we just heard the guy's true feelings[n]on TV![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 130]What didn't you understand!?[n][f 1 3 -1][f 1 1][e]

[sel SEL_081]
[f 0 5 -258][f 2 1]"Why he's scared."[e]
[f 0 5 -258][f 2 1]"Something's bothering me." *[e]
[f 0 5 -258][f 2 1]"He can still repent..."[e]
[f 0 5 -258][f 2 1]"I actually don't know."[e]

[msg MSG_082 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 131]I dunno, either he's begging for his life,[n]or he freaked out from seeing his other[n]self face to face...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 132]Who gives a damn? That's not what's[n]important right now![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 133]Why the hell are you so cold about this!?[n]Nanako-chan is dead, for god's sake![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 134]I don't understand you...[n][f 1 3 -1][f 1 1][e]

[msg MSG_083 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 135]Who the hell's side are you on!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 136]He killed Senpai and Nanako-chan,[n]and who's to say he'll stop there!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 137]You think he can just say "I'm sorry"[n]and everything'll be okay!? You think[n]we can forgive him for this!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 138]I don't understand you...[n][f 1 3 -1][f 1 1][e]

[msg MSG_084 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 4 -1 1][f 3 1 1 0 0 139]I don't understand you...[n][f 1 3 -1][f 1 1][e]

[msg MSG_085 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 140]Well, what is it!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 141]I already told you, there's no time to waste![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 142]Are you even getting at something here,[n]or are you just stalling!?[n][f 1 3 -1][f 1 1][e]

[sel SEL_086]
[f 0 5 -258][f 2 1]"...I got nothing."[e]
[f 0 5 -258][f 2 1]"He could escape via the TV."[e]
[f 0 5 -258][f 2 1]"We're missing something..." *[e]

[msg MSG_087 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 4 -1 1][f 3 1 1 0 0 143]......[n][f 1 3 -1][f 1 1][e]

[msg MSG_088 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 144]He'll definitely escape if we DON'T[n]drop him in! No, worse--because he'll[n]get out legally![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 145]Why the hell are you so cold about this!?[n]Nanako-chan is dead, dammit![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 146]I don't understand you...[n][f 1 3 -1][f 1 1][e]

[msg MSG_089 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 147]Missing...? Like what exactly?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 2 7 5 18 5][f 4 8 2 11][f 3 1 1 0 0 148]Dammit... I've heard enough of this bullshit![n]Give me a straight answer![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 149]Are we doing this or not!? That's all[n]I give a damn about right now![n][f 1 3 -1][f 1 1][e]

[sel SEL_090]
[f 0 5 -258][f 2 1]"I can't do it."[e]
[f 0 5 -258][f 2 1]"Calm the hell down!" *[e]
[f 0 5 -258][f 2 1]"I'm sorry..."[e]

[msg MSG_091 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 4 -1 1][f 3 1 1 0 0 150]So... that's your answer, huh...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_092 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 151]Sorry? About what? That you can't do it?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 152]Why are you going on and on about all[n]this crap...? Aren't you suffering most?[n]It's your family who's been killed![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 153]I don't understand you...[n][f 1 3 -1][f 1 1][e]

[msg MSG_093]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You yelled at everyone to calm down.[n][f 1 3 -1][f 1 1][e]

[msg MSG_094 [Namatame]]
[f 0 5 -258][f 2 1][f 4 6 14 20 0 1][f 3 1 1 0 0 154]Nnngh...[n][f 1 3 -1][f 1 1][e]

[msg MSG_095 [Yukiko]]
[f 0 5 -258][f 2 1][f 4 6 4 5 -1 1][f 3 1 1 0 0 155]H-He's right. L-Let's all calm down for[n]a second.[n][f 1 3 -1][f 1 1][e]

[msg MSG_096 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 156]I'm perfectly calm.[n][f 1 3 -1][f 1 1][e]

[msg MSG_097 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 157]Hey, what did you mean by, "we're missing[n]something"...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_098 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 158]What's there to miss with a sick bastard[n]like him!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_099 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 1 -1 1][f 3 1 1 0 0 159]Hey, let's all take a deep breath.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 160]After what happened to Nanako-chan,[n]and seeing Dojima-san... we're not thinking[n]straight right now.[n][f 1 3 -1][f 1 1][e]

[msg MSG_100 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 4 -1 1][f 3 1 1 0 0 161]Tch... Fine...[n][f 1 3 -1][f 1 1][e]

[msg MSG_101]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Everyone took a deep breath.[n][f 1 3 -1][f 1 1][e]

[msg MSG_102]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> It seems that everyone has finally[n]regained their composure...[n][f 1 3 -1][f 1 1][e]

[msg MSG_103 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1][f 3 1 1 0 0 162]You're right... We should calm down and[n]think rationally about this...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 163]I realize now that we've heard almost[n]nothing from Namatame's perspective...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 164]There's no denying that this man brought[n]great harm to Nanako-chan...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 165]But other than that point, the rest comes[n]from our assumptions based on watching[n]the Midnight Channel a moment ago.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 166]I won't deny that we were blinded by the[n]heat of the moment... trying to impute all[n]responsibility to him rashly.[n][f 1 3 -1][f 1 1][e]

[msg MSG_104 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 3 -1 1][f 3 1 1 0 0 167]But...![n][f 1 3 -1][f 1 1][e]

[msg MSG_105 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 168]Yeah, the guy's not saying anything.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 169]Whatever reason he had, there's no doubt[n]about the fact that he'd been throwing[n]people inside the TV.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 170]It was him who put Senpai through that[n]misery...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 171]How can we possibly understand someone[n]who says killing people is the same as[n]"saving" them!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_106 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1][f 3 1 1 0 0 172]Failing to understand and failing to listen[n]are rather different things.[n][f 1 3 -1][f 1 1][e]

[msg MSG_107 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 4 -1 1][f 3 1 1 0 0 173]......[n][f 1 3 -1][f 1 1][e]

[msg MSG_108 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1][f 3 1 1 0 0 174]Truthfully, not all the hitches that were[n]nagging at me have been answered yet.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 175]We'll have to see what he can tell us[n]about them...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 176]...Though it appears he's in no condition[n]to do so at the moment.[n][f 1 3 -1][f 1 1][e]

[msg MSG_109 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 177]True... Dealing with him right now[n]might not solve all the things that[n]are bothering us...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 178]Dammit...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 2 3 5 0 5][f 3 1 1 0 0 179]But you better remember this... I'll do[n]everything I can to stop him from repeating[n]what he's done.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 180]Anytime, anywhere... anything.[n][f 1 3 -1][f 1 1][e]

[sel SEL_110]
[f 0 5 -258][f 2 1]"I feel the same way."[e]
[f 0 5 -258][f 2 1]"Let's just think for now."[e]
[f 0 5 -258][f 2 1]"......"[e]

[msg MSG_111 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 9 -1 1][f 3 1 1 0 0 181]Geez... How the hell can you stay so[n]calm, man?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 182]Then again, that's why you're our leader...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 183]......[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 4 9 2 3 5 0 5][f 3 1 1 0 0 184]Alright. Let's go ahead and think this through[n]as much as we need.[n][f 1 3 -1][f 1 1][e]

[msg MSG_112 [Kanji]]
[f 0 5 -258][f 2 1][f 4 6 6 1 -1 1][f 3 1 1 0 0 185]If we leave any unanswered questions[n]behind, we'll just be lying to ourselves...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 186]Yeah, that ain't gonna cut it...[n]Alright, I'm convinced.[n][f 1 3 -1][f 1 1][e]

[msg MSG_113 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 2 -1 1][f 3 1 1 0 0 187]*sigh* Thank you...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 188]I'll think as hard as I can, and try to help![n][f 1 3 -1][f 1 1][e]

[msg MSG_114 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 2 -1 1][f 3 1 1 0 0 189]We all know how you feel, Yosuke![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 190]C'mon, we've accomplished this much[n]together, haven't we?[n][f 1 3 -1][f 1 1][e]

[msg MSG_115 [Yukiko]]
[f 0 5 -258][f 2 1][f 4 6 4 2 -1 1][f 3 1 1 0 0 191]Right... Together.[n][f 1 3 -1][f 1 1][e]

[msg MSG_116 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 4 -1 1][f 3 1 1 0 0 192]Yeah...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 193]Yeah, you're right.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 4 9 2 3 5 0 5][f 3 1 1 0 0 194]Sorry... and thanks.[n][f 1 3 -1][f 1 1][e]

[msg MSG_117 [Adachi]]
[f 0 5 -258][f 2 1][f 4 6 12 5 0 1][f 3 1 1 0 0 195]Hey... you guys!? What're you doing!?[n]You can't be in here![n][f 1 3 -1][f 1 1][e]

[msg MSG_118 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 196]Oh crap![n][f 1 3 -1][f 1 1][e]

[msg MSG_119 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 5 -1 1][f 3 1 1 0 0 197]W-We were keeping an eye on the suspect.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1][f 3 1 1 0 0 198]The police officers outside seemed to[n]have their hands full helping Dojima-san.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 199]If Namatame were to escape, it would be[n]a disaster for the police's reputation...[n]and their trust in you, Adachi-san.[n][f 1 3 -1][f 1 1][e]

[msg MSG_120 [Adachi]]
[f 0 5 -258][f 2 1][f 4 6 12 1 0 1][f 3 1 1 0 0 200]O-Oh... I see.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 201]We'll tighten security from now on, and[n]I'll arrange for him to be transported out[n]as soon as possible.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 202]So... if you guys can keep quiet about[n]being in here, I'd really appreciate it...[n][f 1 3 -1][f 1 1][e]

[msg MSG_121 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1][f 3 1 1 0 0 203]How is he, Doctor? He seemed to be[n]extremely agitated a moment ago.[n][f 1 3 -1][f 1 1][e]

[msg MSG_122 [Doctor]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 204]He seems fine for now, but he really needs[n]his rest.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 205]Outside, everyone. Doctor's orders.[n][f 1 3 -1][f 1 1][e]

[msg MSG_123 [Adachi]]
[f 0 5 -258][f 2 1][f 4 6 12 1 0 1][f 3 1 1 0 0 206]U-Understood.[n][f 1 3 -1][f 1 1][e]

[msg MSG_124 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 207]We should go too... Let's get back to[n]Nanako-chan's room.[n][f 1 3 -1][f 1 1][e]

[msg MSG_125]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> The window in the room is wide open...[n][f 1 3 -1][f 1 1][e]

[msg MSG_126]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> The case has taken a sharp turn[n]and the Investigation Team is now[n]one step closer to the truth...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> It seems that you will go on with your[n]friends to solve another mystery...[n][f 1 3 -1][f 1 1][e]

