[msg MSG_000 [ ]]
[f 0 5 -258][f 2 1]> Samegawa flood plain...[n][f 1 1][e]

[msg MSG_001 [Naoto]]
[f 0 5 -258][f 2 1]> Naoto brought a new challenge from[n]the Phantom Thief...[n][f 1 4][e]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1]This was in my mailbox this morning.[n][f 1 1][e]
[f 0 5 -258][f 2 1]The Phantom Thief knows where I live...[n][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1]...Which means he had other reasons for[n]having you deliver the first card.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Why you, though...?[n][f 1 1][e]

[sel SEL_003]
[f 0 5 -258][f 2 1]"Because I looked reliable." +2/3[e]
[f 0 5 -258][f 2 1]"Because we looked 'close.'"[e]
[f 0 5 -258][f 2 1]"Because I looked useless." +2/3[e]

[msg MSG_004 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 2 -1 1][f 3 1 1 0 0 543]I don't think that's the sort of metric[n]the culprit would use...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 14 5 10]> Naoto is laughing heartily.[n][f 1 1][e]

[msg MSG_005 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 6 -1 1][f 3 1 1 0 0 536]Wh-What are you saying!? That can't be it![n][f 1 1][e]
[f 0 5 -258][f 2 1]D-Don't blurt out such ridiculous nonsense![n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n]> Naoto is panicking fiercely...[n][f 1 1][e]

[msg MSG_006 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 2 -1 1][f 3 1 1 0 0 543]If that's the case... this Phantom[n]Thief isn't a very good judge of[n]character.[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 14 5 10]> Naoto is laughing heartily.[n][f 1 1][e]

[msg MSG_007 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1]So then, what do you think of the contents[n]of this card?[n][f 1 1][e]

[msg MSG_008 [ ]]
[f 0 5 -258][f 2 1]> The card reads as follows...[n][f 1 1][e]

[msg MSG_009 [Writing on the card]]
[f 0 5 -258][f 2 1]When the banks close, the fruit tree[n]grows. By the large seven at the third[n]is the spot I chose.[n][f 1 1][e]

[msg MSG_010 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1]More cryptic this time. Well, I[n]anticipated that.[n][f 1 1][e]
[f 0 5 -258][f 2 1]The first thing that comes to mind with[n]"fruit tree" is the original card.[n][f 1 1][e]
[f 0 5 -258][f 2 1]But the second sentence...[n][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1]"By the seven," "at the third"...[n]What do these numerical values mean...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]"When the banks close, the fruit tree[n]grows. By the large seven at the third[n]is the spot I chose..."[n][f 1 1][e]

[sel SEL_012]
[f 0 5 -258][f 2 1]"7 and 3 o'clock, maybe...?"[e]
[f 0 5 -258][f 2 1]"The phrasing is suspicious."[e]
[f 0 5 -258][f 2 1]"The numbers are important." +3/3[e]

[msg MSG_013 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 4 -1 1]No, there's nothing peculiar about those[n]particular positions...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n]> Naoto is sighing...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1][f 1 5]Naoto[n]"When the banks close, the fruit tree[n]grows..."[n][f 1 1][e]
[f 0 5 -258][f 2 1]It's incomprehensible... "Seven" and[n]"third"...?[n][f 1 1][e]

[msg MSG_014 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 4 -1 1]The phrasing...? I don't see anything[n]odd about that...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n]> Naoto suddenly became quiet...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1][f 1 5]Naoto[n]...Hm?[n][f 1 1][e]
[f 0 5 -258][f 2 1]The words... The seven and third...[n][f 1 1][e]

[msg MSG_015 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1]The numbers themselves...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]...The seven and the third...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 14 10 10]> Naoto's eyes lit up.[n][f 1 1][e]

[msg MSG_016 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 3 -1 1]"When the banks close, the fruit tree[n]grows..." Look at the third and seventh[n]words...[n][f 1 1][e]
[f 0 5 -258][f 2 1]"Banks" and "tree." In other words,[n]"by the large tree at the banks is the[n]spot I chose!"[n][f 1 1][e]
[f 0 5 -258][f 2 1]A-Anyway, let's search for the biggest tree[n]at this river's banks![n][f 1 1][e]

[msg MSG_017 [ ]]
[f 0 5 -258][f 2 1]> You searched the riverbank with Naoto...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> There was something buried by the tree[n]you found...[n][f 1 1][e]

[msg MSG_018 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1]I knew it...[n]This watch brings back memories...[n][f 1 1][e]

[msg MSG_019 [ ]]
[f 0 5 -258][f 2 1]> Naoto holds a digital watch, slightly large[n]for a child's wrist.[n][f 1 1][e]

[msg MSG_020 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 2 -1 1][f 3 1 1 0 0 557]This is pretty advanced, you know.[n][f 1 1][e]
[f 0 5 -258][f 2 1]It's one of the seven tools of the detective.[n]It has an extremely strong backlight.[n][f 1 1][e]
[f 0 5 -258][f 2 1]You can use it to blind the enemy...[n][f 1 1][e]
[f 0 5 -258][f 2 1]...I modified it when I was a child.[n][f 1 1][e]

[msg MSG_021 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 2 -1 1]I've always loved this sort of thing,[n]ever since childhood.[n][f 1 1][e]
[f 0 5 -258][f 2 1]I preferred robots and cars to dolls[n]and teddy bears...[n][f 1 1][e]
[f 0 5 -258][f 2 1]I liked high places, so I had a secret base[n]in the trees...[n][f 1 1][e]
[f 0 5 -258][f 2 1]I enjoyed that...[n][f 1 1][e]

[msg MSG_022 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 4 -1 1]Why...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]Why couldn't I have been born male...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]It would have been much easier for me...[n]I could have done what I wanted to with[n]gusto...[n][f 1 1][e]
[f 0 5 -258][f 2 1]It's funny, isn't it...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]......[n][f 1 1][e]

[sel SEL_023]
[f 0 5 -258][f 2 1]"I'm glad you're a girl." (Love)[e]
[f 0 5 -258][f 2 1]"Your gender doesn't matter." +3/3[e]
[f 0 5 -258][f 2 1]"Nothing you can do."[e]

[msg MSG_024 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 5 -1 1][f 3 1 1 0 0 556][f 4 2]-senpai...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 7 2 -1 1]Now that I have people like you who'll say that[n]to me... What right have I to complain?[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 7 4 -1 1]Thank you, [f 4 2]-san.[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 14 15 10]> Naoto is smiling sadly...[n][f 1 1][e]

[msg MSG_025 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 4 -1 1]. . .[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 7 4 -1 1]Maybe you're right.[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 14 15 10]> Naoto looks confused.[n][f 1 1][e]

[msg MSG_026 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 4 -1 1][f 3 1 1 0 0 515]...You're right. Complaining about it[n]won't change anything...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 3 1 1 0 0 557][f 1 5] [n]> Naoto smiles sadly...[n][f 1 1][e]

[msg MSG_027 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 2 -1 1]Really... It's quite difficult to keep[n]my composure when you're around.[n][f 1 1][e]
[f 0 5 -258][f 2 1]I feel like I'm being lectured...[n]Like I'm still a child...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 7 6 -1 1]......[n][f 1 1][e]

[msg MSG_028 [ ]]
[f 0 5 -258][f 2 1]> Naoto looks at her feet, embarrassed...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You feel your relationship with Naoto[n]has grown deeper...[n][f 1 1][e]

[msg MSG_029 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 1 -1 1]I-It seems I've been doing all the talking...[n][f 1 1][e]

[msg MSG_030 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 2 -1 1]Why don't you tell me about yourself?[n]What were you like as a child...?[n][f 1 1][e]

[msg MSG_031 [Naoto]]
[f 0 5 -258][f 2 1][f 4 6 7 2 -1 1]...I wish I could have seen it.[n][f 1 1][e]

[msg MSG_032 [ ]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 563]> You chatted idly with Naoto, then[n]went home.[n][f 1 1][e]

[msg MSG_KIRI [ ]]
[f 0 5 -258][f 2 1]> Fog has enveloped the area...[n][f 1 1][e]

[msg MSG_000]
[f 0 5 -258][f 2 1]> Samegawa flood plain...[n][f 1 1][e]

[msg MSG_008]
[f 0 5 -258][f 2 1]> The card reads as follows...[n][f 1 1][e]

[msg MSG_017]
[f 0 5 -258][f 2 1]> You searched the riverbank with Naoto...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> There was something buried by the tree[n]you found...[n][f 1 1][e]

[msg MSG_019]
[f 0 5 -258][f 2 1]> Naoto holds a digital watch, slightly large[n]for a child's wrist.[n][f 1 1][e]

[msg MSG_028]
[f 0 5 -258][f 2 1]> Naoto looks at her feet, embarrassed...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You feel your relationship with Naoto[n]has grown deeper...[n][f 1 1][e]

[msg MSG_032]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 563]> You chatted idly with Naoto, then[n]went home.[n][f 1 1][e]

[msg MSG_KIRI]
[f 0 5 -258][f 2 1]> Fog has enveloped the area...[n][f 1 1][e]

