[msg myth_000]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_001]
[f 0 5 -258][f 2 1]One of the ancient[n]gods who existed[n]before Japan began.[n]He created the[n]Oyashima from chaos,[n]then gave birth to[n]countless children[n]and laid the[n]foundation of soil[n]and nature.[n][e]

[msg myth_002]
[f 0 5 -258][f 2 1]Goddess of Aztec[n]myth who governs[n]night and fear, she[n]symbolizes death[n]and evil. Her war[n]with the sun god[n]caused a catastrophic[n]solar eclipse. She[n]seeks a sacrifice[n]every 52 years.[n][e]

[msg myth_003]
[f 0 5 -258][f 2 1]One of the 72[n]demons of the[n]Goetia. He appears[n]as a leopard and[n]can see the past[n]and future. He can[n]control fire[n]and burn all his[n]adversaries to[n]death.[n][e]

[msg myth_004]
[f 0 5 -258][f 2 1]A major Norse[n]deity, known as a[n]trickster who[n]clashes with the[n]other gods. Blood[n]brothers with Odin,[n]but was later[n]punished for his[n]role in Balder's[n]death.[n][e]

[msg myth_005]
[f 0 5 -258][f 2 1]Goddess of war and[n]love, revered in[n]ancient Mesopotamia.[n]She seduced many men[n]to their doom, but[n]the hero Gilgamesh[n]spurned her, causing[n]her to murder his[n]best friend Enkidu.[n][e]

[msg myth_006]
[f 0 5 -258][f 2 1]Also known as Jack[n]O'Lantern, he was[n]an Irish farmer who[n]persuaded Satan[n]not to take him to[n]hell. When he was[n]refused entry into [n]heaven, he wandered[n]earth as a pumpkin-[n]headed soul.[n][e]

[msg myth_007]
[f 0 5 -258][f 2 1]A winter fairy of[n]European descent.[n]Normally an[n]innocent creature,[n]but if provoked,[n]he will kill his[n]victim by covering[n]him in snow.[n][e]

[msg myth_008]
[f 0 5 -258][f 2 1]A warrior queen of[n]the Land of Shadows[n]in Celtic lore.[n]She taught the[n]Irish hero Cu[n]Chulainn the art[n]of war, and gave[n]him the spear[n]Gae Bolg.[n][e]

[msg myth_009]
[f 0 5 -258][f 2 1]A wicked witch of[n]Balinese lore. She[n]represents evil,[n]and is Barong's[n]eternal rival.[n]Even if defeated,[n]she will come back[n]to life, and their[n]battle will have[n]no end.[n][e]

[msg myth_010]
[f 0 5 -258][f 2 1]A god who migrated[n]from Silla to Kyushu[n]to give oracles to[n]the people. Later[n]deified as a[n]guardian of samurai[n]across Japan. Also[n]called Yahata, or[n]"a figure for gods[n]to possess."[n][e]

[msg myth_011]
[f 0 5 -258][f 2 1]A legendary hero in[n]Celtic folklore.[n]His name means "The[n]Hound of Culann" [n]and his true name is[n]Setanta. There are[n]many tales of his[n]exciting adventures[n]with his spear[n]Gae Bolg.[n][e]

[msg myth_012]
[f 0 5 -258][f 2 1]One of Goetia's 72[n]demons, known as[n]the President of[n]Hell. He can shift[n]his shape from[n]leopard to human,[n]and reveals the[n]truth behind[n]divine mysteries.[n][e]

[msg myth_013]
[f 0 5 -258][f 2 1]One of the four[n]aspects of the[n]human soul, as[n]described in[n]Shinto teachings.[n]It is said to[n]bring good luck[n]in the areas of[n]health and[n]medicine.[n][e]

[msg myth_014]
[f 0 5 -258][f 2 1]Water spirits in[n]Hindu mythology.[n]They are beautiful[n]young women who[n]dance for the gods.[n]They also guide[n]heroes fallen in[n]battle to paradise.[n][e]

[msg myth_015]
[f 0 5 -258][f 2 1]A dual-gendered god[n]whose appearance is[n]half that of the[n]destroyer Shiva and[n]half his wife,[n]Parvati. Ardha is[n]the ideal figure of[n]Shaktism; the[n]perfect god.[n][e]

[msg myth_016]
[f 0 5 -258][f 2 1]This beautiful[n]goddess of love is[n]one of Shiva's[n]wives in Hindu[n]mythology. She won[n]Shiva's love,[n]overcoming his[n]asceticism.[n][e]

[msg myth_017]
[f 0 5 -258][f 2 1]The goddess of life[n]in Shinto myth. She[n]once mediated[n]between Izanagi[n]and Izanami during[n]their confrontation[n]in Yomi, the land[n]of the dead.[n][e]

[msg myth_018]
[f 0 5 -258][f 2 1]Repeller of evil[n]found by En-no-[n]Ozunu at Kinpusen.[n]Believed to be a[n]fusion of Buddha,[n]Guanyin, and[n]Maitreya, a god who[n]originated from Japan[n]rather than[n]Buddhavacana.[n][e]

[msg myth_019]
[f 0 5 -258][f 2 1]In Hindu myth, she[n]is the goddess of[n]rivers and patron[n]of speech, writing,[n]learning, and the[n]arts and sciences.[n]Brahma is her[n]husband.[n][e]

[msg myth_020]
[f 0 5 -258][f 2 1]7 days after its[n]birth, a wolf killed[n]its mother. Yoshizane[n]Satomi later promised[n]his daughter's hand[n]if it could defeat[n]the enemy, but after[n]Yatsufusa's success,[n]Yoshizane's retainer[n]shot it dead.[n][e]

[msg myth_021]
[f 0 5 -258][f 2 1]Phrygian goddess of[n]the earth. Attis[n]was her son and[n]consort, but she[n]drove him mad, and[n]he castrated[n]himself. Her[n]orgiastic cult[n]spread to Greece.[n][e]

[msg myth_022]
[f 0 5 -258][f 2 1]In Zoroastrian myth,[n]Sraosha's duty is[n]to listen to the[n]cry of humans for[n]Ahura Mazda. Also[n]known to descend[n]after sunset to[n]vanquish evil. Its[n]name literally[n]means "observance."[n][e]

[msg myth_023]
[f 0 5 -258][f 2 1]A prophetic Taoist[n]god, originally[n]known as Mao Shogun.[n]Due to a linguistic[n]error involving the[n]Chinese word for[n]cat, his name[n]was changed to[n]Neko Shogun.[n][e]

[msg myth_024]
[f 0 5 -258][f 2 1]According to Hindu[n]myth, she is a[n]consort of Shiva.[n]Also called The[n]Black One, she is[n]a symbol of[n]destruction. She[n]is usually depicted[n]wearing a chain of[n]human heads.[n][e]

[msg myth_025]
[f 0 5 -258][f 2 1]A ghost who appears[n]at night on a bushy[n]path to jump on the[n]backs of passersby.[n]Once on, he won't[n]get off easily, but[n]some believe he will[n]transform into money[n]if taken back to[n]one's home.[n][e]

[msg myth_026]
[f 0 5 -258][f 2 1]A subordinate demon[n]of Hell, ordered by[n]Beelzebub to stoke[n]the fires that heat[n]its iron pots. He[n]also throws coals[n]into the fire to[n]torment humans[n]trapped in Hell.[n][e]

[msg myth_027]
[f 0 5 -258][f 2 1]A serpentine woman[n]of Greek myth, she[n]was the queen of[n]Libya. It has a[n]beautiful woman's[n]torso, and the tail[n]of a snake. It[n]feeds on the blood[n]of young men.[n][e]

[msg myth_028]
[f 0 5 -258][f 2 1]In Norse myth, he[n]is the father of[n]the gods, and the[n]god of wisdom. He[n]rides his eight-[n]legged horse[n]Sleipnir, bearing[n]his spear Gungnir[n]and wearing his[n]ring Draupnir.[n][e]

[msg myth_029]
[f 0 5 -258][f 2 1]The king of snow,[n]ruling over an[n]infinite number of[n]Jack Frosts. He has[n]the power to freeze[n]the entire world,[n]but his personality[n]is actually very[n]naive.[n][e]

[msg myth_030]
[f 0 5 -258][f 2 1]A Kunitsu deity of[n]Japanese mythology[n]that governs[n]agriculture and[n]medicine. Said to[n]have built the[n]country of Izumo[n]with Susano-o's[n]daughter,[n]Suseri-Hime.[n][e]

[msg myth_031]
[f 0 5 -258][f 2 1]This water spirit[n]lives in lakes and[n]fountains, appearing[n]as a beautiful[n]woman. It has no[n]soul unless it[n]marries a human[n]man, which is a[n]serious taboo[n]among Undines.[n][e]

[msg myth_032]
[f 0 5 -258][f 2 1]A cheerful, mischief-[n]loving spirit that[n]governs air. Since[n]belief in it dates[n]back generations,[n]many have tried to[n]find a real Sylph.[n][e]

[msg myth_033]
[f 0 5 -258][f 2 1]One of the Goetia's[n]72 demons, he[n]appears as a great[n]sea monster. He is[n]linguistically[n]skilled, and a[n]master of rhetoric.[n][e]

[msg myth_034]
[f 0 5 -258][f 2 1]A cursed Norse[n]spirit in the form[n]of a beautiful[n]woman, known to[n]bloom from the[n]blood of hanged men.[n]She was believed[n]to tell secrets if[n]properly tended to.[n][e]

[msg myth_035]
[f 0 5 -258][f 2 1]An ancient Iranian[n]god of contracts,[n]he was also revered[n]as a sun god. At[n]the end of time,[n]he will descend[n]from the heavens[n]and raise the dead[n]for final judgment.[n][e]

[msg myth_036]
[f 0 5 -258][f 2 1]A monk who died[n]while fasting. His[n]spiritual power[n]allows his body to[n]continue to exist[n]without rotting.[n]It is said that he[n]will appear before[n]people on the day[n]of salvation.[n][e]

[msg myth_037]
[f 0 5 -258][f 2 1]A serpent with 1000[n]heads of Hindu[n]myth. Ananta is[n]Sanskrit for[n]"infinite." After[n]resting on him,[n]Vishnu woke up and[n]created the[n]universe.[n][e]

[msg myth_038]
[f 0 5 -258][f 2 1]The Nihonshoki sword[n]deity who pacified[n]Ashihara no[n]Nakatsukuni. His[n]name comes from[n]"futsu," the fashion[n]in which things are[n]cut, and "nushi,"[n]his nature as a god.[n][e]

[msg myth_039]
[f 0 5 -258][f 2 1]A Slavic god whose[n]name means "three[n]heads." He rode a[n]holy black horse,[n]in contrast to[n]Sventovit, who rode[n]a white horse.[n][e]

[msg myth_040]
[f 0 5 -258][f 2 1]One of the four[n]major archangels,[n]his name means[n]"healer." He recites[n]the history of the[n]fallen angels and[n]the creation of[n]Adam and Eve.[n][e]

[msg myth_041]
[f 0 5 -258][f 2 1]Fairy queen and[n]wife to Oberon.[n]She is derived from [n]Diana in Roman myth[n]and is immortalized[n]in Shakespeare's[n]play, "A Midsummer[n]Night's Dream."[n][e]

[msg myth_042]
[f 0 5 -258][f 2 1]Fairy king and[n]husband to Titania.[n]Was cursed as a[n]child, and has not[n]grown any larger[n]since.[n][e]

[msg myth_043]
[f 0 5 -258][f 2 1]Blank[n][e]

[msg myth_044]
[f 0 5 -258][f 2 1]A fairy in German[n]folklore who carries[n]a bag of magical[n]sand, which puts[n]humans to sleep[n]when thrown into[n]their eyes. If the[n]victim resists, the[n]Sandman will sit[n]on their eyelids.[n][e]

[msg myth_045]
[f 0 5 -258][f 2 1]A beautiful fairy[n]of Irish lore that[n]yearns for a human[n]man's love. She[n]drains her lovers'[n]lives in return for[n]granting them[n]artistic inspiration.[n][e]

[msg myth_046]
[f 0 5 -258][f 2 1]In English myth,[n]they are fairies[n]of the forest that[n]love to play tricks[n]on people. They[n]can also be hard[n]workers when[n]necessary.[n][e]

[msg myth_047]
[f 0 5 -258][f 2 1]One of the four[n]major archangels.[n]His name means[n]"Flame of God,"[n]and he knows all[n]the celestial[n]phenomena. He is[n]the first angel[n]Satan met on[n]earth.[n][e]

[msg myth_048]
[f 0 5 -258][f 2 1]A fire giant in[n]Norse mythology.[n]He rules the fire[n]realm, Muspelheim,[n]and brandishes a[n]burning sword. At[n]Ragnarok, he will[n]set the world[n]ablaze.[n][e]

[msg myth_049]
[f 0 5 -258][f 2 1]The third of the[n]nine orders of[n]angels. It is said[n]that they carry[n]the throne of God.[n]They are angels of[n]knowledge.[n][e]

[msg myth_050]
[f 0 5 -258][f 2 1]The god of war in[n]Greek myth. Other[n]gods despised[n]him for his cruel[n]and violent nature.[n]Opposed Athena,[n]who represented[n]strategic warfare.[n][e]

[msg myth_051]
[f 0 5 -258][f 2 1]The children of[n]Gaia and Uranus in[n]Greek myth. They[n]ruled the land as[n]gods before the[n]Olympians[n]overthrew them.[n][e]

[msg myth_052]
[f 0 5 -258][f 2 1]BLANK[n][e]

[msg myth_053]
[f 0 5 -258][f 2 1]One of the four[n]aspects of the[n]human soul, as[n]described in[n]Shinto teachings.[n]It is associated[n]with aggression.[n][e]

[msg myth_054]
[f 0 5 -258][f 2 1]"Choosers of the[n]slain" in Norse[n]mythology. Armed[n]with shining armor[n]and spears, they[n]look for brave[n]warriors to take[n]to Valhalla, so[n]that they may[n]fight in Ragnarok.[n][e]

[msg myth_055]
[f 0 5 -258][f 2 1]An angel of[n]Gnosticism, said[n]to be born from[n]Sophia. In the[n]Bible, he is[n]mentioned as a[n]righteous king.[n][e]

[msg myth_056]
[f 0 5 -258][f 2 1]The fourth of the[n]nine orders of[n]angels. Their [n]duty is to oversee[n]the other angels.[n]It is said that[n]the success or[n]failure of nations[n]is decided by[n]these angels.[n][e]

[msg myth_057]
[f 0 5 -258][f 2 1]The German name of[n]the hero in the[n]epic poem of the[n]Nibelungenlied.[n]The dragon Fafnir's[n]blood made him[n]invincible, but a[n]single leaf on his[n]back resulted in a[n]weak spot.[n][e]

[msg myth_058]
[f 0 5 -258][f 2 1]The fifth of the[n]nine orders of[n]angels, also known[n]as "The Shining[n]Ones." They work [n]miracles and[n]support those[n]struggling with[n]their faith.[n][e]

[msg myth_059]
[f 0 5 -258][f 2 1]The sixth of the[n]nine orders of[n]angels. It is said[n]that they were the[n]first order to be[n]created. Their[n]duty is to protect[n]human souls from[n]demons.[n][e]

[msg myth_060]
[f 0 5 -258][f 2 1]Eighth of the nine [n]orders of angels.[n]Their duty is to[n]minister to humans[n]and deliver[n]messages. They are[n]at constant war[n]with the fallen[n]angels.[n][e]

[msg myth_061]
[f 0 5 -258][f 2 1]Ninth of the nine [n]orders of angels.[n]The "watchers" who[n]never sleep. Among[n]these are the[n]guardian angels[n]who are assigned[n]to every human at[n]birth.[n][e]

[msg myth_062]
[f 0 5 -258][f 2 1]Japanese god of[n]words, thought to[n]be the deification[n]of echoes. Said to[n]proclaim good and[n]bad in a single[n]word, and all[n]words uttered by[n]him come true.[n][e]

[msg myth_063]
[f 0 5 -258][f 2 1]A one-eyed, one-[n]legged monster said[n]to live deep in the[n]mountains of Kumano,[n]Japan. Believed to[n]be the degraded[n]blacksmith god,[n]Ame no Me-Hitotsu[n]no Kami.[n][e]

[msg myth_064]
[f 0 5 -258][f 2 1]The general of Hell,[n]he keeps watch over[n]other demons. One[n]of the greatest[n]necromancers in Hell,[n]he can control souls[n]and corpses.[n][e]

[msg myth_065]
[f 0 5 -258][f 2 1]One of the 72[n]demons of the[n]Goetia. He comes[n]in the shape of a[n]star and has vast[n]knowledge of herbs[n]and jewels. He can[n]also control birds[n]at will.[n][e]

[msg myth_066]
[f 0 5 -258][f 2 1]Demonic governor of[n]the deadly sin of[n]sloth, who also[n]excels at invention[n]and discovery. May[n]derive from Ba'al[n]Pe'or, Syrian god[n]of abundant crops.[n][e]

[msg myth_067]
[f 0 5 -258][f 2 1]A demoness in[n]Japanese mythology[n]that lives in Yomi,[n]the netherworld.[n]She is the first[n]demon Izanami[n]sends after Izanagi.[n][e]

[msg myth_068]
[f 0 5 -258][f 2 1]A type of Preta in[n]Hindu and Buddhist[n]myth. Classified as[n]"powerful ghosts,"[n]they have varying[n]shapes and forms.[n]They can control[n]the dead and eat[n]humans.[n][e]

[msg myth_069]
[f 0 5 -258][f 2 1]Goddesses of fate[n]in Norse myth. They[n]live below the[n]roots of Yggdrasil[n]and weave the[n]threads of fate,[n]which even the[n]gods are bound by.[n][e]

[msg myth_070]
[f 0 5 -258][f 2 1]One of the three[n]Moirae Sisters in[n]Greek mythology.[n]She cuts the life[n]threads of those[n]whose time has[n]come.[n][e]

[msg myth_071]
[f 0 5 -258][f 2 1]The Babylonian lord[n]of wind and scorching[n]sands. Has a lion's[n]head and arms, eagle-[n]clawed feet, bird[n]wings, and deadly[n]poison. The diseases[n]he spreads can only[n]be cured by magical[n]means.[n][e]

[msg myth_072]
[f 0 5 -258][f 2 1]One of the three[n]Moirae Sisters in[n]Greek mythology.[n]She is the[n]apportioner,[n]measuring the[n]thread which[n]determines each[n]person's lifespan.[n][e]

[msg myth_073]
[f 0 5 -258][f 2 1]One of the four[n]aspects of the[n]human soul, as[n]described in Shinto[n]teachings. It is[n]said to bring good[n]luck in hunting[n]and fishing.[n][e]

[msg myth_074]
[f 0 5 -258][f 2 1]One of the 72[n]demons of the[n]Goetia. He looks[n]like a knight and[n]has the power to[n]see things to come.[n]He also knows[n]much about wars.[n][e]

[msg myth_075]
[f 0 5 -258][f 2 1]One of the three[n]Moirae Sisters in[n]Greek mythology.[n]She spins the[n]threads of fate.[n][e]

[msg myth_076]
[f 0 5 -258][f 2 1]Roman goddess of[n]luck. Her Greek[n]counterpart is[n]Tyche. Originally[n]a goddess of [n]fertility, she[n]later became known[n]as the spinner of[n]the Wheel of[n]Fortune.[n][e]

[msg myth_077]
[f 0 5 -258][f 2 1]Norse thunder god,[n]and son of Odin.[n]He wears the belt[n]Megingjard, which [n]doubles his power.[n]Lightning flashes[n]whenever he throws[n]his hammer, Mjolnir.[n][e]

[msg myth_078]
[f 0 5 -258][f 2 1]An evil spirit of[n]Murngin mythology,[n]believed to be[n]reborn shadows.[n]They kidnap and eat[n]children, and[n]strike down[n]sorcerers who use[n]black magic.[n][e]

[msg myth_079]
[f 0 5 -258][f 2 1]The "destroyer"[n]and angel of the[n]bottomless pit, as[n]described in[n]ancient scriptures.[n]He controls locusts[n]and uses them to[n]cause massive[n]destruction to[n]villages.[n][e]

[msg myth_080]
[f 0 5 -258][f 2 1]One of the 72 demons[n]of the Goetia. It[n]led the cities of[n]Sodom and Gomorrah[n]to ruin, and[n]prosecuted Jesus.[n]Those who summon[n]Belial are granted[n]high social status.[n][e]

[msg myth_081]
[f 0 5 -258][f 2 1]A hero of Hindu[n]descent. He can[n]transform into[n]anything, fly and[n]has great strength.[n]He performed many[n]heroic deeds in the[n]Ramayana. He is[n]depicted as a[n]monkey.[n][e]

[msg myth_082]
[f 0 5 -258][f 2 1]A Japanese general[n]of the Genpei War[n]near the end of the[n]Heian era and start[n]of the Kamakura era.[n]His bold ingenuity[n]and ruthless skill[n]with a blade are[n]still praised in[n]Japan today.[n][e]

[msg myth_083]
[f 0 5 -258][f 2 1]Indian god who[n]repels evil, known[n]as Daikokuten in[n]Buddhism. Its swords[n]are fearsome, but[n]by paying tribute[n]to him, believers[n]may be blessed with[n]tremendous wealth[n]and happiness.[n][e]

[msg myth_084]
[f 0 5 -258][f 2 1]A god of Phrygian[n]descent. He was[n]Cybele's son and[n]consort, but[n]castrated himself[n]and died. Cybele[n]resurrected him as[n]a pine. He came to[n]represent rebirth.[n][e]

[msg myth_085]
[f 0 5 -258][f 2 1]A giant serpent of[n]Hindu mythology.[n]It is said the gods[n]and demons used him[n]to churn the sea of[n]milk. The strain[n]caused him to[n]exhale incredibly[n]potent venom, but[n]Shiva swallowed it.[n][e]

[msg myth_086]
[f 0 5 -258][f 2 1]The two-headed pet[n]dog belonging to[n]the giant Geryon,[n]in Greek myth. He[n]guarded a herd of[n]red oxen, and[n]fought Hercules.[n][e]

[msg myth_087]
[f 0 5 -258][f 2 1]A Scottish fairy[n]knight who protected[n]the glen called[n]Carterhaugh. He was[n]once human, but was[n]captured by the[n]Queen of the Fairies[n]and lived as one[n]of them thereafter.[n][e]

[msg myth_088]
[f 0 5 -258][f 2 1]A spirit of wind[n]and fire appearing[n]in Arabian lore.[n]It can transform[n]at will and grant[n]wishes to those[n]who release it[n]from its bottle[n]or jar.[n][e]

[msg myth_089]
[f 0 5 -258][f 2 1]A giant monster[n]in Hindu myth.[n]Its mouth is so[n]enormous that it[n]can swallow all of[n]space, along with[n]all gods. Its name[n]means "intoxicator."[n][e]

[msg myth_090]
[f 0 5 -258][f 2 1]One of the four[n]horsemen of the[n]Apocalypse in the[n]Book of Revelation,[n]he rides a white[n]horse with a bow[n]in hand. A crown[n]was granted to him,[n]and he promises[n]victory.[n][e]

[msg myth_091]
[f 0 5 -258][f 2 1]A ghost who appears[n]as a young blonde[n]girl. She seems[n]young, but has[n]formidable magic[n]powers. Some say[n]she's the ghost of[n]a poor English girl[n]who died an[n]unfortunate death.[n][e]

[msg myth_092]
[f 0 5 -258][f 2 1]The Egyptian god[n]of the desert,[n]chaos, and evil.[n]He murdered his[n]brother Osiris and[n]tried to become[n]chief god, but was[n]castrated by[n]Osiris's son,[n]Horus.[n][e]

[msg myth_093]
[f 0 5 -258][f 2 1]The Canaanite god[n]of death. Every[n]year he attempts[n]to kill Baal, the[n]god of fertility,[n]only to see him[n]raised from the[n]dead with the help[n]of Baal's sister,[n]Anat.[n][e]

[msg myth_094]
[f 0 5 -258][f 2 1]A mysterious angel[n]with the name[n]"poison of God."[n]He is often shown[n]as a serpent. [n]Opinions differ on[n]whether he is[n]fallen or not, but[n]either way, he is[n]linked with death.[n][e]

[msg myth_095]
[f 0 5 -258][f 2 1]The tigress mount[n]of the goddess[n]Durga, of Hindu[n]myth. Durga was born[n]to defeat the Asura[n]Mahisha, and Gdon[n]was granted to her[n]to help complete[n]the task.[n][e]

[msg myth_096]
[f 0 5 -258][f 2 1]A hideous female[n]monster with poison[n]fangs and snakes[n]instead of hair.[n]Her name is Greek[n]for "terrible."[n]After Perseus took[n]her head, he offered[n]it to the gods who[n]helped him slay her.[n][e]

[msg myth_097]
[f 0 5 -258][f 2 1]A spiritual attendant[n]to humans in Norse[n]myth. She is known[n]as both a goddess[n]of farming and war,[n]though some see her[n]as a low-ranking[n]servant of the[n]valkyries.[n][e]

[msg myth_098]
[f 0 5 -258][f 2 1]One of the four[n]major angels, he is[n]at the top of the[n]angel hierarchy.[n]Carries a long[n]sword that can cut[n]through anything.[n]His name means,[n]"Who is like God?"[n][e]

[msg myth_099]
[f 0 5 -258][f 2 1]One of the Ssu-[n]Ling, celestial[n]creatures in[n]Chinese myth. It[n]represents the[n]direction west,[n]the season of[n]autumn, and the[n]element of metal.[n][e]

[msg myth_100]
[f 0 5 -258][f 2 1]One of the Ssu-[n]Ling, celestial[n]creatures in[n]Chinese myth. It[n]represents the[n]direction south,[n]the season of[n]summer and the[n]element of fire.[n][e]

[msg myth_101]
[f 0 5 -258][f 2 1]One of the Ssu-[n]Ling, celestial[n]creatures in[n]Chinese myth. It[n]represents the[n]direction east,[n]the season of[n]spring, and the[n]element of wood.[n][e]

[msg myth_102]
[f 0 5 -258][f 2 1]One of the four[n]aspects of the[n]human soul, as[n]described in[n]Shinto teachings.[n]It is associated[n]with gentleness.[n][e]

[msg myth_103]
[f 0 5 -258][f 2 1]One of the Ssu-[n]Ling, celestial[n]creatures in[n]Chinese myth. It[n]represents the[n]direction north,[n]the season of[n]winter, and the[n]element of water.[n][e]

[msg myth_104]
[f 0 5 -258][f 2 1]Demonic Lord of the[n]Flies, whose insect[n]minions carry souls[n]for him to control.[n]Mentioned in the Bible[n]as a leader of evil[n]spirits, and thus[n]seen as a powerful[n]demon in Christianity.[n][e]

[msg myth_105]
[f 0 5 -258][f 2 1]The Fiend known as[n]the "Whore of[n]Babylon." Riding a[n]beast with seven[n]heads and ten[n]horns, she carries[n]a golden cup of[n]abominations, and[n]the filth of her[n]acts.[n][e]

[msg myth_106]
[f 0 5 -258][f 2 1]A powerful shikigami[n]that can be summoned[n]by certain onmyodo.[n]It can cause harm to[n]others or cure[n]illness, but its[n]ordinary temperament[n]is quite vicious.[n][e]

[msg myth_107]
[f 0 5 -258][f 2 1]Said to have been[n]Adam's first wife.[n]She refused to[n]obey him, leaving[n]Eden to become a[n]demon of the night.[n]All theories of[n]her fall depict[n]her as unfaithful.[n][e]

[msg myth_108]
[f 0 5 -258][f 2 1]A male demon of[n]European lore in[n]medieval times.[n]They visit sleeping[n]women and have[n]sexual intercourse[n]with them; the[n]resulting children[n]become witches[n]and wizards.[n][e]

[msg myth_109]
[f 0 5 -258][f 2 1]A female demon of[n]European lore in[n]medieval times.[n]They visit sleeping[n]men and have sexual[n]intercourse with[n]them; the victims[n]don't wake up, but[n]may dream of the[n]encounter.[n][e]

[msg myth_110]
[f 0 5 -258][f 2 1]Lilith's children.[n]Like their mother,[n]they have sex with[n]men at night.[n]Their legend[n]spread to Greece[n]where they are[n]known as the [n]"Empusa."[n][e]

[msg myth_111]
[f 0 5 -258][f 2 1]The legendary bird[n]of Chinese myth.[n]Said to appear only[n]in times of peace.[n]It is the ruler of[n]all birds; when it[n]dies, birds across[n]the land chirp with[n]sadness.[n][e]

[msg myth_112]
[f 0 5 -258][f 2 1]One of the triad[n]of main deities in[n]Hindu myth. He is[n]known as the[n]destroyer, but is[n]also related to[n]regeneration. His[n]wife is Parvati.[n][e]

[msg myth_113]
[f 0 5 -258][f 2 1]Taira no Masakado,[n]hero of the Heian[n]period. He claimed[n]the title "Shinno"[n](New Emperor) and[n]rebelled against[n]the government. He[n]was killed, but it[n]is said he became[n]a demigod.[n][e]

[msg myth_114]
[f 0 5 -258][f 2 1]Izanami sent them[n]after Izanagi at[n]Yomotsu Hirasaka,[n]the entrance of[n]Yomi, the Japanese[n]land of shadows.[n]The army of Ikusa[n]is led by Yomotsu[n]Shikome.[n][e]

[msg myth_115]
[f 0 5 -258][f 2 1]A giant snake with[n]eight heads that[n]fell at Susano-o's[n]hands. The sword that[n]came out was the[n]Ame-no-murakumo-[n]no-tsurugi, also[n]known as the Sword[n]of Kusanagi.[n][e]

[msg myth_116]
[f 0 5 -258][f 2 1]An evil deity of[n]Mesopotamian[n]folklore with[n]an eagle's body[n]and a lion's head.[n]While the god Enlil[n]purified himself,[n]Anzu stole the[n]Tablets of Destiny[n]from him.[n][e]

[msg myth_117]
[f 0 5 -258][f 2 1]A fallen angel in[n]Judeo-Christian[n]lore whose name[n]signifies "Morning[n]Star." Primarily[n]known for defying[n]God, but also[n]worshipped as a[n]bringer of light[n]to mankind.[n][e]

[msg myth_118]
[f 0 5 -258][f 2 1]Metatron's twin[n]brother in Judeo-[n]Christian lore. He[n]is the master of[n]heavenly songs.[n]It's said that a[n]human would take[n]500 years to walk[n]the length of his[n]body.[n][e]

[msg myth_119]
[f 0 5 -258][f 2 1]A Jack Frost that[n]wished for evil[n]powers. This[n]powerful demon is[n]born when a cute[n]Jack Frost[n]remembers its[n]nature as a demon.[n][e]

[msg myth_120]
[f 0 5 -258][f 2 1]A divine bird-man[n]in Hindu myth. He[n]once fought the[n]gods, and received[n]immortality in[n]exchange for[n]becoming Vishnu's[n]carrier.[n][e]

[msg myth_121]
[f 0 5 -258][f 2 1]One of the four oni[n]controlled by[n]Fujiwara no Chikata,[n]it can cause floods[n]at any time. In the[n]Taiheiki, Ki no[n]Tomoo succeeded in[n]expelling the oni[n]by reading a[n]Japanese poem.[n][e]

[msg myth_122]
[f 0 5 -258][f 2 1]The elephant-headed[n]god in Hindu myth.[n]He was originally[n]created by Parvati[n]to prevent anyone[n]from watching her[n]bathe. Shiva batted[n]his head off, but[n]replaced it with an[n]elephant's head.[n][e]

[msg myth_123]
[f 0 5 -258][f 2 1]Osiris's wife as[n]well as his younger[n]sister. Upon the[n]death of her husband,[n]she revived him with[n]her incredible magic[n]power. Isis is seen[n]at many gravesites[n]as the guardian[n]goddess of the dead.[n][e]

[msg myth_124]
[f 0 5 -258][f 2 1]The guardian hound[n]of Tartarus in Greek[n]myth. It is the[n]offspring of Typhon,[n]the giant of wind,[n]and Echidna, the[n]mother of monsters.[n]Orthrus is its[n]older brother.[n][e]

[msg myth_125]
[f 0 5 -258][f 2 1]One of the four oni[n]controlled by[n]Fujiwara no Chikata,[n]it sends hurricanes[n]to blow away its[n]enemies. Some say[n]that Fuu-ki is the[n]original ninja.[n][e]

[msg myth_126]
[f 0 5 -258][f 2 1]A brave young man[n]in Celtic myth.[n]After defeating a[n]vicious dog with[n]his bare hands, he[n]took up its role[n]as guardian, and[n]gave himself a name[n]meaning "Hound of[n]Culann."[n][e]

[msg myth_127]
[f 0 5 -258][f 2 1]A giant elephant [n]monster of Sri[n]Lankan myth. It is [n]typically portrayed[n]as being ridden by[n]the Evil One, Mara.[n]Whoever looks into[n]its evil eye is[n]said to be met[n]with misfortune.[n][e]

[msg myth_128]
[f 0 5 -258][f 2 1]A spirit of earth[n]from Japanese myth,[n]whose name means[n]"god of fields."[n]Though not innately[n]evil, its temper[n]may cause it to[n]attack humans from[n]behind a tree or[n]bushes.[n][e]

[msg myth_129]
[f 0 5 -258][f 2 1]The spirit who[n]said, "For we are[n]many," in ancient[n]scriptures. The[n]name comes from[n]the Roman military[n]term for an army[n]unit of 3,000 to[n]6,000 men.[n][e]

[msg myth_130]
[f 0 5 -258][f 2 1]One of the 72[n]demons of the[n]Goetia. He rides[n]a gigantic horse[n]and burns those[n]without manners.[n]He is the duke of[n]Hell.[n][e]

[msg myth_131]
[f 0 5 -258][f 2 1]The Roman god of[n]agriculture. He is[n]commonly identified[n]with Cronus. In an[n]attempt to prevent[n]his destiny, he ate[n]his children, but[n]was overthrown as[n]was fated.[n][e]

[msg myth_132]
[f 0 5 -258][f 2 1]One of the major[n]gods in Hindu myth,[n]he is the preserver[n]of the universe.[n]It is believed that[n]he will descend to[n]earth ten times to[n]maintain the[n]balance of power.[n][e]

[msg myth_133]
[f 0 5 -258][f 2 1]A mystical creature[n]in Balinese lore.[n]It represents good[n]and is Rangda's[n]eternal rival.[n]Even if defeated,[n]it will be reborn. [n]The result is a [n]never-ending[n]struggle.[n][e]

[msg myth_134]
[f 0 5 -258][f 2 1]One of the 72 demons[n]of the Goetia. He[n]appears wherever[n]there is battle to[n]stoke the hatred[n]within the soldiers.[n]He teaches those[n]who summon him how[n]to defeat their[n]enemies.[n][e]

[msg myth_135]
[f 0 5 -258][f 2 1]An ancient god of[n]Egypt whose eyes[n]are the sun and[n]moon. Revered by[n]some as the chief[n]god, and often[n]depicted as a hawk[n]or a falcon.[n][e]

[msg myth_136]
[f 0 5 -258][f 2 1]The 4th avatar of[n]Vishnu. He took[n]this form to defeat[n]Hiranyakashipu, who[n]can't be killed by[n]human, animal or[n]deva, and killed[n]his foe at dusk,[n]since he couldn't[n]die at other times.[n][e]

[msg myth_137]
[f 0 5 -258][f 2 1]A spirit formed of a[n]long-lived wildcat.[n]It disguises itself[n]as a beautiful woman[n]to take vitality[n]from men. Some say[n]other demon animals[n]collect vitality in[n]order to become[n]Senri themselves.[n][e]

[msg myth_138]
[f 0 5 -258][f 2 1]One of the four oni[n]controlled by[n]Fujiwara no Chikata,[n]its body is so hard[n]that no weapons[n]could penetrate it.[n][e]

[msg myth_139]
[f 0 5 -258][f 2 1]The king of Asuras[n]in Hindu myth. His[n]name is Maha[n]Vairocana (One Who[n]Shines On All). In[n]Buddhism, he is[n]known as Dainichi[n]Nyorai.[n][e]

[msg myth_140]
[f 0 5 -258][f 2 1]One of the most[n]important angels[n]in the hierarchy,[n]yet the most[n]mysterious. He is[n]the scribe and[n]advocate of Heaven.[n][e]

[msg myth_141]
[f 0 5 -258][f 2 1]The prince of[n]darkness in Judeo-[n]Christian lore,[n]known for his role[n]as the snake that [n]tempted Adam and[n]Eve at Eden. It is[n]also said he is[n]sent by God to[n]test man's piety.[n][e]

[msg myth_142]
[f 0 5 -258][f 2 1]One of the four[n]major angels. She[n]is also the only[n]female angel at[n]this rank. Her name[n]comes from the[n]Sumerian word for[n]"governor."[n][e]

[msg myth_143]
[f 0 5 -258][f 2 1]According to[n]Chinese myth,[n]Hokuto Seikun, or[n]"Wise Man of the[n]North Star,"[n]determines the[n]moment that one[n]is born.[n][e]

[msg myth_144]
[f 0 5 -258][f 2 1]Angels said to[n]sound the trumpets[n]at the apocalypse.[n]Each trumpet brings[n]more plagues and[n]disasters, turning[n]the earth into a[n]land of death and[n]suffering.[n][e]

[msg myth_145]
[f 0 5 -258][f 2 1]The jackal-headed[n]god of Egyptian[n]myth. He weighs[n]the hearts of the[n]dead to determine[n]their final[n]destination. He is[n]also associated[n]with embalming.[n][e]

[msg myth_146]
[f 0 5 -258][f 2 1]A deity of Chinese[n]mythology, also[n]known as Zhongtan[n]Yuanshuai. He[n]committed suicide[n]to atone for[n]killing a Dragon[n]King, but was[n]brought back to[n]life as a lotus.[n][e]

[msg myth_147]
[f 0 5 -258][f 2 1]One of the four oni[n]controlled by[n]Fujiwara no Chikata.[n]By eliminating its[n]aura and preventing[n]others from sensing[n]its presence, it was[n]able to surprise its[n]enemies.[n][e]

[msg myth_148]
[f 0 5 -258][f 2 1]The leader of a swarm[n]of pixies. Any pixie[n]in a leadership role,[n]or with remarkable[n]power, is called by[n]this name.[n][e]

[msg myth_149]
[f 0 5 -258][f 2 1]A female demon in[n]Hindu myth. Originally[n]a Dravidian fertility[n]goddess, the spread[n]of Hinduism changed[n]perception of her to[n]a demonic figure.[n]Usually depicted as[n]a voluptuous, nude[n]female.[n][e]

[msg myth_150]
[f 0 5 -258][f 2 1]A spirit from Chinese[n]legend, shaped like[n]a sheep, that can[n]see through any lie.[n]It occasionally[n]appears in the human[n]world to punish[n]evildoers with the[n]power stored in its[n]sharp horn.[n][e]

[msg myth_151]
[f 0 5 -258][f 2 1]Egyptian moon god[n]that takes the form[n]of a baboon. He is[n]the measurer of time,[n]and gave Isis the[n]power to resurrect[n]Osiris after he was[n]killed by the evil[n]god Seth.[n][e]

[msg myth_152]
[f 0 5 -258][f 2 1]A dog fairy in[n]Scottish folklore.[n]Its main duties are[n]to transport fairies[n]and be a watchdog.[n]It can transfix a[n]target it's chasing[n]by barking three[n]times.[n][e]

[msg myth_153]
[f 0 5 -258][f 2 1]A cryptid sighted in[n]West Virginia from the[n]60s to 80s. Named for[n]the finlike appendages[n]on the sides of his[n]body. Said to keenly[n]sense blood, so as to[n]track the source and[n]feed on it.[n][e]

[msg myth_154]
[f 0 5 -258][f 2 1]An evil monster of[n]Japanese lore known[n]for its hideous[n]appearance and brute[n]strength. They loot[n]and plunder villages,[n]massacring the[n]townspeople with[n]their iron clubs.[n][e]

[msg myth_155]
[f 0 5 -258][f 2 1]A divine wolf from[n]Japanese lore. It[n]had the power to[n]protect people from[n]fire or theft, but[n]they also feared it[n]because the Makami[n]would sometimes prey[n]upon them as well.[n][e]

[msg myth_156]
[f 0 5 -258][f 2 1]Demon of Hindu myth.[n]He is an enemy of the[n]gods, and attacks[n]humans to feed off[n]of them. His hideous[n]appearance strikes[n]fear into those who[n]see him. Can shift[n]his shape to deceive[n]his enemies.[n][e]

[msg myth_157]
[f 0 5 -258][f 2 1]A master sportsman[n]who entertains the[n]audience in exchange[n]for his own life:[n]one mistake can mean[n]his death. Some[n]believe that matadors[n]who die while[n]performing remain[n]in this world.[n][e]

[msg myth_158]
[f 0 5 -258][f 2 1]A motorcyclist whose[n]violent nature turned[n]him into a demon. His[n]anger at himself and[n]the world causes him[n]to lash out, so that[n]everyone else will[n]suffer as well.[n][e]

[msg myth_159]
[f 0 5 -258][f 2 1]One of the Si-xiong[n]from the west side[n]of China, it is[n]believed to carry[n]the blood of a great[n]emperor. Its stubborn[n]personality leads it[n]to fight until it[n]can no longer stand.[n][e]

[msg myth_160]
[f 0 5 -258][f 2 1]One of the Si-xiong[n]of ancient China.[n]It has a human face[n]on a sheep-like body,[n]and sharp fangs.[n]Its insatiable[n]hunger causes it[n]to eat until nothing[n]remains.[n][e]

[msg myth_161]
[f 0 5 -258][f 2 1]A guardian of the[n]gate to paradise.[n]This beast with a[n]human head and a[n]scorpion body[n]appears in[n]Mesopotamian lore.[n][e]

[msg myth_162]
[f 0 5 -258][f 2 1]An Eastern demon lord[n]who tempted Buddha[n]during his training.[n]He is a master of[n]fear, and his immense[n]power reaches to[n]every part of the[n]globe. His distant[n]offspring includes[n]Mare and Mora.[n][e]

[msg myth_163]
[f 0 5 -258][f 2 1]A Hindu god of war,[n]also known as Skanda[n]and Murugan. He rides[n]upon a peacock called[n]Paravani, with a bow[n]and arrow drawn. He[n]commands the army of[n]the gods, and defeated[n]the forces of Asura.[n][e]

[msg myth_164]
[f 0 5 -258][f 2 1]Demon whose name[n]means "Lord of the[n]High Place." Possibly[n]derived from the[n]Syrian deity Ba'al,[n]he presides over[n]death and the spirits[n]of the deceased.[n]Many worshipped him[n]because of this power.[n][e]

[msg myth_165]
[f 0 5 -258][f 2 1]A legendary bird of[n]Hindu mythology. Its[n]name means "one with[n]beautiful wings."[n]It can create wind at[n]will by flapping its[n]wings, and can also[n]change its size[n]freely.[n][e]

[msg myth_166]
[f 0 5 -258][f 2 1]A fallen angel, and[n]the lord of demons in[n]Judeo-Christian lore.[n]His pride led him to[n]revolt against God,[n]taking a third of the[n]heavenly host with[n]him. He now waits[n]for a second chance[n]to challenge God.[n][e]

[msg myth_167]
[f 0 5 -258][f 2 1]One of the 72 demons[n]of the Goetia. He[n]appears as a horse[n]and answers questions[n]of the past, present,[n]and future. He is[n]faithful to his conjurer.[n][e]

[msg myth_168]
[f 0 5 -258][f 2 1]Among the eight[n]Yashaou, and one[n]of Bishamonten's[n]attendants.[n]Originally a child-[n]eating demon, he[n]was converted by the[n]Buddha and became[n]a protector figure.[n][e]

[msg myth_169]
[f 0 5 -258][f 2 1]Also known as[n]Kishimojin. She[n]used to eat others'[n]children, but[n]Buddha changed her[n]ways. She eats[n]pomegranates now,[n]and is a goddess[n]of parenting.[n][e]

[msg myth_170]
[f 0 5 -258][f 2 1]A giantess called[n]the "snow-shoe[n]goddess," and the[n]embodiment of[n]winter. According[n]to legend, all the[n]gods will return[n]to her at the end[n]of Ragnarok.[n][e]

[msg myth_171]
[f 0 5 -258][f 2 1]A legendary white[n]horse with a single[n]spiral horn. It can[n]only be tamed by a[n]pure maiden. Its[n]horn supposedly has[n]miraculous healing[n]capabilities.[n][e]

[msg myth_172]
[f 0 5 -258][f 2 1]A deity of knowledge[n]in Japanese myth.[n]He conceived the[n]plan to draw[n]Amaterasu from the[n]Amato-Iwato, the[n]cave she was[n]hiding in.[n][e]

[msg myth_173]
[f 0 5 -258][f 2 1]A holy beast said to[n]protect houses from[n]evil, and grant them[n]fortune. It looks[n]similar to Shinto[n]guardian dogs, but is[n]actually modeled after[n]a lion. There are[n]many stories about it[n]in Ryukyu myth.[n][e]

[msg myth_174]
[f 0 5 -258][f 2 1]The seventh of the[n]nine orders of[n]angels. They guard[n]cities and nations,[n]and protect various[n]religions.[n][e]

[msg myth_175]
[f 0 5 -258][f 2 1]A member of the[n]Tengu race in[n]Japanese myth.[n]The most powerful[n]and popular of all[n]Tengu, they have[n]the power to fend[n]off evil spirits[n]and attract good[n]luck.[n][e]

[msg myth_176]
[f 0 5 -258][f 2 1]A snake with a[n]rainbow body from[n]Murngin lore. He is[n]a fertility deity[n]that controls the[n]weather, and resides[n]in a holy pond filled[n]with rainbow-colored[n]water.[n][e]

[msg myth_177]
[f 0 5 -258][f 2 1]A god in Assyrian[n]mythology. He is[n]associated with[n]the planet Saturn.[n]He is usually[n]grouped with [n]another god,[n]Sakkut.[n][e]

[msg myth_178]
[f 0 5 -258][f 2 1]The king of birds[n]in Hindu myth. In[n]the Ramayana, he[n]fought bravely,[n]but lost to Ravana[n]in an attempt to[n]save Sita, Rama's[n]wife, the 7th[n]avatar of Vishnu.[n][e]

[msg myth_179]
[f 0 5 -258][f 2 1]A primitive monster[n]with a viscous body.[n]There are various[n]theories as to its[n]origin, but it is[n]still under debate.[n]Said to compulsively[n]collect shiny objects.[n][e]

[msg myth_180]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_181]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_182]
[f 0 5 -258][f 2 1]A major deity in[n]Shinto myth. Clay[n]dolls were often[n]sculpted in its[n]image. Since it[n]was worshipped by[n]rebels, the dolls[n]came to be seen[n]as symbols of[n]defiance.[n][e]

[msg myth_183]
[f 0 5 -258][f 2 1]A tree spirit of[n]Chinese folklore who[n]dwells in trees used[n]for hangings. She is[n]smaller than a human,[n]and cannot speak,[n]but her voice is said[n]to be as clear as[n]a bird's song.[n][e]

[msg myth_184]
[f 0 5 -258][f 2 1]The Arabian mother[n]goddess, also known[n]as Allat. The Black[n]Stone at the Kaaba[n]was thought to be[n]her residence. She[n]and her son,[n]Dusura, were[n]worshipped there[n]by desert nomads.[n][e]

[msg myth_185]
[f 0 5 -258][f 2 1]Known as the gold[n]or yellow dragon,[n]it reigns over the[n]Ssu-Ling, celestial[n]creatures in[n]Chinese myth. It[n]is located in the[n]center of the four[n]beasts.[n][e]

[msg myth_186]
[f 0 5 -258][f 2 1]Cannibalistic demon[n]from Islamic lore.[n]It feeds on the flesh[n]of both the living[n]and the dead. It is[n]indistinguishable[n]from normal humans,[n]and prefers to prey[n]on children and[n]travellers.[n][e]

[msg myth_187]
[f 0 5 -258][f 2 1]The fairy queen in[n]Celtic myth. Often[n]identified with[n]Titania, Oberon's[n]wife. She would[n]offer mead mixed[n]with her blood to[n]her many consorts.[n][e]

[msg myth_188]
[f 0 5 -258][f 2 1]The personification[n]of the Ganges[n]river. Originally[n]from the heavens,[n]she came to earth[n]to clean the souls[n]of the people as a[n]result of the[n]prayers of[n]Bhagiratha.[n][e]

[msg myth_189]
[f 0 5 -258][f 2 1]The father of all in[n]Japanese myth, as[n]well as the ruler of[n]creation. When[n]forbidden to see his[n]wife Izanami, he[n]broke the promise,[n]resulting in the two[n]being separated from[n]each other forever.[n][e]

[msg myth_190]
[f 0 5 -258][f 2 1]An evil dragon that[n]gnaws on the roots[n]of Yggdrasil, the[n]World Tree. It rules[n]over the evil snakes[n]that live there.[n]Capable of surviving[n]Ragnarok by feeding[n]on the slain corpses[n]that drift to it.[n][e]

[msg myth_191]
[f 0 5 -258][f 2 1]A divine creature[n]in Japanese myth.[n]They are three-[n]legged birds sent by[n]Amaterasu to help[n]humans. It is said[n]that they helped[n]Emperor Jinmu[n]claim victory.[n][e]

[msg myth_192]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_193]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_194]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_195]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_196]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_197]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_198]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_199]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_200]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_201]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_202]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_203]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_204]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_205]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_206]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_207]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_208]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_209]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_210]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_211]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_212]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_213]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_214]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_215]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_216]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_217]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_218]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_219]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_220]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_221]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_222]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_223]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_224]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_225]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_226]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_227]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_228]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_229]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

[msg myth_230]
[f 0 5 -258][f 2 1]RESERVE230[n]Myth[n][e]

[msg myth_231]
[f 0 5 -258][f 2 1]RESERVE231[n]Myth[n][e]

[msg myth_232]
[f 0 5 -258][f 2 1]A divine being that[n]appeared from a[n]glowing bamboo shoot.[n]Though many men[n]proposed to her,[n]none could complete[n]her impossible tasks[n]and she returned to[n]her homeland, the[n]capital of the moon.[n][e]

[msg myth_233]
[f 0 5 -258][f 2 1]One of the four[n]horsemen of the[n]apocalypse. He[n]rides on a pale[n]horse, and is the[n]ruler of Hades.[n]Has the power to[n]destroy life.[n][e]

[msg myth_234]
[f 0 5 -258][f 2 1]According to[n]Japanese myth,[n]he fought Take-[n]Mikazuchi for[n]control of Japan[n]and lost. He is[n]revered as the god[n]of hunting.[n][e]

[msg myth_235]
[f 0 5 -258][f 2 1]A young man of[n]Greek myth. He[n]rejected the nymph[n]Echo, who faded to[n]a whisper out of[n]despair. Cursed by[n]Nemesis, he fell[n]in love with his[n]own reflection and[n]wasted away.[n][e]

[msg myth_236]
[f 0 5 -258][f 2 1]Demon of Buddhist[n]myth, said to drain[n]human life energy.[n]He has dark skin and[n]stands 3 meters tall,[n]but sometimes changes[n]shape to a gourd.[n]Known to have once[n]served Rudra, the[n]god of storms.[n][e]

[msg myth_237]
[f 0 5 -258][f 2 1]A demon that takes[n]the shape of a[n]giant bird in Sri[n]Lankan myth. It is[n]thought to be a[n]derivation of[n]Garuda.[n][e]

[msg myth_238]
[f 0 5 -258][f 2 1]A demon that governs[n]Black Masses. During[n]the Inquisition,[n]this name came up.[n]Later, he would[n]become an object[n]of worship for[n]witches.[n][e]

[msg myth_239]
[f 0 5 -258][f 2 1]A group of deities[n]worshipped in[n]voodoo. They[n]control the forces[n]of nature and[n]influence human[n]activities. Some[n]also have powerful[n]magic used to[n]curse others.[n][e]

[msg myth_240]
[f 0 5 -258][f 2 1]A cursed god of[n]the darkness in[n]Slavic myth. His[n]name means "Black[n]God." He is the[n]counterpart of the[n]"White God,"[n]Belobog.[n][e]

[msg myth_241]
[f 0 5 -258][f 2 1]An Aztec deity,[n]known as the[n]"Feathered[n]Serpent." He[n]created humans by[n]sprinkling blood[n]on the bones of[n]people from a[n]previously created[n]world.[n][e]

[msg myth_242]
[f 0 5 -258][f 2 1]The Japanese goddess[n]of entertainment.[n]She governs many[n]sacred dances.[n]Famous for her[n]dance used to lure[n]out Amaterasu, who[n]had barricaded[n]herself inside[n]a cave.[n][e]

[msg myth_243]
[f 0 5 -258][f 2 1]Sun Wu Kong was [n]supposedly born[n]from a rock. He[n]wreaked havoc[n]and was punished[n]by Buddha, but[n]was eventually[n]saved by a monk[n]named Santsang.[n][e]

[msg myth_244]
[f 0 5 -258][f 2 1]The son and second[n]consort to the[n]female dragon[n]Tiamat. He was to[n]be the leader of[n]the gods, but was[n]killed by Marduk.[n]Mankind was created[n]from his blood.[n][e]

[msg myth_245]
[f 0 5 -258][f 2 1]A fertility goddess[n]in Japanese lore.[n]The youngest of[n]eight daughters of[n]Ashinazuchi, all[n]her sisters were[n]sacrificed to[n]Yamatano-Orochi.[n]Soon after, Susano-O[n]rescued her.[n][e]

[msg myth_246]
[f 0 5 -258][f 2 1]Shiva's first[n]consort in Hindu[n]myth, she threw[n]herself into a[n]sacrificial fire[n]in protest of her[n]father's treatment[n]of Shiva. Reborn as[n]Parvati, she was[n]reunited with Shiva.[n][e]

[msg myth_247]
[f 0 5 -258][f 2 1]The king of the[n]Naga, a half-man,[n]half-snake tribe[n]in Hindu myth. The[n]dragon kings Nanda[n]and Takshaka of[n]Buddhist myth fall[n]into this royal[n]category.[n][e]

[msg myth_248]
[f 0 5 -258][f 2 1]In Hindu mythology,[n]the goddess of[n]beauty and good[n]fortune. Vishnu's[n]wife and Kama's[n]mother, she is the[n]goddess of love.[n]Believed to be[n]born from an ocean[n]of milk.[n][e]

[msg myth_249]
[f 0 5 -258][f 2 1]Izanagi's rival who[n]looks just like him.[n]Magatsu means[n]"calamity." Unlike[n]Izanagi, who founded[n]the land and brought[n]order, he leads all[n]back into chaos.[n][e]

[msg myth_250]
[f 0 5 -258][f 2 1]RESERVE[n]Myth[n][e]

