[msg skill_000]
[s]Deals miniscule Phys[n]damage to 1 foe.[n][e]

[msg skill_001]
[s]Deals light Fire[n]damage to 1 foe.[n][e]

[msg skill_002]
[s]Deals medium Fire[n]damage to 1 foe.[n][e]

[msg skill_003]
[s]Deals heavy Fire[n]damage to 1 foe.[n][e]

[msg skill_004]
[s]Deals light Fire[n]damage to all foes.[n][e]

[msg skill_005]
[s]Deals medium Fire[n]damage to all foes.[n][e]

[msg skill_006]
[s]Deals heavy Fire[n]damage to all foes.[n][e]

[msg skill_007]
[s]Deals heavy Fire[n]damage to all foes.[n][e]

[msg skill_008]
[s]Deals severe Fire[n]damage to 1 foe.[n][e]

[msg skill_009]
[s]Deals heavy Fire[n]damage to all foes.[n][e]

[msg skill_00A]
[s]Recovers 20SP[n]for one ally.[n][e]

[msg skill_00B]
[s]Allows one ally to reflect[n]one physical attack.[n][e]

[msg skill_00C]
[s]Deals light Almighty[n]damage to all foes 1x[n]to 3x.[n][e]

[msg skill_00D]
[s]Deals severe Almighty[n]damage to all foes.[n][e]

[msg skill_00E]
[s]Deals light Wind[n]damage to 1 foe.[n][e]

[msg skill_00F]
[s]Deals medium Wind[n]damage to 1 foe.[n][e]

[msg skill_010]
[s]Deals heavy Wind[n]damage to 1 foe.[n][e]

[msg skill_011]
[s]Deals light Wind[n]damage to all foes.[n][e]

[msg skill_012]
[s]Deals medium Wind[n]damage to all foes.[n][e]

[msg skill_013]
[s]Deals heavy Wind[n]damage to all foes.[n][e]

[msg skill_014]
[s]Deals heavy Wind[n]damage to all foes.[n][e]

[msg skill_015]
[s]Deals severe Wind[n]damage to 1 foe.[n][e]

[msg skill_016]
[s]Heals one ally's ailments[n]other than Down/KO.[n][e]

[msg skill_017]
[s]Nullifies stat penalties on[n]party. Medium chance[n]of Silence (all foes).[n][e]

[msg skill_018]
[s]Deals severe Almighty[n]damage and inflicts[n]Knockdown (var. foes).[n][e]

[msg skill_019]
[s]Depletes 50SP from[n]all foes.[n][e]

[msg skill_01A]
[s]Deals light Ice[n]damage to 1 foe.[n][e]

[msg skill_01B]
[s]Deals medium Ice[n]damage to 1 foe.[n][e]

[msg skill_01C]
[s]Deals heavy Ice[n]damage to 1 foe.[n][e]

[msg skill_01D]
[s]Deals light Ice[n]damage to all foes.[n][e]

[msg skill_01E]
[s]Deals medium Ice[n]damage to all foes.[n][e]

[msg skill_01F]
[s]Deals heavy Ice[n]damage to all foes.[n][e]

[msg skill_020]
[s]Deals heavy Ice[n]damage to all foes.[n][e]

[msg skill_021]
[s]Deals severe Ice[n]damage to 1 foe.[n][e]

[msg skill_022]
[s]Deals heavy Ice[n]damage to all foes.[n][e]

[msg skill_023]
[s]Gives one ally Fire[n]resistance for 3 turns.[n][e]

[msg skill_024]
[s]Nullifies all attacks[n](if used by foe).[n][e]

[msg skill_025]
[s]Deals severe Almighty[n]damage and inflicts[n]Knockdown (2 foes).[n][e]

[msg skill_026]
[s]Repels all attacks[n](if used by foe).[n][e]

[msg skill_027]
[s]Deals light Elec[n]damage to 1 foe.[n][e]

[msg skill_028]
[s]Deals medium Elec[n]damage to 1 foe.[n][e]

[msg skill_029]
[s]Deals heavy Elec[n]damage to 1 foe.[n][e]

[msg skill_02A]
[s]Deals light Elec[n]damage to all foes.[n][e]

[msg skill_02B]
[s]Deals medium Elec[n]damage to all foes.[n][e]

[msg skill_02C]
[s]Deals heavy Elec[n]damage to all foes.[n][e]

[msg skill_02D]
[s]Deals heavy Elec[n]damage to all foes.[n][e]

[msg skill_02E]
[s]Deals severe Elec[n]damage to 1 foe.[n][e]

[msg skill_02F]
[s]Fully restores one ally's[n]HP and SP.[n][e]

[msg skill_030]
[s]Recovers 60SP[n]for one ally.[n][e]

[msg skill_031]
[s]Recovers 90SP[n]for one ally.[n][e]

[msg skill_032]
[s]Allows one ally to reflect[n]one magical attack.[n][e]

[msg skill_033]
[s]Deals medium Almighty[n]damage to all foes.[n][e]

[msg skill_034]
[s]Deals heavy Almighty[n]damage to all foes.[n][e]

[msg skill_035]
[s]Deals severe Almighty[n]damage to all foes.[n][e]

[msg skill_036]
[s]Deals medium Almighty[n]damage to everyone,[n][e]

[msg skill_037]
[s]Deals severe Almighty[n]damage to 1 foe.[n][e]

[msg skill_038]
[s]Deals severe Almighty[n]damage to all foes.[n][e]

[msg skill_039]
[s]Gives one ally Ice[n]resistance for 3 turns.[n][e]

[msg skill_03A]
[s]Gives one ally Elec[n]resistance for 3 turns.[n][e]

[msg skill_03B]
[s]Gives one ally Wind[n]resistance for 3 turns.[n][e]

[msg skill_03C]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_03D]
[s]Deals light Light[n]damage to 1 foe.[n][e]

[msg skill_03E]
[s]Deals heavy Light[n]damage to 1 foe.[n][e]

[msg skill_03F]
[s]Deals light Light[n]damage to all foes.[n][e]

[msg skill_040]
[s]Deals heavy Light[n]damage to all foes.[n][e]

[msg skill_041]
[s]Light: medium chance of[n]reducing foes to 1/2 HP.[n]Chance of insta-kill.[n][e]

[msg skill_042]
[s]Light: medium chance[n]of reducing 1 foe to[n]1/2 current HP.[n][e]

[msg skill_043]
[s]Light: high chance of[n]instant kill to all foes.[n][e]

[msg skill_044]
[s]Nullifies one enemy's[n]Fire resistance.[n][e]

[msg skill_045]
[s]Nullifies one enemy's[n]Ice resistance.[n][e]

[msg skill_046]
[s]Nullifies one enemy's[n]Wind resistance.[n][e]

[msg skill_047]
[s]Nullifies one enemy's[n]Elec resistance.[n][e]

[msg skill_048]
[s]Deals light Darkness[n]damage to 1 foe.[n][e]

[msg skill_049]
[s]Deals heavy Darkness[n]damage to 1 foe.[n][e]

[msg skill_04A]
[s]Deals light Darkness[n]damage to all foes.[n][e]

[msg skill_04B]
[s]Deals heavy Darkness[n]damage to all foes.[n][e]

[msg skill_04C]
[s]Darkness: med chance of[n]reducing foes to 1/2 HP.[n]Chance of insta-kill.[n][e]

[msg skill_04D]
[s]Darkness: high chance[n]of reducing 1 foe to[n]1/2 current HP.[n][e]

[msg skill_04E]
[s]Darkness: high chance of[n]instant kill to all foes.[n][e]

[msg skill_04F]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_050]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_051]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_052]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_053]
[s]High chance of making[n]1 foe Panic.[n][e]

[msg skill_054]
[s]Medium chance of[n]making all foes Panic.[n][e]

[msg skill_055]
[s]High chance of instilling[n]Fear in 1 foe.[n][e]

[msg skill_056]
[s]Medium chance of[n]instilling Fear in all foes.[n][e]

[msg skill_057]
[s]Instantly kills foes[n]instilled with Fear.[n][e]

[msg skill_058]
[s]High chance of[n]Enraging 1 foe.[n][e]

[msg skill_059]
[s]Medium chance of[n]Enraging all foes.[n][e]

[msg skill_05A]
[s]High chance of[n]Poisoning 1 foe.[n][e]

[msg skill_05B]
[s]Medium chance of[n]Poisoning all foes.[n][e]

[msg skill_05C]
[s]High chance of[n]Exhausting 1 foe.[n][e]

[msg skill_05D]
[s]Medium chance of[n]Exhausting all foes.[n][e]

[msg skill_05E]
[s]High chance of[n]Enervating 1 foe.[n][e]

[msg skill_05F]
[s]Medium chance of[n]Enervating all foes.[n][e]

[msg skill_060]
[s]Enervates 1 foe and[n]reduces their HP to 1.[n][e]

[msg skill_061]
[s]High chance of[n]Silencing 1 foe.[n][e]

[msg skill_062]
[s]Medium chance of[n]Silencing all foes.[n][e]

[msg skill_063]
[s]Increases chance of[n]inflicting ailments to[n]1 foe (3 turns).[n][e]

[msg skill_064]
[s]Increases chance of[n]inflicting ailments to[n]all combatants (3 turns).[n][e]

[msg skill_065]
[s]Drains 30HP[n]from 1 foe.[n][e]

[msg skill_066]
[s]Drains 30SP[n]from 1 foe.[n][e]

[msg skill_067]
[s]Drains 150HP[n]from 1 foe.[n][e]

[msg skill_068]
[s]Drains 100SP[n]from 1 foe.[n][e]

[msg skill_069]
[s]Reduces to 1 the[n]HP of all foes that are[n]weak to Light/Darkness.[n][e]

[msg skill_06A]
[s]Enrages 1 target.[n]Guaranteed.[n][e]

[msg skill_06B]
[s]Deals severe Almighty[n]damage to all combatants.[n][e]

[msg skill_06C]
[s]Deals colossal Almighty[n]damage to all combatants.[n][e]

[msg skill_06D]
[s]Fully restores[n]party's HP and SP.[n][e]

[msg skill_06E]
[s]Inflicts Knockdown[n]on all foes.[n][e]

[msg skill_06F]
[s]Inflicts random status[n]ailments on all foes.[n][e]

[msg skill_070]
[s]Fully restores the HP[n]and SP of all[n]combatants.[n][e]

[msg skill_071]
[s]Inflicts Knockdown on[n]all combatants.[n][e]

[msg skill_072]
[s]Inflicts random status[n]ailments on all[n]combatants.[n][e]

[msg skill_073]
[s]Fully restores the HP[n]and SP of all foes.[n][e]

[msg skill_074]
[s]Inflicts Knockdown[n]on party.[n][e]

[msg skill_075]
[s]No effect.[n][e]

[msg skill_076]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_077]
[s]Nullifies 1 foe's[n]elemental resistances.[n][e]

[msg skill_078]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_079]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_07A]
[s]Deals medium Phys[n]damage to 1 foe.[n][e]

[msg skill_07B]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_07C]
[s]Deals light Phys[n]damage to 1 foe 2x.[n][e]

[msg skill_07D]
[s]Deals light Phys[n]damage to 1 foe 1x[n]to 3x.[n][e]

[msg skill_07E]
[s]Deals light Phys[n]damage to all foes 1x[n]to 2x.[n][e]

[msg skill_07F]
[s]Deals light Phys[n]damage to 1 foe 2x.[n][e]

[msg skill_080]
[s]Deals heavy Phys[n]damage to 1 foe.[n][e]

[msg skill_081]
[s]Deals heavy Phys[n]damage to 1 foe with[n]a high chance of Critical.[n][e]

[msg skill_082]
[s]Deals light Phys[n]damage to 1 foe 2x[n]to 4x.[n][e]

[msg skill_083]
[s]Deals heavy Phys[n]damage to all foes.[n][e]

[msg skill_084]
[s]Deals severe Phys[n]damage to 1 foe.[n][e]

[msg skill_085]
[s]Deals light Phys[n]damage to all foes[n]2x to 4x.[n][e]

[msg skill_086]
[s]Deals heavy Phys[n]damage to all foes.[n][e]

[msg skill_087]
[s]Deals medium Phys[n]damage to all foes 2x.[n][e]

[msg skill_088]
[s]Deals heavy Phys[n]damage to all foes 1x[n]to 2x.[n][e]

[msg skill_089]
[s]Deals medium Phys[n]damage to 1 foe 1x[n]to 2x.[n][e]

[msg skill_08A]
[s]Deals severe Phys[n]damage to 1 foe with[n]a high chance of Critical.[n][e]

[msg skill_08B]
[s]Deals light Phys[n]damage to all foes 1x[n]to 3x.[n][e]

[msg skill_08C]
[s]Deals colossal Phys[n]damage to 1 foe.[n][e]

[msg skill_08D]
[s]Deals colossal Phys dmg[n]to all foes with a medium[n]chance of instant kill.[n][e]

[msg skill_08E]
[s]Deals colossal Phys[n]damage to 1 foe.[n][e]

[msg skill_08F]
[s]Deals severe Phys[n]damage to all foes.[n][e]

[msg skill_090]
[s]Deals medium Phys[n]damage to 1 foe.[n][e]

[msg skill_091]
[s]Deals medium Phys[n]damage to all foes.[n][e]

[msg skill_092]
[s]Deals colossal Phys[n]damage to 1 foe.[n][e]

[msg skill_093]
[s]Deals medium Phys[n]damage to all foes.[n][e]

[msg skill_094]
[s]Deals heavy Phys[n]damage to all foes.[n][e]

[msg skill_095]
[s]Deals medium Phys[n]damage to 1 foe.[n][e]

[msg skill_096]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_097]
[s]Deals light Phys[n]damage to 1 foe with a[n]low chance of Poison.[n][e]

[msg skill_098]
[s]Deals heavy Phys[n]damage to 1 foe with a[n]medium chance of Poison.[n][e]

[msg skill_099]
[s]Deals heavy Phys[n]damage to all foes with a[n]low chance of Poison.[n][e]

[msg skill_09A]
[s]Deals medium Phys[n]damage to all foes with a[n]medium chance of Poison.[n][e]

[msg skill_09B]
[s]Deals light Phys[n]damage to 1 foe with a[n]low chance of Panic.[n][e]

[msg skill_09C]
[s]Deals medium Phys[n]damage to all foes with a[n]low chance of Panic.[n][e]

[msg skill_09D]
[s]Deals light Phys[n]damage to 1 foe 2x with[n]a low chance of Rage.[n][e]

[msg skill_09E]
[s]Deals medium Phys[n]damage to all foes with a[n]low chance of Rage.[n][e]

[msg skill_09F]
[s]Deals light Phys[n]damage to 1 foe with a[n]low chance of Silence.[n][e]

[msg skill_0A0]
[s]Deals medium Phys[n]damage to all foes with a[n]low chance of Silence.[n][e]

[msg skill_0A1]
[s]Deals light Phys[n]damage to 1 foe 2x with[n]a low chance of Fear.[n][e]

[msg skill_0A2]
[s]Deals light Phys damage[n]to all foes 1x to 2x with[n]a low chance of Fear.[n][e]

[msg skill_0A3]
[s]Deals medium Phys[n]damage to 1 foe with a[n]low chance of Enervation.[n][e]

[msg skill_0A4]
[s]Deals medium Phys[n]damage to all foes with a[n]low chance of Enervation.[n][e]

[msg skill_0A5]
[s]Deals light Phys damage[n]to 1 foe 1x to 3x with a[n]low chance of Exhaustion.[n][e]

[msg skill_0A6]
[s]Deals medium Phys[n]damage to all foes with a[n]low chance of Exhaustion.[n][e]

[msg skill_0A7]
[s]Deals heavy Phys[n]damage to 1 foe with a[n]low chance of Fear.[n][e]

[msg skill_0A8]
[s]Deals heavy Phys[n]damage to 1 foe with a[n]high chance of Critical.[n][e]

[msg skill_0A9]
[s]Deals severe Phys[n]damage to 1 foe with a[n]high chance of Critical.[n][e]

[msg skill_0AA]
[s]Deals light Phys[n]damage to all foes 8x.[n][e]

[msg skill_0AB]
[s]Deals light Phys[n]damage to all foes[n]1x to 3x.[n][e]

[msg skill_0AC]
[s]Deals medium Phys[n]damage to all foes[n]1x to 3x.[n][e]

[msg skill_0AD]
[s]Deals medium Phys[n]damage to all foes[n]1x to 3x.[n][e]

[msg skill_0AE]
[s]Med Phys dmg, 1 foe.[n]Bonus damage to foes[n]that are Down.[n][e]

[msg skill_0AF]
[s]Severe Phys dmg, 1 foe.[n]Bonus damage to foes[n]that are Down.[n][e]

[msg skill_0B0]
[s]Deals severe Phys[n]damage to all foes[n]1x to 3x.[n][e]

[msg skill_0B1]
[s]Increases party's[n]Attack for 3 turns.[n][e]

[msg skill_0B2]
[s]Increases party's[n]Defense for 3 turns.[n][e]

[msg skill_0B3]
[s]Increases party's[n]Hit/Evasion rate[n]for 3 turns.[n][e]

[msg skill_0B4]
[s]More than doubles[n]dmg of party's next[n]phys/magic attacks.[n][e]

[msg skill_0B5]
[s]Restores 30% of[n]max HP to party.[n][e]

[msg skill_0B6]
[s]Restores 10% of[n]max SP to party.[n][e]

[msg skill_0B7]
[s]Restores 30% of[n]max HP to party.[n]Cures ailments.[n][e]

[msg skill_0B8]
[s]Restores 30% of[n]max HP to party.[n]Cures undefined ailment.[n][e]

[msg skill_0B9]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_0BA]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_0BB]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_0BC]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_0BD]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_0BE]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_0BF]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_0C0]
[s]Slightly restores[n]1 ally's HP.[n][e]

[msg skill_0C1]
[s]Moderately restores[n]1 ally's HP.[n][e]

[msg skill_0C2]
[s]Fully restores 1[n]ally's HP.[n][e]

[msg skill_0C3]
[s]Slightly restores[n]party's HP.[n][e]

[msg skill_0C4]
[s]Moderately restores[n]party's HP.[n][e]

[msg skill_0C5]
[s]Fully restores[n]party's HP.[n][e]

[msg skill_0C6]
[s]Fully restores party's[n]HP. Cures ailments.[n][e]

[msg skill_0C7]
[s]Dispels Panic, Fear[n]and Rage (1 ally).[n][e]

[msg skill_0C8]
[s]Dispels Panic, Fear[n]and Rage (party).[n][e]

[msg skill_0C9]
[s]Recovers 1 ally from[n]Knockdown or Dizzy[n]status.[n][e]

[msg skill_0CA]
[s]Neutralizes Poison[n](1 ally).[n][e]

[msg skill_0CB]
[s]Cures Silence[n](1 ally).[n][e]

[msg skill_0CC]
[s]Cures Rage[n](1 ally).[n][e]

[msg skill_0CD]
[s]Cures Enervation[n](1 ally).[n][e]

[msg skill_0CE]
[s]Cures Enervation/[n]Exhaustion (1 ally).[n][e]

[msg skill_0CF]
[s]Cures Enervation/[n]Exhaustion (party).[n][e]

[msg skill_0D0]
[s]Cures all ailments[n]except Down and KO[n](party).[n][e]

[msg skill_0D1]
[s]Revives an ally with[n]50% HP.[n][e]

[msg skill_0D2]
[s]Revives an ally with[n]full HP.[n][e]

[msg skill_0D3]
[s]Decreases 1 foe's Attack[n]for 3 turns.[n][e]

[msg skill_0D4]
[s]Decreases all foes'[n]Attack for 3 turns.[n][e]

[msg skill_0D5]
[s]Decreases 1 foe's[n]Hit/Evasion rate for[n]3 turns.[n][e]

[msg skill_0D6]
[s]Decreases all foes'[n]Hit/Evasion rate for[n]3 turns.[n][e]

[msg skill_0D7]
[s]Decreases 1 foe's[n]Defense for 3 turns.[n][e]

[msg skill_0D8]
[s]Decreases all foes'[n]Defense for 3 turns.[n][e]

[msg skill_0D9]
[s]Nullifies stat[n]penalties on party.[n][e]

[msg skill_0DA]
[s]Increases 1 ally's[n]Attack for 3 turns.[n][e]

[msg skill_0DB]
[s]Increases party's[n]Attack for 3 turns.[n][e]

[msg skill_0DC]
[s]Increases 1 ally's[n]Hit/Evasion rate for[n]3 turns.[n][e]

[msg skill_0DD]
[s]Increases party's[n]Hit/Evasion rate for[n]3 turns.[n][e]

[msg skill_0DE]
[s]Increases 1 ally's[n]Defense for 3 turns.[n][e]

[msg skill_0DF]
[s]Increases party's[n]Defense for 3 turns.[n][e]

[msg skill_0E0]
[s]Nullifies stat[n]bonuses on all foes.[n][e]

[msg skill_0E1]
[s]Increases 1 ally's[n]Attack, Defense and[n]Hit/Evasion rate (3 turns).[n][e]

[msg skill_0E2]
[s]Decreases 1 foe's[n]Attack, Defense and[n]Hit/Evasion rate (3 turns).[n][e]

[msg skill_0E3]
[s]More than doubles[n]damage of next[n]physical attack.[n][e]

[msg skill_0E4]
[s]More than doubles[n]damage of next[n]magic attack.[n][e]

[msg skill_0E5]
[s]Barrier that reflects[n]phys dmg once.[n][e]

[msg skill_0E6]
[s]Barrier that reflects[n]magic dmg once.[n][e]

[msg skill_0E7]
[s]Negates all foes'[n]Tetrakarn.[n][e]

[msg skill_0E8]
[s]Negates all foes'[n]Makarakarn.[n][e]

[msg skill_0E9]
[s]Nullifies instant kill[n]attack once (1 ally).[n][e]

[msg skill_0EA]
[s]Increases 1 ally's[n]chance of Critical[n]for 3 turns.[n][e]

[msg skill_0EB]
[s]Increases all combatants'[n]chance of Critical[n](3 turns).[n][e]

[msg skill_0EC]
[s]Nullifies 1 foe's Fire[n]resistance. Cannot[n]negate Red Wall.[n][e]

[msg skill_0ED]
[s]Nullifies 1 foe's Ice[n]resistance. Cannot[n]negate White Wall.[n][e]

[msg skill_0EE]
[s]Nullifies 1 foe's Wind[n]resistance. Cannot[n]negate Green Wall.[n][e]

[msg skill_0EF]
[s]Nullifies 1 foe's Elec[n]resistance. Cannot[n]negate Blue Wall.[n][e]

[msg skill_0F0]
[s]Adds Fire resistance to[n]1 ally for 3 turns.[n][e]

[msg skill_0F1]
[s]Adds Ice resistance to[n]1 ally for 3 turns.[n][e]

[msg skill_0F2]
[s]Adds Elec resistance to[n]1 ally for 3 turns.[n][e]

[msg skill_0F3]
[s]Adds Wind resistance to[n]1 ally for 3 turns.[n][e]

[msg skill_0F4]
[s]Enables escape from[n]most battles.[n][e]

[msg skill_0F5]
[s]Recovers all allies' HP,[n]but caster's HP falls to 1.[n][e]

[msg skill_0F6]
[s]Instantly escape from[n]a dungeon.[n][e]

[msg skill_0F7]
[s]Moderately restores party's[n]HP and raises Hit/Evasion[n]rate for 3 turns.[n][e]

[msg skill_0F8]
[s]Increases party's Attack,[n]Defense and Hit/Evasion[n]rate for 3 turns.[n][e]

[msg skill_0F9]
[s]Deals severe Fire[n]damage to all foes.[n][e]

[msg skill_0FA]
[s]May inflict Down/Dizzy[n]on all foes.[n][e]

[msg skill_0FB]
[s]Anything could happen...[n][e]

[msg skill_0FC]
[s]Shields the party from[n]all damage once.[n][e]

[msg skill_0FD]
[s]View 1 foe's skills[n]and affinities, including[n]those you have not tried.[n][e]

[msg skill_0FE]
[s]Online SOS function.[n][e]

[msg skill_0FF]
[s]Enervation function[n](forget).[n][e]

[msg skill_100]
[s]Deals Almighty damage to[n]all foes. Dmg influenced[n]by current party members.[n][e]

[msg skill_101]
[s]Deals Almighty damage to[n]all foes. Dmg influenced[n]by current party members.[n][e]

[msg skill_102]
[s]Deals Almighty damage to[n]all foes. Dmg influenced[n]by current party members.[n][e]

[msg skill_103]
[s]Panic function[n](lose money).[n][e]

[msg skill_104]
[s]Deals miniscule Phys[n]damage to 1 foe 2x to[n]3x. Guaranteed Critical.[n][e]

[msg skill_105]
[s]Deals ultimate Phys[n]damage to 1 foe.[n][e]

[msg skill_106]
[s]Deals miniscule Phys[n]damage to 1 foe.[n]Guaranteed Critical.[n][e]

[msg skill_107]
[s]Deals miniscule Phys[n]damage to all foes.[n]Guaranteed Critical.[n][e]

[msg skill_108]
[s]Deals miniscule Phys[n]damage to 1 foe 3x to[n]4x. Guaranteed Critical.[n][e]

[msg skill_109]
[s]Deals miniscule Phys[n]damage to all foes.[n]Guaranteed Critical.[n][e]

[msg skill_10A]
[s]Deals miniscule Phys[n]damage to 1 foe.[n]Guaranteed Critical.[n][e]

[msg skill_10B]
[s]Reveals enemy skills and[n]affinities you've tried[n]when using Analyze.[n][e]

[msg skill_10C]
[s]Shows whether an attack[n]will be effective when[n]choosing a target.[n][e]

[msg skill_10D]
[s]Displays one foe's[n]weakness at the start[n]of battle.[n][e]

[msg skill_10E]
[s]Recovers 5% HP at the[n]end of battle.[n][e]

[msg skill_10F]
[s]Recovers 5% SP at the[n]end of battle.[n][e]

[msg skill_110]
[s]Allows you to analyze[n]foes to find weaknesses.[n][e]

[msg skill_111]
[s]Summons one unit[n](when used by a foe).[n][e]

[msg skill_112]
[s]Displays foes in a wide[n]area of the map, even in[n]unexplored areas.[n][e]

[msg skill_113]
[s]Displays all treasures[n]on the dungeon map.[n][e]

[msg skill_114]
[s]Allows you to escape[n]from almost all battles.[n][e]

[msg skill_115]
[s]The word of power that[n]banishes all the world's[n]curses and falsehoods.[n][e]

[msg skill_116]
[s]Deals miniscule Phys[n]damage to 1 foe 2x to[n]3x. Guaranteed Critical.[n][e]

[msg skill_117]
[s]Deals ultimate Phys[n]damage to 1 foe.[n][e]

[msg skill_118]
[s]Deals miniscule Phys[n]damage to 1 foe.[n]Guaranteed Critical.[n][e]

[msg skill_119]
[s]Deals miniscule Phys[n]damage to all foes.[n]Guaranteed Critical.[n][e]

[msg skill_11A]
[s]Deals miniscule Phys[n]damage to 1 foe 3x to[n]4x. Guaranteed Critical.[n][e]

[msg skill_11B]
[s]Deals miniscule Phys[n]damage to all foes.[n]Guaranteed Critical.[n][e]

[msg skill_11C]
[s]Deals Almighty damage to[n]all foes. Dmg influenced[n]by current party members.[n][e]

[msg skill_11D]
[s]Revives the protagonist[n]and fully restores HP[n](when used by Rise).[n][e]

[msg skill_11E]
[s]Party recovers 10% of[n]its HP after battle.[n][e]

[msg skill_11F]
[s]Party recovers 10% of[n]its SP after battle.[n][e]

[msg skill_120]
[s]Restores 20HP to an[n]ally.[n][e]

[msg skill_121]
[s]Restores 100HP to an[n]ally.[n][e]

[msg skill_122]
[s]Restores 200HP to an[n]ally.[n][e]

[msg skill_123]
[s]Restores 400HP to an[n]ally.[n][e]

[msg skill_124]
[s]Restores 30% of an[n]ally's max HP.[n][e]

[msg skill_125]
[s]Fully restores an[n]ally's HP.[n][e]

[msg skill_126]
[s]Restores 100HP to all[n]allies.[n][e]

[msg skill_127]
[s]Restores 200HP to all[n]allies.[n][e]

[msg skill_128]
[s]Restores 400HP to all[n]allies.[n][e]

[msg skill_129]
[s]Fully restores party's[n]HP.[n][e]

[msg skill_12A]
[s]Restores 10SP to an[n]ally.[n][e]

[msg skill_12B]
[s]Restores 50SP to an[n]ally.[n][e]

[msg skill_12C]
[s]Restores 100SP to an[n]ally.[n][e]

[msg skill_12D]
[s]Restores all of an[n]ally's SP.[n][e]

[msg skill_12E]
[s]Revives an ally and[n]restores 50% of HP.[n][e]

[msg skill_12F]
[s]Revives an ally and[n]fully restores HP.[n][e]

[msg skill_130]
[s]Cures Enervation and[n]Exhaustion (1 ally).[n][e]

[msg skill_131]
[s]Cures Poison[n](1 ally).[n][e]

[msg skill_132]
[s]Cures Silence[n](1 ally).[n][e]

[msg skill_133]
[s]Cures Panic, Fear and[n]Rage (1 ally).[n][e]

[msg skill_134]
[s]Cures Dizzy and Down[n](1 ally).[n][e]

[msg skill_135]
[s]Light: deals light damage[n]to all foes 4x to 8x.[n][e]

[msg skill_136]
[s]100% chance of escaping[n]a battle (some battles[n]are inescapable).[n][e]

[msg skill_137]
[s]Fully restores[n]party's HP and SP.[n][e]

[msg skill_138]
[s]Cures all ailments[n]besides Down and[n]Unconscious (party).[n][e]

[msg skill_139]
[s]Cures all ailments[n]besides Down and[n]Unconscious (1 ally).[n][e]

[msg skill_13A]
[s]Restores 100HP to[n]an ally with a low[n]chance of Rage.[n][e]

[msg skill_13B]
[s]Restores 100HP to[n]an ally with a low[n]chance of Fear.[n][e]

[msg skill_13C]
[s]Restores 100HP to[n]an ally with a low[n]chance of Silence.[n][e]

[msg skill_13D]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_13E]
[s]Barrier that reflects[n]magic one time[n](party).[n][e]

[msg skill_13F]
[s]Barrier that reflects[n]phys atk one time[n](party).[n][e]

[msg skill_140]
[s]Increases party's[n]Attack for 3 turns.[n][e]

[msg skill_141]
[s]Increases party's[n]Hit/Evasion rate[n]for 3 turns.[n][e]

[msg skill_142]
[s]Increases party's[n]Defense for 3 turns.[n][e]

[msg skill_143]
[s]Nullifies stat bonuses[n](all foes).[n][e]

[msg skill_144]
[s]Nullifies stat[n]penalties (party).[n][e]

[msg skill_145]
[s]Deals 50 points of Fire[n]damage to 1 enemy.[n][e]

[msg skill_146]
[s]Deals 50 points of Fire[n]damage to all enemies.[n][e]

[msg skill_147]
[s]Deals 50 points of Ice[n]damage to 1 enemy.[n][e]

[msg skill_148]
[s]Deals 50 points of Ice[n]damage to all enemies.[n][e]

[msg skill_149]
[s]Deals 50 points of Wind[n]damage to 1 enemy.[n][e]

[msg skill_14A]
[s]Deals 50 points of Wind[n]damage to all enemies.[n][e]

[msg skill_14B]
[s]Deals 50 points of Elec[n]damage to 1 enemy.[n][e]

[msg skill_14C]
[s]Deals 50 points of Elec[n]damage to all enemies.[n][e]

[msg skill_14D]
[s]Deals 100 points of[n]non-elemental damage[n]to all enemies.[n][e]

[msg skill_14E]
[s]Casts Hamaon on 1[n]enemy.[n][e]

[msg skill_14F]
[s]Casts Mudoon on 1[n]enemy.[n][e]

[msg skill_150]
[s]Deals 150 points of[n]Fire damage to 1 enemy.[n][e]

[msg skill_151]
[s]Deals 150 points of[n]Wind damage to 1 enemy.[n][e]

[msg skill_152]
[s]Deals 150 points of[n]Ice damage to 1 enemy.[n][e]

[msg skill_153]
[s]Deals 150 points of[n]Elec damage to 1 enemy.[n][e]

[msg skill_154]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_155]
[s]Restores all of one[n]ally's HP.[n][e]

[msg skill_156]
[s]Restores all of one[n]ally's SP.[n][e]

[msg skill_157]
[s]Restores 100HP to an[n]ally.[n][e]

[msg skill_158]
[s]Restores 10HP to an[n]ally.[n][e]

[msg skill_159]
[s]Restores 10SP to an[n]ally.[n][e]

[msg skill_15A]
[s]Restores 5SP to an[n]ally.[n][e]

[msg skill_15B]
[s]Restores 25HP to an[n]ally.[n][e]

[msg skill_15C]
[s]Restores 50HP to an[n]ally.[n][e]

[msg skill_15D]
[s]Deals Almighty damage to[n]all foes. Dmg influenced[n]by current party members.[n][e]

[msg skill_15E]
[s]Deals Almighty damage to[n]all foes. Dmg influenced[n]by current party members.[n][e]

[msg skill_15F]
[s]Deals Almighty damage to[n]all foes. Dmg influenced[n]by current party members.[n][e]

[msg skill_160]
[s]Deals miniscule Wind[n]damage to 1 foe.[n][e]

[msg skill_161]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_162]
[s]Deals light Fire[n]damage to all foes.[n][e]

[msg skill_163]
[s]Dispels Fear and[n]deals medium Almighty[n]damage to 1 foe.[n][e]

[msg skill_164]
[s]Summons the Prince[n](when used by a foe).[n][e]

[msg skill_165]
[s]Fails to summon the[n]Prince.[n][e]

[msg skill_166]
[s]Inflicts Poison on all[n]male foes. Guaranteed.[n][e]

[msg skill_167]
[s]Inflicts Rage on all[n]female foes. Guaranteed.[n][e]

[msg skill_168]
[s]Deals medium Elec[n]damage to all foes.[n][e]

[msg skill_169]
[s]Prevents all enemy[n]attacks from connecting[n](party). Indefinite.[n][e]

[msg skill_16A]
[s]Inflicts Knockdown, deals[n]severe Almighty dmg to all[n]foes. Insta-kills if Dizzy.[n][e]

[msg skill_16B]
[s]No effect.[n][e]

[msg skill_16C]
[s]Deals medium Almighty[n]damage to 1 foe.[n]Inflicts Knockdown.[n][e]

[msg skill_16D]
[s]Deals medium Phys[n]damage to 1 foe.[n][e]

[msg skill_16E]
[s]Builds first stage[n]of Shadow Mitsuo's[n]shell.[n][e]

[msg skill_16F]
[s]Builds second stage[n]of Shadow Mitsuo's[n]shell.[n][e]

[msg skill_170]
[s]Builds third stage[n]of Shadow Mitsuo's[n]shell.[n][e]

[msg skill_171]
[s]Builds Shadow Mitsuo's[n]entire shell.[n][e]

[msg skill_172]
[s]Deals heavy Almighty[n]damage to 1 foe[n](Fight).[n][e]

[msg skill_173]
[s]Deals medium Almighty[n]damage to 1 foe.[n]Inflicts Exhaustion (Bomb).[n][e]

[msg skill_174]
[s]Deals heavy Almighty[n]damage to all foes[n](Gigadyne, 1 Morale Icon).[n][e]

[msg skill_175]
[s]Deals heavy Almighty[n]damage to all foes[n](Gigadyne, 2 Morale Icons).[n][e]

[msg skill_176]
[s]Deals heavy Almighty[n]damage to all foes[n](Gigadyne, 3 Morale Icons).[n][e]

[msg skill_177]
[s]Deals heavy Almighty[n]damage to all foes[n](Gigadyne, 4 Morale Icons).[n][e]

[msg skill_178]
[s]Nullifies all foes'[n]Fire/Ice/Elec/Wind[n]resistances.[n][e]

[msg skill_179]
[s]Deals severe magic[n]damage to 1 foe.[n]Inflicts Silence.[n][e]

[msg skill_17A]
[s]Raises the strength of a[n]random elemental type,[n]reduces the others (all).[n][e]

[msg skill_17B]
[s]Control one player unit[n](when used by a foe).[n][e]

[msg skill_17C]
[s]Deals heavy Almighty[n]damage to all foes.[n][e]

[msg skill_17D]
[s]Deals severe Almighty[n]damage to all foes.[n][e]

[msg skill_17E]
[s]Deals severe Almighty[n]dmg to all foes. Medium[n]chance of Knockdown.[n][e]

[msg skill_17F]
[s]Prevents all enemy[n]attacks from connecting[n](party). Indefinite.[n][e]

[msg skill_180]
[s]Allows enemy attacks[n]to connect again[n](if used by foe).[n][e]

[msg skill_181]
[s]Insta-kills 1 foe. Will[n]crash if used against ???/[n]S. Rise/Marie/Izanami.[n][e]

[msg skill_182]
[s]Deals heavy Almighty[n]dmg to all foes. High[n]chance of ailment.[n][e]

[msg skill_183]
[s]Instills Fear in 1 foe.[n]Guaranteed.[n][e]

[msg skill_184]
[s]Control 3 player units[n](when used by a foe).[n][e]

[msg skill_185]
[s]Deals heavy Almighty[n]damage to all foes.[n][e]

[msg skill_186]
[s]Prevents all enemy[n]attacks from connecting[n](party). Indefinite.[n][e]

[msg skill_187]
[s]Insta-kills all foes[n]inflicted with status[n]ailments.[n][e]

[msg skill_188]
[s]Deals severe Almighty[n]damage to all foes.[n][e]

[msg skill_189]
[s]Deals 999 points of[n]Almighty damage to[n]all foes.[n][e]

[msg skill_18A]
[s]Deals 9999 points of[n]Almighty damage to[n]all foes.[n][e]

[msg skill_18B]
[s]No effect.[n]Will always miss.[n][e]

[msg skill_18C]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_18D]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_18E]
[s]Deals Almighty damage to[n]all foes. Dmg influenced[n]by current party members.[n][e]

[msg skill_18F]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_190]
[s]Low chance of making[n]1 foe Panic.[n][e]

[msg skill_191]
[s]Low chance of making[n]1 foe Panic.[n][e]

[msg skill_192]
[s]Low chance of making[n]1 foe Panic.[n][e]

[msg skill_193]
[s]Low chance of[n]Poisoning 1 foe.[n][e]

[msg skill_194]
[s]Low chance of[n]Poisoning 1 foe.[n][e]

[msg skill_195]
[s]Low chance of[n]Poisoning 1 foe.[n][e]

[msg skill_196]
[s]Low chance of instilling[n]Fear in 1 foe.[n][e]

[msg skill_197]
[s]Low chance of instilling[n]Fear in 1 foe.[n][e]

[msg skill_198]
[s]Low chance of instilling[n]Fear in 1 foe.[n][e]

[msg skill_199]
[s]Low chance of[n]Enraging 1 foe.[n][e]

[msg skill_19A]
[s]Low chance of[n]Enraging 1 foe.[n][e]

[msg skill_19B]
[s]Low chance of[n]Enraging 1 foe.[n][e]

[msg skill_19C]
[s]Low chance of making[n]1 foe Dizzy.[n][e]

[msg skill_19D]
[s]Low chance of making[n]1 foe Dizzy.[n][e]

[msg skill_19E]
[s]Low chance of making[n]1 foe Dizzy.[n][e]

[msg skill_19F]
[s]Low chance of[n]Exhausting 1 foe.[n][e]

[msg skill_1A0]
[s]Low chance of[n]Exhausting 1 foe.[n][e]

[msg skill_1A1]
[s]Low chance of[n]Exhausting 1 foe.[n][e]

[msg skill_1A2]
[s]Low chance of[n]Enervating 1 foe.[n][e]

[msg skill_1A3]
[s]Low chance of[n]Enervating 1 foe.[n][e]

[msg skill_1A4]
[s]Low chance of[n]Enervating 1 foe.[n][e]

[msg skill_1A5]
[s]Low chance of[n]Silencing 1 foe.[n][e]

[msg skill_1A6]
[s]Low chance of[n]Silencing 1 foe.[n][e]

[msg skill_1A7]
[s]Low chance of[n]Silencing 1 foe.[n][e]

[msg skill_1A8]
[s]Low chance of inflicting[n]a status ailment[n](1 foe).[n][e]

[msg skill_1A9]
[s]Low chance of inflicting[n]a status ailment[n](1 foe).[n][e]

[msg skill_1AA]
[s]Low chance of inflicting[n]a status ailment[n](1 foe).[n][e]

[msg skill_1AB]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1AC]
[s]Dark: deals heavy damage[n]to all foes with a chance[n]of Panic/Fear/Enervation.[n][e]

[msg skill_1AD]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1AE]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1AF]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1B0]
[s]Fully restores party's[n]HP and nullifies all[n]stat penalties.[n][e]

[msg skill_1B1]
[s]Restores 50% HP of[n]party and increases[n]Hit/Evasion rates.[n][e]

[msg skill_1B2]
[s]Deals heavy Almighty[n]damage to all foes with a[n]high chance of instant kill.[n][e]

[msg skill_1B3]
[s]Deals heavy Almighty[n]damage to all foes 3x.[n][e]

[msg skill_1B4]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1B5]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1B6]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1B7]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1B8]
[s]Restores 30% of[n]max HP to 1 ally.[n][e]

[msg skill_1B9]
[s]Revives an ally and[n]restores 50% of HP.[n][e]

[msg skill_1BA]
[s]Recovers 20SP[n]for one ally.[n][e]

[msg skill_1BB]
[s]Recovers 50SP[n]to party.[n][e]

[msg skill_1BC]
[s]Fully restores[n]1 ally's HP and SP.[n][e]

[msg skill_1BD]
[s]Deals 50 points of Fire[n]damage to 1 enemy.[n][e]

[msg skill_1BE]
[s]Deals 50 points of Ice[n]damage to 1 enemy.[n][e]

[msg skill_1BF]
[s]Deals 50 points of Wind[n]damage to 1 enemy.[n][e]

[msg skill_1C0]
[s]Deals 50 points of Elec[n]damage to 1 enemy.[n][e]

[msg skill_1C1]
[s]Deals 150 points of Fire[n]damage to 1 enemy.[n][e]

[msg skill_1C2]
[s]Deals 150 points of Ice[n]damage to 1 enemy.[n][e]

[msg skill_1C3]
[s]Deals 150 points of Wind[n]damage to 1 enemy.[n][e]

[msg skill_1C4]
[s]Deals 150 points of Elec[n]damage to 1 enemy.[n][e]

[msg skill_1C5]
[s]Recovers 25SP[n]for one ally.[n][e]

[msg skill_1C6]
[s]Recovers 50SP[n]for one ally.[n][e]

[msg skill_1C7]
[s]Restores 200HP[n]to an ally.[n][e]

[msg skill_1C8]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1C9]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1CA]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1CB]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1CC]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1CD]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1CE]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1CF]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1D0]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1D1]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1D2]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1D3]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1D4]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1D5]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1D6]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1D7]
[s]Unused/Debug.[n]Deals miniscule[n]damage to 1 foe.[n][e]

[msg skill_1D8]
[s]Reduces damage from[n]Phys attacks. Nullifies[n]weakness.[n][e]

[msg skill_1D9]
[s]Nullifies damage from[n]Phys attacks.[n][e]

[msg skill_1DA]
[s]Reflects damage from[n]Phys attacks.[n][e]

[msg skill_1DB]
[s]Absorbs damage from[n]Phys attacks.[n][e]

[msg skill_1DC]
[s]Reduces damage from[n]Fire attacks. Nullifies[n]weakness.[n][e]

[msg skill_1DD]
[s]Nullifies damage from[n]Fire attacks.[n][e]

[msg skill_1DE]
[s]Reflects damage from[n]Fire attacks.[n][e]

[msg skill_1DF]
[s]Absorbs damage from[n]Fire attacks.[n][e]

[msg skill_1E0]
[s]Reduces damage from[n]Ice attacks. Nullifies[n]weakness.[n][e]

[msg skill_1E1]
[s]Nullifies damage from[n]Ice attacks.[n][e]

[msg skill_1E2]
[s]Reflects damage from[n]Ice attacks.[n][e]

[msg skill_1E3]
[s]Absorbs damage from[n]Ice attacks.[n][e]

[msg skill_1E4]
[s]Reduces damage from[n]Elec attacks. Nullifies[n]weakness.[n][e]

[msg skill_1E5]
[s]Nullifies damage from[n]Elec attacks.[n][e]

[msg skill_1E6]
[s]Reflects damage from[n]Elec attacks.[n][e]

[msg skill_1E7]
[s]Absorbs damage from[n]Elec attacks.[n][e]

[msg skill_1E8]
[s]Reduces damage from[n]Wind attacks. Nullifies[n]weakness.[n][e]

[msg skill_1E9]
[s]Nullifies damage from[n]Wind attacks.[n][e]

[msg skill_1EA]
[s]Reflects damage from[n]Wind attacks.[n][e]

[msg skill_1EB]
[s]Absorbs damage from[n]Wind attacks.[n][e]

[msg skill_1EC]
[s]Reduces chance of KO[n]from Light attacks.[n]Nullifies weakness.[n][e]

[msg skill_1ED]
[s]Nullifies Light attacks.[n][e]

[msg skill_1EE]
[s]Reflects Light attacks.[n][e]

[msg skill_1EF]
[s]Reduces chance of KO[n]from Darkness attacks.[n]Nullifies weakness.[n][e]

[msg skill_1F0]
[s]Nullifies Darkness[n]attacks.[n][e]

[msg skill_1F1]
[s]Reflects Darkness[n]attacks.[n][e]

[msg skill_1F2]
[s]Protects user from[n]Panic.[n][e]

[msg skill_1F3]
[s]Protects user from[n]Exhaustion.[n][e]

[msg skill_1F4]
[s]Protects user from[n]Silence.[n][e]

[msg skill_1F5]
[s]Protects user from[n]Fear.[n][e]

[msg skill_1F6]
[s]Protects user from[n]Rage.[n][e]

[msg skill_1F7]
[s]Protects user from[n]Poison.[n][e]

[msg skill_1F8]
[s]Protects user from[n]Dizzy.[n][e]

[msg skill_1F9]
[s]Protects user from[n]Enervation.[n][e]

[msg skill_1FA]
[s]Protects user from[n]Panic/Fear/Silence/[n]Enervation/Rage.[n][e]

[msg skill_1FB]
[s]Nullifies all attacks[n]but Almighty.[n][e]

[msg skill_1FC]
[s]Doubles evasion rate[n]against Phys attacks.[n][e]

[msg skill_1FD]
[s]Triples evasion rate[n]against Phys attacks.[n]Does not stack.[n][e]

[msg skill_1FE]
[s]Doubles evasion rate[n]against Fire attacks.[n][e]

[msg skill_1FF]
[s]Triples evasion rate[n]against Fire attacks.[n]Does not stack.[n][e]

[msg skill_200]
[s]Doubles evasion rate[n]against Ice attacks.[n][e]

[msg skill_201]
[s]Triples evasion rate[n]against Ice attacks.[n]Does not stack.[n][e]

[msg skill_202]
[s]Doubles evasion rate[n]against Wind attacks.[n][e]

[msg skill_203]
[s]Triples evasion rate[n]against Wind attacks.[n]Does not stack.[n][e]

[msg skill_204]
[s]Doubles evasion rate[n]against Elec attacks.[n][e]

[msg skill_205]
[s]Triples evasion rate[n]against Elec attacks.[n]Does not stack.[n][e]

[msg skill_206]
[s]Doubles evasion rate[n]against all attacks but[n]Light/Darkness/Almighty.[n][e]

[msg skill_207]
[s]Strengthens Fire[n]attacks by 25%.[n][e]

[msg skill_208]
[s]Strengthens Fire[n]attacks by 50%.[n]Can stack.[n][e]

[msg skill_209]
[s]Strengthens Ice[n]attacks by 25%.[n][e]

[msg skill_20A]
[s]Strengthens Ice[n]attacks by 50%.[n]Can stack.[n][e]

[msg skill_20B]
[s]Strengthens Elec[n]attacks by 25%.[n][e]

[msg skill_20C]
[s]Strengthens Elec[n]attacks by 50%.[n]Can stack.[n][e]

[msg skill_20D]
[s]Strengthens Wind[n]attacks by 25%.[n][e]

[msg skill_20E]
[s]Strengthens Wind[n]attacks by 50%.[n]Can stack.[n][e]

[msg skill_20F]
[s]Allows you to escape[n]from almost all battles.[n][e]

[msg skill_210]
[s]Increases max HP by 10%.[n][e]

[msg skill_211]
[s]Increases max HP by 20%.[n][e]

[msg skill_212]
[s]Increases max HP by 30%.[n][e]

[msg skill_213]
[s]Increases max SP by 10%.[n][e]

[msg skill_214]
[s]Increases max SP by 20%.[n][e]

[msg skill_215]
[s]Increases max SP by 30%.[n][e]

[msg skill_216]
[s]10% chance of reflecting[n]Phys attacks.[n][e]

[msg skill_217]
[s]15% chance of reflecting[n]Phys attacks. Does[n]not stack.[n][e]

[msg skill_218]
[s]20% chance of reflecting[n]Phys attacks. Does[n]not stack.[n][e]

[msg skill_219]
[s]Restores 2% of max HP[n]each turn in battle.[n][e]

[msg skill_21A]
[s]Restores 4% of max HP[n]each turn in battle.[n][e]

[msg skill_21B]
[s]Restores 6% of max HP[n]each turn in battle.[n][e]

[msg skill_21C]
[s]Restores 3 SP[n]each turn in battle.[n][e]

[msg skill_21D]
[s]Restores 5 SP[n]each turn in battle.[n][e]

[msg skill_21E]
[s]Restores 7 SP[n]each turn in battle.[n][e]

[msg skill_21F]
[s]Persona gains 1/4 EXP[n]while inactive.[n][e]

[msg skill_220]
[s]Persona gains 1/2 EXP[n]while inactive.[n][e]

[msg skill_221]
[s]Persona gains full EXP[n]while inactive.[n][e]

[msg skill_222]
[s]Increases user's Attack[n]automatically for 3 turns[n]at the start of battle.[n][e]

[msg skill_223]
[s]Increases user's Defense[n]automatically for 3 turns[n]at the start of battle.[n][e]

[msg skill_224]
[s]Increases user's Hit/Evasion[n]rates automatically for 3[n]turns at the start of battle.[n][e]

[msg skill_225]
[s]Lowers odds of being[n]taken by surprise.[n][e]

[msg skill_226]
[s]Lowers odds of[n]sustaining crit dmg.[n][e]

[msg skill_227]
[s]Increases user's[n]Critical Rate.[n][e]

[msg skill_228]
[s]The Hit rate of an[n]attacking unit is[n]reduced by half.[n][e]

[msg skill_229]
[s]Always take half damage,[n]but you can never evade.[n][e]

[msg skill_22A]
[s]Halves SP cost for[n]magic skills.[n][e]

[msg skill_22B]
[s]Halves HP cost for[n]physical skills.[n][e]

[msg skill_22C]
[s]Max HP doubles,[n]max SP halves.[n][e]

[msg skill_22D]
[s]Max SP doubles,[n]max HP halves.[n][e]

[msg skill_22E]
[s]Effects of healing magic[n]are increased by 50%.[n][e]

[msg skill_22F]
[s]Restores 1 HP upon[n]Unconscious 1x per[n]battle.[n][e]

[msg skill_230]
[s]Restores all HP upon[n]Unconscious 1x per[n]battle.[n][e]

[msg skill_231]
[s]50% chance of being[n]revived with 1 HP if[n]killed by Light.[n][e]

[msg skill_232]
[s]50% chance of being[n]revived with 1 HP if[n]killed by Darkness.[n][e]

[msg skill_233]
[s]Increases Defense[n]automatically for 3 turns at[n]the start of battle (party).[n][e]

[msg skill_234]
[s]Increases Attack[n]automatically for 3 turns at[n]the start of battle (party).[n][e]

[msg skill_235]
[s]Increases Hit/Evasion rates[n]automatically for 3 turns at[n]the start of battle (party).[n][e]

[msg skill_236]
[s]Increases odds of[n]inflicting Panic.[n][e]

[msg skill_237]
[s]Increases odds of[n]inflicting Poison.[n][e]

[msg skill_238]
[s]Increases odds of[n]inflicting Exhaustion.[n][e]

[msg skill_239]
[s]Increases odds of[n]inflicting Silence.[n][e]

[msg skill_23A]
[s]Increases odds of[n]inflicting Fear.[n][e]

[msg skill_23B]
[s]Increases odds of[n]inflicting Rage.[n][e]

[msg skill_23C]
[s]Increases odds of[n]inflicting Dizziness[n]during a Knockdown.[n][e]

[msg skill_23D]
[s]Increases odds of[n]inflicting Enervation.[n][e]

[msg skill_23E]
[s]Increases odds of[n]inflicting any ailment.[n][e]

[msg skill_23F]
[s]Increases success rate[n]of Light magic.[n][e]

[msg skill_240]
[s]Increases success rate[n]of Darkness magic.[n][e]

[msg skill_241]
[s]Automatic revival with[n]1 HP when killed by[n]Light magic.[n][e]

[msg skill_242]
[s]Automatic revival with[n]1 HP when killed by[n]Darkness magic.[n][e]

[msg skill_243]
[s]Restores 8% of HP[n]and SP after battle.[n][e]

[msg skill_244]
[s]Fully restores HP and[n]SP after battle.[n][e]

[msg skill_245]
[s]Reduces chance of being[n]Poisoned.[n][e]

[msg skill_246]
[s]Reduces chance of being[n]Panicked.[n][e]

[msg skill_247]
[s]Reduces chance of being[n]Feared.[n][e]

[msg skill_248]
[s]Reduces chance of being[n]Exhausted.[n][e]

[msg skill_249]
[s]Reduces chance of being[n]Enervated.[n][e]

[msg skill_24A]
[s]Reduces chance of being[n]Enraged.[n][e]

[msg skill_24B]
[s]Reduces chance of being[n]Dizzy.[n][e]

[msg skill_24C]
[s]Reduces chance of being[n]Silenced.[n][e]

[msg skill_24D]
[s]Increases max HP by 50%.[n][e]

[msg skill_24E]
[s]Increases max SP by 50%.[n][e]

[msg skill_24F]
[s]Time needed to recover[n]from ailments is halved.[n][e]

[msg skill_250]
[s]Time needed to recover[n]from ailments is reduced[n]to 1 turn.[n][e]

[msg skill_251]
[s]Allows user to[n]withstand all attacks[n]indefinitely.[n][e]

[msg skill_252]
[s]Allows user to[n]withstand all attacks[n]indefinitely.[n][e]

[msg skill_253]
[s]Reflects damage from[n]Phys attacks.[n][e]

[msg skill_254]
[s]Skill254[n][e]

[msg skill_255]
[s]Skill255[n][e]

[msg skill_256]
[s]Skill256[n][e]

[msg skill_257]
[s]Skill257[n][e]

[msg skill_258]
[s]Skill258[n][e]

[msg skill_259]
[s]Skill259[n][e]

[msg skill_25A]
[s]Skill25A[n][e]

[msg skill_25B]
[s]Skill25B[n][e]

[msg skill_25C]
[s]Skill25C[n][e]

[msg skill_25D]
[s]Skill25D[n][e]

[msg skill_25E]
[s]Skill25E[n][e]

[msg skill_25F]
[s]Skill25F[n][e]

