[msg skill_000]
[s]Blank[n][e]

[msg skill_001]
[s]Deals light Fire[n]damage to 1 foe.[n][e]

[msg skill_002]
[s]Deals medium Fire[n]damage to 1 foe.[n][e]

[msg skill_003]
[s]Deals heavy Fire[n]damage to 1 foe.[n][e]

[msg skill_004]
[s]Deals light Fire[n]damage to all foes.[n][e]

[msg skill_005]
[s]Deals medium Fire[n]damage to all foes.[n][e]

[msg skill_006]
[s]Deals heavy Fire[n]damage to all foes.[n][e]

[msg skill_007]
[s]Deals heavy Fire[n]damage to all foes.[n][e]

[msg skill_008]
[s]Deals severe Fire[n]damage to 1 foe.[n][e]

[msg skill_009]
[s]Deals severe Fire[n]damage to all foes.[n][e]

[msg skill_00A]
[s]Skill00A[n][e]

[msg skill_00B]
[s]Skill00B[n][e]

[msg skill_00C]
[s]Skill00C[n][e]

[msg skill_00D]
[s]Skill00D[n][e]

[msg skill_00E]
[s]Deals light Wind[n]damage to 1 foe.[n][e]

[msg skill_00F]
[s]Deals medium Wind[n]damage to 1 foe.[n][e]

[msg skill_010]
[s]Deals heavy Wind[n]damage to 1 foe.[n][e]

[msg skill_011]
[s]Deals light Wind[n]damage to all foes.[n][e]

[msg skill_012]
[s]Deals medium Wind[n]damage to all foes.[n][e]

[msg skill_013]
[s]Deals heavy Wind[n]damage to all foes.[n][e]

[msg skill_014]
[s]Deals heavy Wind[n]damage to all foes.[n][e]

[msg skill_015]
[s]Deals severe Wind[n]damage to 1 foe.[n][e]

[msg skill_016]
[s]Skill016[n][e]

[msg skill_017]
[s]Skill017[n][e]

[msg skill_018]
[s]Skill018[n][e]

[msg skill_019]
[s]Skill019[n][e]

[msg skill_01A]
[s]Deals light Ice[n]damage to 1 foe.[n][e]

[msg skill_01B]
[s]Deals medium Ice[n]damage to 1 foe.[n][e]

[msg skill_01C]
[s]Deals heavy Ice[n]damage to 1 foe.[n][e]

[msg skill_01D]
[s]Deals light Ice[n]damage to all foes.[n][e]

[msg skill_01E]
[s]Deals medium Ice[n]damage to all foes.[n][e]

[msg skill_01F]
[s]Deals heavy Ice[n]damage to all foes.[n][e]

[msg skill_020]
[s]Deals heavy Ice[n]damage to all foes.[n][e]

[msg skill_021]
[s]Deals severe Ice[n]damage to 1 foe.[n][e]

[msg skill_022]
[s]Deals severe Ice[n]damage to all foes.[n][e]

[msg skill_023]
[s]Skill023[n][e]

[msg skill_024]
[s]Skill024[n][e]

[msg skill_025]
[s]Skill025[n][e]

[msg skill_026]
[s]Skill026[n][e]

[msg skill_027]
[s]Deals light Elec[n]damage to 1 foe.[n][e]

[msg skill_028]
[s]Deals medium Elec[n]damage to 1 foe.[n][e]

[msg skill_029]
[s]Deals heavy Elec[n]damage to 1 foe.[n][e]

[msg skill_02A]
[s]Deals light Elec[n]damage to all foes.[n][e]

[msg skill_02B]
[s]Deals medium Elec[n]damage to all foes.[n][e]

[msg skill_02C]
[s]Deals heavy Elec[n]damage to all foes.[n][e]

[msg skill_02D]
[s]Deals heavy Elec[n]damage to all foes.[n][e]

[msg skill_02E]
[s]Deals severe Elec[n]damage to 1 foe.[n][e]

[msg skill_02F]
[s]Skill02F[n][e]

[msg skill_030]
[s]Skill030[n][e]

[msg skill_031]
[s]Skill031[n][e]

[msg skill_032]
[s]Skill032[n][e]

[msg skill_033]
[s]Deals medium Almighty[n]damage to all foes.[n][e]

[msg skill_034]
[s]Deals heavy Almighty[n]damage to all foes.[n][e]

[msg skill_035]
[s]Deals severe Almighty[n]damage to all foes.[n][e]

[msg skill_036]
[s]Deals medium Almighty[n]damage to everyone,[n][e]

[msg skill_037]
[s]Deals massive Almighty[n]damage to 1 foe.[n][e]

[msg skill_038]
[s]Deals massive Almighty[n]damage to all foes.[n][e]

[msg skill_039]
[s]Skill039[n][e]

[msg skill_03A]
[s]Skill03A[n][e]

[msg skill_03B]
[s]Skill03B[n][e]

[msg skill_03C]
[s]Skill03C[n][e]

[msg skill_03D]
[s]Light: low chance of[n]instant kill, 1 foe.[n][e]

[msg skill_03E]
[s]Light: medium chance of[n]instant kill, 1 foe.[n][e]

[msg skill_03F]
[s]Light: low chance of[n]instant kill, all foes.[n][e]

[msg skill_040]
[s]Light: medium chance of[n]instant kill, all foes.[n][e]

[msg skill_041]
[s]Light: chance of[n]reducing foes to 1/4 HP.[n][e]

[msg skill_042]
[s]Light: chance of[n]reducing foes to 1/2 HP.[n][e]

[msg skill_043]
[s]Light: instant kill to[n]all foes with no Light[n]resistance.[n][e]

[msg skill_044]
[s]Skill044[n][e]

[msg skill_045]
[s]Skill045[n][e]

[msg skill_046]
[s]Skill046[n][e]

[msg skill_047]
[s]Skill047[n][e]

[msg skill_048]
[s]Darkness: low chance of[n]instant kill, 1 foe.[n][e]

[msg skill_049]
[s]Darkness: medium chance[n]of instant kill, 1 foe.[n][e]

[msg skill_04A]
[s]Darkness: low chance of[n]instant kill, all foes.[n][e]

[msg skill_04B]
[s]Darkness: med chance of[n]instant kill, all foes.[n][e]

[msg skill_04C]
[s]Darkness: chance of[n]reducing foes to 1/4 HP.[n][e]

[msg skill_04D]
[s]Darkness: chance of[n]reducing foes to 1/2 HP.[n][e]

[msg skill_04E]
[s]Darkness: instant kill[n]to all foes with no[n]Darkness resistance.[n][e]

[msg skill_04F]
[s]Skill04F[n][e]

[msg skill_050]
[s]Deals severe Fire[n]damage to all foes.[n][e]

[msg skill_051]
[s]Skill051[n][e]

[msg skill_052]
[s]Skill052[n][e]

[msg skill_053]
[s]Makes 1 foe Panic.[n][e]

[msg skill_054]
[s]Makes all foes Panic.[n][e]

[msg skill_055]
[s]Instills Fear in 1 foe.[n][e]

[msg skill_056]
[s]Instills Fear in all[n]foes.[n][e]

[msg skill_057]
[s]Instantly kills foes[n]who are Feared.[n][e]

[msg skill_058]
[s]Enrages 1 foe.[n][e]

[msg skill_059]
[s]Enrages all foes.[n][e]

[msg skill_05A]
[s]Poisons 1 foe.[n][e]

[msg skill_05B]
[s]Poisons all foes.[n][e]

[msg skill_05C]
[s]Exhausts 1 foe.[n][e]

[msg skill_05D]
[s]Exhausts all foes.[n][e]

[msg skill_05E]
[s]Enervates 1 foe.[n][e]

[msg skill_05F]
[s]Enervates all foes.[n][e]

[msg skill_060]
[s]Reduces 1 foe's HP to 1[n]and has a chance of[n]Enervation.[n][e]

[msg skill_061]
[s]Silences 1 foe.[n][e]

[msg skill_062]
[s]Silences all foes.[n][e]

[msg skill_063]
[s]Increases chances of all[n]status ailments for 1[n]foe (temporary)[n][e]

[msg skill_064]
[s]Increases chances of all[n]status ailments for all[n]foes (temporary)[n][e]

[msg skill_065]
[s]Drains 1 foe's HP.[n][e]

[msg skill_066]
[s]Drains 1 foe's SP.[n][e]

[msg skill_067]
[s]Drains a large amount[n]of 1 foe's HP.[n][e]

[msg skill_068]
[s]Drains a large amount[n]of a foe's SP.[n][e]

[msg skill_069]
[s]HP of all foes that are[n]weark to Light/Darkness[n]are reduced to 1.[n][e]

[msg skill_06A]
[s]Enrages 1 target.[n][e]

[msg skill_06B]
[s]Skill06B[n][e]

[msg skill_06C]
[s]Skill06C[n][e]

[msg skill_06D]
[s]Skill06D[n][e]

[msg skill_06E]
[s]Skill06E[n][e]

[msg skill_06F]
[s]Skill06F[n][e]

[msg skill_070]
[s]Skill070[n][e]

[msg skill_071]
[s]Skill071[n][e]

[msg skill_072]
[s]Skill072[n][e]

[msg skill_073]
[s]Skill073[n][e]

[msg skill_074]
[s]Skill074[n][e]

[msg skill_075]
[s]Skill075[n][e]

[msg skill_076]
[s]Skill076[n][e]

[msg skill_077]
[s]Skill077[n][e]

[msg skill_078]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_079]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_07A]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_07B]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_07C]
[s]Deals light Phys[n]damage to 1 foe 2x.[n][e]

[msg skill_07D]
[s]Deals light Phys[n]damage to 1 foe 1x[n]to 3x.[n][e]

[msg skill_07E]
[s]Deals light Phys[n]damage to all foes 1x[n]to 2x.[n][e]

[msg skill_07F]
[s]Deals light Phys[n]damage to 1 foe 2x.[n][e]

[msg skill_080]
[s]Deals medium Phys[n]damage to 1 foe.[n][e]

[msg skill_081]
[s]Deals medium Phys[n]damage to 1 foe.[n][e]

[msg skill_082]
[s]Deals medium Phys[n]damage to 1 foe 2x[n]to 3x.[n][e]

[msg skill_083]
[s]Deals medium Phys[n]damage to all enemies.[n][e]

[msg skill_084]
[s]Deals heavy Phys[n]damage to 1 foe.[n][e]

[msg skill_085]
[s]Deals medium Phys[n]damage to all foes[n]2x to 4x.[n][e]

[msg skill_086]
[s]Deals heavy Phys[n]damage to all foes.[n][e]

[msg skill_087]
[s]Deals heavy Phys[n]damage to all foes 2x.[n][e]

[msg skill_088]
[s]Deals heavy Phys[n]damage to all foes 1x[n]to 2x.[n][e]

[msg skill_089]
[s]Deals heavy Phys[n]damage to 1 foe 1x[n]to 2x.[n][e]

[msg skill_08A]
[s]Deals heavy Phys[n]damage to 1 foe.[n][e]

[msg skill_08B]
[s]Deals heavy Phys[n]damage to all foes 1x[n]to 3x.[n][e]

[msg skill_08C]
[s]Deals severe Phys[n]damage to 1 foe.[n][e]

[msg skill_08D]
[s]Deals severe Phys damage[n]to all foes with a high[n]chance of instant kills.[n][e]

[msg skill_08E]
[s]Deals severe Phys[n]damage to 1 foe.[n][e]

[msg skill_08F]
[s]Deals heavy Phys[n]damage to all foes.[n][e]

[msg skill_090]
[s]Deals medium Phys[n]damage to 1 foe.[n][e]

[msg skill_091]
[s]Deals light Phys[n]damage to all foes.[n][e]

[msg skill_092]
[s]Deals severe Phys[n]damage to 1 foe.[n][e]

[msg skill_093]
[s]Deals medium Phys[n]damage to all foes.[n][e]

[msg skill_094]
[s]Deals heavy Phys[n]damage to all foes.[n][e]

[msg skill_095]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_096]
[s]Deals light Phys[n]damage to 1 foe.[n][e]

[msg skill_097]
[s]Deals light Phys[n]damage to 1 foe with[n]a chance of Poison.[n][e]

[msg skill_098]
[s]Deals medium Phys[n]damage to 1 foe with[n]a chance of Poison.[n][e]

[msg skill_099]
[s]Deals heavy Phys[n]damage to all foes with[n]a chance of Poison.[n][e]

[msg skill_09A]
[s]Deals heavy Phys[n]damage to all foes with[n]a chance of Poison.[n][e]

[msg skill_09B]
[s]Deals light Phys[n]damage to 1 foe with a[n]chance of Panic.[n][e]

[msg skill_09C]
[s]Deals medium Phys[n]damage to all foes with[n]a chance of Panic.[n][e]

[msg skill_09D]
[s]Deals light Phys[n]damage to 1 foe with a[n]chance of Rage.[n][e]

[msg skill_09E]
[s]Deals medium Phys[n]damage to all foes with[n]a chance of Rage.[n][e]

[msg skill_09F]
[s]Deals light Phys[n]damage to 1 foe with a[n]chance of Silence.[n][e]

[msg skill_0A0]
[s]Deals medium Phys[n]damage to all foes with[n]a chance of Silence.[n][e]

[msg skill_0A1]
[s]Deals light Phys[n]damage to 1 foe with a[n]chance of Fear.[n][e]

[msg skill_0A2]
[s]Deals med Phys damage[n]to all foes 1x to 2x[n]with a chance of Fear.[n][e]

[msg skill_0A3]
[s]Deals light Phys[n]damage to 1 foe with a[n]chance of Enervation.[n][e]

[msg skill_0A4]
[s]Deals medium Phys[n]damage to all foes with[n]a chance of Enervation.[n][e]

[msg skill_0A5]
[s]Deals light Phys damage[n]to 1 foe 1x to 3x with[n]a chance of Exhaustion.[n][e]

[msg skill_0A6]
[s]Deals medium Phys[n]damage to all foes with[n]a chance of Exhaustion.[n][e]

[msg skill_0A7]
[s]Deals medium Phys[n]damage to 1 foe with a[n]chance of Fear.[n][e]

[msg skill_0A8]
[s]Deals medium Phys[n]damage to 1 foe.[n][e]

[msg skill_0A9]
[s]Deals heavy Phys[n]damage to 1 foe.[n][e]

[msg skill_0AA]
[s]Deals light Phys[n]damage to all foes 8x.[n][e]

[msg skill_0AB]
[s]Deals light Phys[n]damage to all foes[n]1x to 3x.[n][e]

[msg skill_0AC]
[s]Deals medium Phys[n]damage to all foes[n]1x to 3x.[n][e]

[msg skill_0AD]
[s]Deals heavy Phys[n]damage to all foes[n]1x to 3x.[n][e]

[msg skill_0AE]
[s]Med Phys dmg, 1 foe.[n]Bonus damage to foes[n]that are Down.[n][e]

[msg skill_0AF]
[s]Hvy Phys dmg, 1 foe.[n]Bonus damage to foes[n]that are Down.[n][e]

[msg skill_0B0]
[s]Skill0B0[n][e]

[msg skill_0B1]
[s]Skill0B1[n][e]

[msg skill_0B2]
[s]Skill0B2[n][e]

[msg skill_0B3]
[s]Skill0B3[n][e]

[msg skill_0B4]
[s]Skill0B4[n][e]

[msg skill_0B5]
[s]Skill0B5[n][e]

[msg skill_0B6]
[s]Skill0B6[n][e]

[msg skill_0B7]
[s]Skill0B7[n][e]

[msg skill_0B8]
[s]Skill0B8[n][e]

[msg skill_0B9]
[s]Skill0B9[n][e]

[msg skill_0BA]
[s]Skill0BA[n][e]

[msg skill_0BB]
[s]Skill0BB[n][e]

[msg skill_0BC]
[s]Skill0BC[n][e]

[msg skill_0BD]
[s]Skill0BD[n][e]

[msg skill_0BE]
[s]Skill0BD[n][e]

[msg skill_0BF]
[s]Skill0BF[n][e]

[msg skill_0C0]
[s]Slightly restores[n]1 ally's HP.[n][e]

[msg skill_0C1]
[s]Moderately restores[n]1 ally's HP.[n][e]

[msg skill_0C2]
[s]Fully restores 1[n]ally's HP.[n][e]

[msg skill_0C3]
[s]Slightly restores[n]party's HP.[n][e]

[msg skill_0C4]
[s]Moderately restores[n]party's HP.[n][e]

[msg skill_0C5]
[s]Fully restores[n]party's HP.[n][e]

[msg skill_0C6]
[s]Fully restores party's[n]HP. Cures ailments.[n][e]

[msg skill_0C7]
[s]Dispels Panic, Fear,[n]and Rage (1 ally).[n][e]

[msg skill_0C8]
[s]Dispels Panic, Fear,[n]and Rage (party).[n][e]

[msg skill_0C9]
[s]Recovers 1 ally from[n]Knockdown or Dizzy[n]status.[n][e]

[msg skill_0CA]
[s]Neutralizes Poison[n](1 ally).[n][e]

[msg skill_0CB]
[s]Cures Silence[n](1 ally).[n][e]

[msg skill_0CC]
[s]Recovers Exhaustion[n](1 ally).[n][e]

[msg skill_0CD]
[s]Cures Enervation[n](1 ally).[n][e]

[msg skill_0CE]
[s]Cures Enervation/[n]Exhaustion (1 ally).[n][e]

[msg skill_0CF]
[s]Cures Enervation/[n]Exhaustion (party).[n][e]

[msg skill_0D0]
[s]Cures all ailments[n]except Down and KO[n](party).[n][e]

[msg skill_0D1]
[s]Revives an ally with[n]50% HP.[n][e]

[msg skill_0D2]
[s]Revives an ally with[n]full HP.[n][e]

[msg skill_0D3]
[s]Decreases 1 foe's Attack[n]for 3 turns.[n][e]

[msg skill_0D4]
[s]Decreases all foes'[n]Attack for 3 turns.[n][e]

[msg skill_0D5]
[s]Decreases 1 foe's[n]Hit/Evasion rates for[n]3 turns.[n][e]

[msg skill_0D6]
[s]Decreases all foes'[n]Hit/Evasion rates for[n]3 turns.[n][e]

[msg skill_0D7]
[s]Decreases 1 foe's[n]Defense for 3 turns.[n][e]

[msg skill_0D8]
[s]Decreases all foes'[n]Defense for 3 turns.[n][e]

[msg skill_0D9]
[s]Nullifies stat[n]penalties on party.[n][e]

[msg skill_0DA]
[s]Increases 1 ally's[n]Attack for 3 turns.[n][e]

[msg skill_0DB]
[s]Increases party's[n]Attack for 3 turns.[n][e]

[msg skill_0DC]
[s]Increases 1 ally's[n]Hit/Evasion rate for[n]3 turns.[n][e]

[msg skill_0DD]
[s]Increases party's[n]Hit/Evasion rate for[n]3 turns.[n][e]

[msg skill_0DE]
[s]Increases 1 ally's[n]Defense for 3 turns.[n][e]

[msg skill_0DF]
[s]Increases party's[n]Defense for 3 turns.[n][e]

[msg skill_0E0]
[s]Nullifies stat[n]bonuses on all foes.[n][e]

[msg skill_0E1]
[s]Increases Attack,[n]Defense, and Hit/Evasion[n]rate (1 ally).[n][e]

[msg skill_0E2]
[s]Decreases Attack,[n]Defense, and Hit/Evasion[n]rate (1 foe).[n][e]

[msg skill_0E3]
[s]Doubles damage of next[n]physical attack.[n][e]

[msg skill_0E4]
[s]Doubles damage of next[n]magic attack.[n][e]

[msg skill_0E5]
[s]Barrier that reflects[n]phys dmg once.[n][e]

[msg skill_0E6]
[s]Barrier that reflects[n]magic dmg once.[n][e]

[msg skill_0E7]
[s]Negate all foes'[n]Tetrakarn.[n][e]

[msg skill_0E8]
[s]Negate all foes'[n]Makarakarn.[n][e]

[msg skill_0E9]
[s]Nullifies instant kill[n]attack once (1 ally).[n][e]

[msg skill_0EA]
[s]Increases Critical[n]Rate (1 ally).[n][e]

[msg skill_0EB]
[s]Increases Critical[n]Rate (all).[n][e]

[msg skill_0EC]
[s]Nullifies 1 foe's[n]Fire resistance.[n][e]

[msg skill_0ED]
[s]Nullifies 1 foe's[n]Ice resistance.[n][e]

[msg skill_0EE]
[s]Nullifies 1 foe's[n]Wind resistance.[n][e]

[msg skill_0EF]
[s]Nullifies 1 foe's[n]Elec resistance.[n][e]

[msg skill_0F0]
[s]Add Fire resistance to[n]1 ally.[n][e]

[msg skill_0F1]
[s]Add Ice resistance to[n]1 ally.[n][e]

[msg skill_0F2]
[s]Add Elec resistance to[n]1 ally.[n][e]

[msg skill_0F3]
[s]Add Wind resistance to[n]1 ally.[n][e]

[msg skill_0F4]
[s]Enables escape from[n]most battles.[n][e]

[msg skill_0F5]
[s]Recovers all allies' HP,[n]but caster's HP falls to 1.[n][e]

[msg skill_0F6]
[s]Instantly escape from[n]a dungeon.[n][e]

[msg skill_0F7]
[s]Moderately restores party's[n]HP and raises Hit/Evasion[n]rate for 3 turns.[n][e]

[msg skill_0F8]
[s]Increases party's Attack,[n]Defense, and Hit/Evade.[n][e]

[msg skill_0F9]
[s]Deals severe Fire[n]damage to all foes.[n][e]

[msg skill_0FA]
[s]May inflict Down/Dizzy[n]on all foes.[n][e]

[msg skill_0FB]
[s]Anything could happen...[n][e]

[msg skill_0FC]
[s]Shields the party from[n]all damage once.[n][e]

[msg skill_0FD]
[s]View foe's skills and[n]affinities, including[n]those you have not tried.[n][e]

[msg skill_0FE]
[s]Skill0FE[n][e]

[msg skill_0FF]
[s]Skill0FF[n][e]

[msg skill_100]
[s]Special gang bashing 1.[n][e]

[msg skill_101]
[s]Special gang bashing 2.[n][e]

[msg skill_102]
[s]Special gang bashing 3.[n][e]

[msg skill_103]
[s]Lose money when Panicked.[n][e]

[msg skill_104]
[s]Yosuke's special attack.[n][e]

[msg skill_105]
[s]Chie's special attack.[n][e]

[msg skill_106]
[s]Yukiko's special attack.[n][e]

[msg skill_107]
[s]Kanji's special attack.[n][e]

[msg skill_108]
[s]Teddie's special attack.[n][e]

[msg skill_109]
[s]Naoto's special attack.[n][e]

[msg skill_10A]
[s]Chie's special attack[n](Boss only).[n][e]

[msg skill_10B]
[s]Reveals enemy skills and[n]affinities you've tried[n]when using Analyze.[n][e]

[msg skill_10C]
[s]Shows whether an attack[n]will be effective when[n]choosing a target.[n][e]

[msg skill_10D]
[s]Displays one foe's[n]weakness at the start[n]of battle.[n][e]

[msg skill_10E]
[s]Recovers 5% HP at the[n]end of battle.[n][e]

[msg skill_10F]
[s]Recovers 5% SP at the[n]end of battle.[n][e]

[msg skill_110]
[s]Allows you to analyze[n]foes to find weaknesses.[n][e]

[msg skill_111]
[s]Summon one unit.[n][e]

[msg skill_112]
[s]Displays foes in a wide[n]area of the map, even in[n]unexplored areas.[n][e]

[msg skill_113]
[s]Displays all treasures[n]on the dungeon map.[n][e]

[msg skill_114]
[s]Allows you to escape[n]from almost all battles.[n][e]

[msg skill_115]
[s]The word of power that[n]banishes all the world's[n]curses and falsehoods.[n][e]

[msg skill_116]
[s]Skill116[n][e]

[msg skill_117]
[s]Skill117[n][e]

[msg skill_118]
[s]Skill118[n][e]

[msg skill_119]
[s]Skill119[n][e]

[msg skill_11A]
[s]Skill11A[n][e]

[msg skill_11B]
[s]Skill11B[n][e]

[msg skill_11C]
[s]Skill11C[n][e]

[msg skill_11D]
[s]Skill11D[n][e]

[msg skill_11E]
[s]Party recovers 10% of[n]its HP after battle.[n][e]

[msg skill_11F]
[s]Party recovers 10% of[n]its SP after battle.[n][e]

[msg skill_120]
[s]Item[n]Restores 10HP to an[n]ally.[n][e]

[msg skill_121]
[s]Item[n]Restores 50HP to an[n]ally.[n][e]

[msg skill_122]
[s]Item[n]Restores 100HP to an[n]ally.[n][e]

[msg skill_123]
[s]Item[n]Restores 200HP to an[n]ally.[n][e]

[msg skill_124]
[s]Item[n]Restores 25% of an[n]ally's max HP.[n][e]

[msg skill_125]
[s]Item[n]Fully restores an[n]ally's HP.[n][e]

[msg skill_126]
[s]Item[n]Restore 50HP of all[n]allies.[n][e]

[msg skill_127]
[s]Item[n]Restores 100HP of all[n]allies.[n][e]

[msg skill_128]
[s]Item[n]Restores 200HP of all[n]allies.[n][e]

[msg skill_129]
[s]Item[n]Fully restores party's[n]HP.[n][e]

[msg skill_12A]
[s]Item[n]Restores 10SP to an[n]ally.[n][e]

[msg skill_12B]
[s]Item[n]Restores 50SP to an[n]ally.[n][e]

[msg skill_12C]
[s]Item[n]Restores 100SP to an[n]ally.[n][e]

[msg skill_12D]
[s]Item[n]Restores all of an[n]ally's SP.[n][e]

[msg skill_12E]
[s]Skill12E[n][e]

[msg skill_12F]
[s]Skill12F[n][e]

[msg skill_130]
[s]Skill130[n][e]

[msg skill_131]
[s]Skill131[n][e]

[msg skill_132]
[s]Skill132[n][e]

[msg skill_133]
[s]Skill133[n][e]

[msg skill_134]
[s]Skill134[n][e]

[msg skill_135]
[s]Skill135[n][e]

[msg skill_136]
[s]Skill136[n][e]

[msg skill_137]
[s]Skill137[n][e]

[msg skill_138]
[s]Skill138[n][e]

[msg skill_139]
[s]Skill139[n][e]

[msg skill_13A]
[s]Skill13A[n][e]

[msg skill_13B]
[s]Skill13B[n][e]

[msg skill_13C]
[s]Skill13C[n][e]

[msg skill_13D]
[s]Skill13D[n][e]

[msg skill_13E]
[s]Skill13D[n][e]

[msg skill_13F]
[s]Skill13F[n][e]

[msg skill_140]
[s]Skill140[n][e]

[msg skill_141]
[s]Skill141[n][e]

[msg skill_142]
[s]Skill142[n][e]

[msg skill_143]
[s]Skill143[n][e]

[msg skill_144]
[s]Skill144[n][e]

[msg skill_145]
[s]Skill145[n][e]

[msg skill_146]
[s]Skill146[n][e]

[msg skill_147]
[s]Skill147[n][e]

[msg skill_148]
[s]Skill148[n][e]

[msg skill_149]
[s]Skill149[n][e]

[msg skill_14A]
[s]Skill14A[n][e]

[msg skill_14B]
[s]Skill14B[n][e]

[msg skill_14C]
[s]Skill14C[n][e]

[msg skill_14D]
[s]Skill14D[n][e]

[msg skill_14E]
[s]Skill14E[n][e]

[msg skill_14F]
[s]Skill14F[n][e]

[msg skill_150]
[s]Skill150[n][e]

[msg skill_151]
[s]Skill151[n][e]

[msg skill_152]
[s]Skill152[n][e]

[msg skill_153]
[s]Skill153[n][e]

[msg skill_154]
[s]Skill154[n][e]

[msg skill_155]
[s]Skill155[n][e]

[msg skill_156]
[s]Skill156[n][e]

[msg skill_157]
[s]Skill157[n][e]

[msg skill_158]
[s]Skill158[n][e]

[msg skill_159]
[s]Skill159[n][e]

[msg skill_15A]
[s]Skill15A[n][e]

[msg skill_15B]
[s]Skill15B[n][e]

[msg skill_15C]
[s]Skill15C[n][e]

[msg skill_15D]
[s]Skill15D[n][e]

[msg skill_15E]
[s]Skill15E[n][e]

[msg skill_15F]
[s]Skill15F[n][e]

[msg skill_160]
[s]Wind damage to 1 foe.[n][e]

[msg skill_161]
[s]Phys damage to 1 foe.[n][e]

[msg skill_162]
[s]Fire damage to all foes.[n][e]

[msg skill_163]
[s]Severely damages foes[n]who are Feared.[n][e]

[msg skill_164]
[s]Summon the prince.[n][e]

[msg skill_165]
[s]Fails to summon the[n]prince.[n][e]

[msg skill_166]
[s]Inflict Poison on male[n]enemies.[n][e]

[msg skill_167]
[s]Inflict Rage on female[n]enemies.[n][e]

[msg skill_168]
[s]Elec damage to all foes.[n][e]

[msg skill_169]
[s]Analyze all foes.[n][e]

[msg skill_16A]
[s]Damages and knocks down[n]standing foes. Kills[n]foes that are Dizzy.[n][e]

[msg skill_16B]
[s]Charge power before[n]unleashing Evil Hand[n]Nihil.[n][e]

[msg skill_16C]
[s]Damage/Dizzy to 1 foe.[n][e]

[msg skill_16D]
[s]Phys damage to 1 foe[n](normal).[n][e]

[msg skill_16E]
[s]Barrier assembly[n]stage 1.[n][e]

[msg skill_16F]
[s]Barrier assembly[n]stage 2.[n][e]

[msg skill_170]
[s]Barrier assembly stage 3.[n][e]

[msg skill_171]
[s]Barrier assembly skill[n]for appearance effect.[n][e]

[msg skill_172]
[s]Phys damage to 1 foe.[n][e]

[msg skill_173]
[s]Almighty damage to[n]1 foe.[n][e]

[msg skill_174]
[s]Almighty damage to all[n]foes (1 Morale Icons)[n][e]

[msg skill_175]
[s]Almighty damage to all[n]foes (2 Morale Icons)[n][e]

[msg skill_176]
[s]Almighty damage to all[n]foes (3 Morale Icons)[n][e]

[msg skill_177]
[s]Almighty damage to all[n]foes (4 Morale Icons)[n][e]

[msg skill_178]
[s]Sets all resistant or[n]higher affinities to[n]normal.[n][e]

[msg skill_179]
[s]Guaranteed Phys damage/[n]Silences 1 foe.[n][e]

[msg skill_17A]
[s]Change element[n]resistances in battle.[n][e]

[msg skill_17B]
[s]Control one player unit.[n][e]

[msg skill_17C]
[s]Heavy Almighty damage to[n]all foes.[n][e]

[msg skill_17D]
[s]Heavy Almighty damage to[n]all foes.[n][e]

[msg skill_17E]
[s]Deals Almighty damage to[n]all foes with a chance[n]of Dizzying.[n][e]

[msg skill_17F]
[s]Ame No Sagiri becomes[n]invincible. Inflicts[n]random effects.[n][e]

[msg skill_180]
[s]End Mist of Confusion.[n][e]

[msg skill_181]
[s]Instantly kills units[n]with ailments, including[n]Down/Dizzy.[n][e]

[msg skill_182]
[s]Deals heavy Almighty[n]damage to all foes,[n]inflicts Enervation.[n][e]

[msg skill_183]
[s]Guaranteed Fear to 1 foe.[n][e]

[msg skill_184]
[s]Control 3 player units.[n][e]

[msg skill_185]
[s]Izanami normal attack.[n][e]

[msg skill_186]
[s]Skill186[n][e]

[msg skill_187]
[s]Skill187[n][e]

[msg skill_188]
[s]Skill188[n][e]

[msg skill_189]
[s]Skill189[n][e]

[msg skill_18A]
[s]Skill18A[n][e]

[msg skill_18B]
[s]Skill18B[n][e]

[msg skill_18C]
[s]Skill18C[n][e]

[msg skill_18D]
[s]Skill18D[n][e]

[msg skill_18E]
[s]Skill18E[n][e]

[msg skill_18F]
[s]Skill18F[n][e]

[msg skill_190]
[s]Skill190[n][e]

[msg skill_191]
[s]Skill191[n][e]

[msg skill_192]
[s]Skill192[n][e]

[msg skill_193]
[s]Skill193[n][e]

[msg skill_194]
[s]Skill194[n][e]

[msg skill_195]
[s]Skill195[n][e]

[msg skill_196]
[s]Skill196[n][e]

[msg skill_197]
[s]Skill197[n][e]

[msg skill_198]
[s]Skill198[n][e]

[msg skill_199]
[s]Skill199[n][e]

[msg skill_19A]
[s]Skill19A[n][e]

[msg skill_19B]
[s]Skill19B[n][e]

[msg skill_19C]
[s]Skill19C[n][e]

[msg skill_19D]
[s]Skill19D[n][e]

[msg skill_19E]
[s]Skill19E[n][e]

[msg skill_19F]
[s]Skill19F[n][e]

[msg skill_1A0]
[s]Skill1A0[n][e]

[msg skill_1A1]
[s]Skill1A1[n][e]

[msg skill_1A2]
[s]Skill1A2[n][e]

[msg skill_1A3]
[s]Skill1A3[n][e]

[msg skill_1A4]
[s]Skill1A4[n][e]

[msg skill_1A5]
[s]Skill1A5[n][e]

[msg skill_1A6]
[s]Skill1A6[n][e]

[msg skill_1A7]
[s]Skill1A7[n][e]

[msg skill_1A8]
[s]Skill1A8[n][e]

[msg skill_1A9]
[s]Skill1A9[n][e]

[msg skill_1AA]
[s]Skill1AA[n][e]

[msg skill_1AB]
[s]Skill1AB[n][e]

[msg skill_1AC]
[s]Skill1AC[n][e]

[msg skill_1AD]
[s]Skill1AD[n][e]

[msg skill_1AE]
[s]Skill1AE[n][e]

[msg skill_1AF]
[s]Skill1AF[n][e]

[msg skill_1B0]
[s]Skill1B0[n][e]

[msg skill_1B1]
[s]Skill1B1[n][e]

[msg skill_1B2]
[s]Skill1B2[n][e]

[msg skill_1B3]
[s]Skill1B3[n][e]

[msg skill_1B4]
[s]Skill1B4[n][e]

[msg skill_1B5]
[s]Skill1B5[n][e]

[msg skill_1B6]
[s]Skill1B6[n][e]

[msg skill_1B7]
[s]Skill1B7[n][e]

[msg skill_1B8]
[s]Skill1B8[n][e]

[msg skill_1B9]
[s]Skill1B9[n][e]

[msg skill_1BA]
[s]Skill1BA[n][e]

[msg skill_1BB]
[s]Skill1BB[n][e]

[msg skill_1BC]
[s]Skill1BC[n][e]

[msg skill_1BD]
[s]Skill1BD[n][e]

[msg skill_1BE]
[s]Skill1BE[n][e]

[msg skill_1BF]
[s]Skill1BF[n][e]

[msg skill_1C0]
[s]Skill1C0[n][e]

[msg skill_1C1]
[s]Skill1C1[n][e]

[msg skill_1C2]
[s]Skill1C2[n][e]

[msg skill_1C3]
[s]Skill1C3[n][e]

[msg skill_1C4]
[s]Skill1C4[n][e]

[msg skill_1C5]
[s]Skill1C5[n][e]

[msg skill_1C6]
[s]Skill1C6[n][e]

[msg skill_1C7]
[s]Skill1C7[n][e]

[msg skill_1C8]
[s]Skill1C8[n][e]

[msg skill_1C9]
[s]Skill1C9[n][e]

[msg skill_1CA]
[s]Skill1CA[n][e]

[msg skill_1CB]
[s]Skill1CB[n][e]

[msg skill_1CC]
[s]Skill1CC[n][e]

[msg skill_1CD]
[s]Skill1CD[n][e]

[msg skill_1CE]
[s]Skill1CE[n][e]

[msg skill_1CF]
[s]Skill1CF[n][e]

[msg skill_1D0]
[s]Skill1D0[n][e]

[msg skill_1D1]
[s]Skill1D1[n][e]

[msg skill_1D2]
[s]Skill1D2[n][e]

[msg skill_1D3]
[s]Skill1D3[n][e]

[msg skill_1D4]
[s]Skill1D4[n][e]

[msg skill_1D5]
[s]Skill1D5[n][e]

[msg skill_1D6]
[s]Skill1D6[n][e]

[msg skill_1D7]
[s]Skill1D7[n][e]

[msg skill_1D8]
[s]Reduces damage from[n]Phys attacks.[n][e]

[msg skill_1D9]
[s]Nullifies damage from[n]Phys attacks.[n][e]

[msg skill_1DA]
[s]Reflects damage from[n]Phys attacks.[n][e]

[msg skill_1DB]
[s]Absorbs damage from[n]Phys attacks.[n][e]

[msg skill_1DC]
[s]Reduces damage from[n]Fire attacks.[n][e]

[msg skill_1DD]
[s]Nullifies damage from[n]Fire attacks.[n][e]

[msg skill_1DE]
[s]Reflects damage from[n]Fire attacks.[n][e]

[msg skill_1DF]
[s]Absorbs damage from[n]Fire attacks.[n][e]

[msg skill_1E0]
[s]Reduces damage from[n]Ice attacks.[n][e]

[msg skill_1E1]
[s]Nullifies damage from[n]Ice attacks.[n][e]

[msg skill_1E2]
[s]Reflects damage from[n]Ice attacks.[n][e]

[msg skill_1E3]
[s]Absorbs damage from[n]Ice attacks.[n][e]

[msg skill_1E4]
[s]Reduces damage from[n]Elec attacks.[n][e]

[msg skill_1E5]
[s]Nullifies damage from[n]Elec attacks.[n][e]

[msg skill_1E6]
[s]Reflects damage from[n]Elec attacks.[n][e]

[msg skill_1E7]
[s]Absorbs damage from[n]Elec attacks.[n][e]

[msg skill_1E8]
[s]Reduces damage from[n]Wind attacks.[n][e]

[msg skill_1E9]
[s]Nullifies damage from[n]Wind attacks.[n][e]

[msg skill_1EA]
[s]Reflects damage from[n]Wind attacks.[n][e]

[msg skill_1EB]
[s]Absorbs damage from[n]Wind attacks.[n][e]

[msg skill_1EC]
[s]Reduces chance of KO[n]from Light attacks.[n][e]

[msg skill_1ED]
[s]Nullifies Light attacks.[n][e]

[msg skill_1EE]
[s]Reflects Light attacks.[n][e]

[msg skill_1EF]
[s]Reduces chance of KO[n]from Darkness attacks.[n][e]

[msg skill_1F0]
[s]Nullifies Darkness[n]attacks.[n][e]

[msg skill_1F1]
[s]Reflects Darkness[n]attacks.[n][e]

[msg skill_1F2]
[s]Protects user from[n]Panic.[n][e]

[msg skill_1F3]
[s]Protects user from[n]Exhaustion.[n][e]

[msg skill_1F4]
[s]Protects user from[n]Silence.[n][e]

[msg skill_1F5]
[s]Protects user from[n]Fear.[n][e]

[msg skill_1F6]
[s]Protects user from[n]Rage.[n][e]

[msg skill_1F7]
[s]Protects user from[n]Poison.[n][e]

[msg skill_1F8]
[s]Protects user from[n]Dizzy.[n][e]

[msg skill_1F9]
[s]Protects user from[n]Enervation.[n][e]

[msg skill_1FA]
[s]Protects user from[n]Panic/Fear/Silence/[n]Enervation/Rage.[n][e]

[msg skill_1FB]
[s]Nullifies all attacks[n]but Almighty.[n][e]

[msg skill_1FC]
[s]Doubles evasion rate[n]against Phys attacks.[n][e]

[msg skill_1FD]
[s]Triples evasion rate[n]against Phys attacks.[n][e]

[msg skill_1FE]
[s]Doubles evasion rate[n]against Fire attacks.[n][e]

[msg skill_1FF]
[s]Triples evasion rate[n]against Fire attacks.[n][e]

[msg skill_200]
[s]Doubles evasion rate[n]against Ice attacks.[n][e]

[msg skill_201]
[s]Triples evasion rate[n]against Ice attacks.[n][e]

[msg skill_202]
[s]Doubles evasion rate[n]against Wind attacks.[n][e]

[msg skill_203]
[s]Triples evasion rate[n]against Wind attacks.[n][e]

[msg skill_204]
[s]Doubles evasion rate[n]against Elec attacks.[n][e]

[msg skill_205]
[s]Triples evasion rate[n]against Elec attacks.[n][e]

[msg skill_206]
[s]Doubles evasion rate[n]against all attacks but[n]Light/Darkness/Almighty.[n][e]

[msg skill_207]
[s]Strengthens Fire[n]attacks by 25%.[n][e]

[msg skill_208]
[s]Strengthens Fire[n]attacks by 50%.[n][e]

[msg skill_209]
[s]Strengthens Ice[n]attacks by 25%.[n][e]

[msg skill_20A]
[s]Strengthens Ice[n]attacks by 50%.[n][e]

[msg skill_20B]
[s]Strengthens Elec[n]attacks by 25%.[n][e]

[msg skill_20C]
[s]Strengthens Elec[n]attacks by 50%.[n][e]

[msg skill_20D]
[s]Strengthens Wind[n]attacks by 25%.[n][e]

[msg skill_20E]
[s]Strengthens Wind[n]attacks by 50%.[n][e]

[msg skill_20F]
[s]Allows you to escape[n]from almost all battles.[n][e]

[msg skill_210]
[s]Increases max HP by 10%.[n][e]

[msg skill_211]
[s]Increases max HP by 20%.[n][e]

[msg skill_212]
[s]Increases max HP by 30%.[n][e]

[msg skill_213]
[s]Increases max SP by 10%.[n][e]

[msg skill_214]
[s]Increases max SP by 20%.[n][e]

[msg skill_215]
[s]Increases max SP by 30%.[n][e]

[msg skill_216]
[s]10% chance of reflecting[n]Phys attacks.[n][e]

[msg skill_217]
[s]15% chance of reflecting[n]Phys attacks.[n][e]

[msg skill_218]
[s]20% chance of reflecting[n]Phys attacks.[n][e]

[msg skill_219]
[s]Restores 2% of max HP[n]each turn in battle.[n][e]

[msg skill_21A]
[s]Restores 4% of max HP[n]each turn in battle.[n][e]

[msg skill_21B]
[s]Restores 6% of max HP[n]each turn in battle.[n][e]

[msg skill_21C]
[s]Restores 3 SP[n]each turn in battle.[n][e]

[msg skill_21D]
[s]Restores 5 SP[n]each turn in battle.[n][e]

[msg skill_21E]
[s]Restores 7 SP[n]each turn in battle.[n][e]

[msg skill_21F]
[s]Persona gains 1/4 EXP[n]while inactive.[n][e]

[msg skill_220]
[s]Persona gains 1/2 EXP[n]while inactive.[n][e]

[msg skill_221]
[s]Persona gains full EXP[n]while inactive.[n][e]

[msg skill_222]
[s]Automatic Tarukaja at[n]the start of battle.[n][e]

[msg skill_223]
[s]Automatic Rakukaja at[n]the start of battle.[n][e]

[msg skill_224]
[s]Automatic Sukukaja at[n]the start of battle.[n][e]

[msg skill_225]
[s]Lowers odds of being[n]taken by surprise.[n][e]

[msg skill_226]
[s]Lowers odds of[n]sustaining crit dmg.[n][e]

[msg skill_227]
[s]Increases user's[n]Critical Rate.[n][e]

[msg skill_228]
[s]The Hit rate of an[n]attacking unit is[n]reduced by half.[n][e]

[msg skill_229]
[s]Always take half damage,[n]but you can never evade.[n][e]

[msg skill_22A]
[s]Halves SP cost for[n]magic skills.[n][e]

[msg skill_22B]
[s]Halves HP cost for[n]physical skills.[n][e]

[msg skill_22C]
[s]Max HP doubles,[n]max SP halves.[n][e]

[msg skill_22D]
[s]Max SP doubles,[n]max HP halves.[n][e]

[msg skill_22E]
[s]Effects of healing magic[n]are increased by 50%.[n][e]

[msg skill_22F]
[s]Restores 1 HP upon[n]Unconscious 1x per[n]battle.[n][e]

[msg skill_230]
[s]Restores all HP upon[n]Unconscious 1x per[n]battle.[n][e]

[msg skill_231]
[s]50% chance of being[n]revived with 1 HP if[n]killed by Light.[n][e]

[msg skill_232]
[s]50% chance of being[n]revived with 1 HP if[n]killed by Darkness.[n][e]

[msg skill_233]
[s]Automatic Marakukaja[n]at start of battle.[n][e]

[msg skill_234]
[s]Automatic Matarukaja[n]at start of battle.[n][e]

[msg skill_235]
[s]Automatic Masukukaja[n]at start of battle.[n][e]

[msg skill_236]
[s]Increases odds of[n]inflicting Panic.[n][e]

[msg skill_237]
[s]Increases odds of[n]inflicting Poison.[n][e]

[msg skill_238]
[s]Increases odds of[n]inflicting Exhaustion.[n][e]

[msg skill_239]
[s]Increases odds of[n]inflicting Silence.[n][e]

[msg skill_23A]
[s]Increases odds of[n]inflicting Fear.[n][e]

[msg skill_23B]
[s]Increases odds of[n]inflicting Rage.[n][e]

[msg skill_23C]
[s]Increases odds of[n]inflicting Dizziness[n]during a Knockdown.[n][e]

[msg skill_23D]
[s]Increases odds of[n]inflicting Enervation.[n][e]

[msg skill_23E]
[s]Increases odds of[n]inflicting any ailment.[n][e]

[msg skill_23F]
[s]Increases success rate[n]of Light magic.[n][e]

[msg skill_240]
[s]Increases success rate[n]of Darkness magic.[n][e]

[msg skill_241]
[s]Automatic revival with[n]1 HP when killed by[n]Light magic.[n][e]

[msg skill_242]
[s]Automatic revival with[n]1 HP when killed by[n]Darkness magic.[n][e]

[msg skill_243]
[s]Restores 8% of HP[n]and SP after battle.[n][e]

[msg skill_244]
[s]Fully restores HP and[n]SP after battle.[n][e]

[msg skill_245]
[s]Reduces chance of being[n]Poisoned.[n][e]

[msg skill_246]
[s]Reduces chance of being[n]Panicked.[n][e]

[msg skill_247]
[s]Reduces chance of being[n]Feared.[n][e]

[msg skill_248]
[s]Reduces chance of being[n]Exhausted.[n][e]

[msg skill_249]
[s]Reduces chance of being[n]Enervated.[n][e]

[msg skill_24A]
[s]Reduces chance of being[n]Enraged.[n][e]

[msg skill_24B]
[s]Reduces chance of being[n]Dizzy.[n][e]

[msg skill_24C]
[s]Reduces chance of being[n]Silenced.[n][e]

[msg skill_24D]
[s]Increases max HP by 50%.[n][e]

[msg skill_24E]
[s]Increases max SP by 50%.[n][e]

[msg skill_24F]
[s]Time needed to recover[n]from ailments is halved.[n][e]

[msg skill_250]
[s]Time needed to recover[n]from ailments is reduced[n]to 1 turn.[n][e]

[msg skill_251]
[s]Skill251[n][e]

[msg skill_252]
[s]Skill252[n][e]

[msg skill_253]
[s]Skill253[n][e]

[msg skill_254]
[s]Skill254[n][e]

[msg skill_255]
[s]Skill255[n][e]

[msg skill_256]
[s]Skill256[n][e]

[msg skill_257]
[s]Skill257[n][e]

[msg skill_258]
[s]Skill258[n][e]

[msg skill_259]
[s]Skill259[n][e]

[msg skill_25A]
[s]Skill25A[n][e]

[msg skill_25B]
[s]Skill25B[n][e]

[msg skill_25C]
[s]Skill25C[n][e]

[msg skill_25D]
[s]Skill25D[n][e]

[msg skill_25E]
[s]Skill25E[n][e]

[msg skill_25F]
[s]Skill25F[n][e]

