[msg skill_card_000]
[s]ブランク[n][e]

[msg skill_card_001]
[s]Skill Card that bestows[n]Agi.[n][e]

[msg skill_card_002]
[s]Skill Card that bestows[n]Agilao.[n][e]

[msg skill_card_003]
[s]Skill Card that bestows[n]Agidyne.[n][e]

[msg skill_card_004]
[s]Skill Card that bestows[n]Maragi.[n][e]

[msg skill_card_005]
[s]Skill Card that bestows[n]Maragion.[n][e]

[msg skill_card_006]
[s]Skill Card that bestows[n]Maragidyne.[n][e]

[msg skill_card_007]
[s]Skill Card that bestows[n]Garu.[n][e]

[msg skill_card_008]
[s]Skill Card that bestows[n]Garula.[n][e]

[msg skill_card_009]
[s]Skill Card that bestows[n]Garudyne.[n][e]

[msg skill_card_00A]
[s]Skill Card that bestows[n]Magaru.[n][e]

[msg skill_card_00B]
[s]Skill Card that bestows[n]Magarula.[n][e]

[msg skill_card_00C]
[s]Skill Card that bestows[n]Magarudyne.[n][e]

[msg skill_card_00D]
[s]Skill Card that bestows[n]Bufu.[n][e]

[msg skill_card_00E]
[s]Skill Card that bestows[n]Bufula.[n][e]

[msg skill_card_00F]
[s]Skill Card that bestows[n]Bufudyne.[n][e]

[msg skill_card_010]
[s]Skill Card that bestows[n]Mabufu.[n][e]

[msg skill_card_011]
[s]Skill Card that bestows[n]Mabufula.[n][e]

[msg skill_card_012]
[s]Skill Card that bestows[n]Mabufudyne.[n][e]

[msg skill_card_013]
[s]Skill Card that bestows[n]Zio.[n][e]

[msg skill_card_014]
[s]Skill Card that bestows[n]Zionga.[n][e]

[msg skill_card_015]
[s]Skill Card that bestows[n]Ziodyne.[n][e]

[msg skill_card_016]
[s]Skill Card that bestows[n]Mazio.[n][e]

[msg skill_card_017]
[s]Skill Card that bestows[n]Mazionga.[n][e]

[msg skill_card_018]
[s]Skill Card that bestows[n]Maziodyne.[n][e]

[msg skill_card_019]
[s]Skill Card that bestows[n]Megido.[n][e]

[msg skill_card_01A]
[s]Skill Card that bestows[n]Megidola.[n][e]

[msg skill_card_01B]
[s]Skill Card that bestows[n]Megidolaon.[n][e]

[msg skill_card_01C]
[s]Skill Card that bestows[n]Hama.[n][e]

[msg skill_card_01D]
[s]Skill Card that bestows[n]Hamaon.[n][e]

[msg skill_card_01E]
[s]Skill Card that bestows[n]Mahama.[n][e]

[msg skill_card_01F]
[s]Skill Card that bestows[n]Mahamaon.[n][e]

[msg skill_card_020]
[s]Skill Card that bestows[n]Mudo.[n][e]

[msg skill_card_021]
[s]Skill Card that bestows[n]Mudoon.[n][e]

[msg skill_card_022]
[s]Skill Card that bestows[n]Mamudo.[n][e]

[msg skill_card_023]
[s]Skill Card that bestows[n]Mamudoon.[n][e]

[msg skill_card_024]
[s]Skill Card that bestows[n]Pulinpa.[n][e]

[msg skill_card_025]
[s]Skill Card that bestows[n]Tentarafoo.[n][e]

[msg skill_card_026]
[s]Skill Card that bestows[n]Evil Touch.[n][e]

[msg skill_card_027]
[s]Skill Card that bestows[n]Evil Smile.[n][e]

[msg skill_card_028]
[s]Skill Card that bestows[n]Ghastly Wail.[n][e]

[msg skill_card_029]
[s]Skill Card that bestows[n]Balzac.[n][e]

[msg skill_card_02A]
[s]Skill Card that bestows[n]Valiant Dance.[n][e]

[msg skill_card_02B]
[s]Skill Card that bestows[n]Poisma.[n][e]

[msg skill_card_02C]
[s]Skill Card that bestows[n]Poison Mist.[n][e]

[msg skill_card_02D]
[s]Skill Card that bestows[n]Soul Break.[n][e]

[msg skill_card_02E]
[s]Skill Card that bestows[n]Anima Freeze.[n][e]

[msg skill_card_02F]
[s]Skill Card that bestows[n]Enervation.[n][e]

[msg skill_card_030]
[s]Skill Card that bestows[n]Old One.[n][e]

[msg skill_card_031]
[s]Skill Card that bestows[n]Galgalim Eyes.[n][e]

[msg skill_card_032]
[s]Skill Card that bestows[n]Makajam.[n][e]

[msg skill_card_033]
[s]Skill Card that bestows[n]Foolish Whisper.[n][e]

[msg skill_card_034]
[s]Skill Card that bestows[n]Foul Breath.[n][e]

[msg skill_card_035]
[s]Skill Card that bestows[n]Stagnant Air.[n][e]

[msg skill_card_036]
[s]Skill Card that bestows[n]Life Drain.[n][e]

[msg skill_card_037]
[s]Skill Card that bestows[n]Spirit Drain.[n][e]

[msg skill_card_038]
[s]Skill Card that bestows[n]Assault Dive.[n][e]

[msg skill_card_039]
[s]Skill Card that bestows[n]Sonic Punch.[n][e]

[msg skill_card_03A]
[s]Skill Card that bestows[n]Double Fangs.[n][e]

[msg skill_card_03B]
[s]Skill Card that bestows[n]Kill Rush.[n][e]

[msg skill_card_03C]
[s]Skill Card that bestows[n]Swift Strike.[n][e]

[msg skill_card_03D]
[s]Skill Card that bestows[n]Twin Shot.[n][e]

[msg skill_card_03E]
[s]Skill Card that bestows[n]Fatal End.[n][e]

[msg skill_card_03F]
[s]Skill Card that bestows[n]Mighty Swing.[n][e]

[msg skill_card_040]
[s]Skill Card that bestows[n]Torrent Shot.[n][e]

[msg skill_card_041]
[s]Skill Card that bestows[n]Heat Wave.[n][e]

[msg skill_card_042]
[s]Skill Card that bestows[n]Gigantic Fist.[n][e]

[msg skill_card_043]
[s]Skill Card that bestows[n]Blade of Fury.[n][e]

[msg skill_card_044]
[s]Skill Card that bestows[n]Deathbound.[n][e]

[msg skill_card_045]
[s]Skill Card that bestows[n]Arrow Rain.[n][e]

[msg skill_card_046]
[s]Skill Card that bestows[n]Akasha Arts.[n][e]

[msg skill_card_047]
[s]Skill Card that bestows[n]Tempest Slash.[n][e]

[msg skill_card_048]
[s]Skill Card that bestows[n]Heaven's Blade.[n][e]

[msg skill_card_049]
[s]Skill Card that bestows[n]Myriad Arrows.[n][e]

[msg skill_card_04A]
[s]Skill Card that bestows[n]God's Hand.[n][e]

[msg skill_card_04B]
[s]Skill Card that bestows[n]Pralaya.[n][e]

[msg skill_card_04C]
[s]Skill Card that bestows[n]Primal Force.[n][e]

[msg skill_card_04D]
[s]Skill Card that bestows[n]Vorpal Blade.[n][e]

[msg skill_card_04E]
[s]Skill Card that bestows[n]Power Slash.[n][e]

[msg skill_card_04F]
[s]Skill Card that bestows[n]Gale Slash.[n][e]

[msg skill_card_050]
[s]Skill Card that bestows[n]Brave Blade.[n][e]

[msg skill_card_051]
[s]Skill Card that bestows[n]Herculean Strike.[n][e]

[msg skill_card_052]
[s]Skill Card that bestows[n]Vicious Strike.[n][e]

[msg skill_card_053]
[s]Skill Card that bestows[n]Poison Skewer.[n][e]

[msg skill_card_054]
[s]Skill Card that bestows[n]Poison Arrow.[n][e]

[msg skill_card_055]
[s]Skill Card that bestows[n]Blight.[n][e]

[msg skill_card_056]
[s]Skill Card that bestows[n]Virus Wave.[n][e]

[msg skill_card_057]
[s]Skill Card that bestows[n]Skull Cracker.[n][e]

[msg skill_card_058]
[s]Skill Card that bestows[n]Mind Slice.[n][e]

[msg skill_card_059]
[s]Skill Card that bestows[n]Hysterical Slap.[n][e]

[msg skill_card_05A]
[s]Skill Card that bestows[n]Crazy Chain.[n][e]

[msg skill_card_05B]
[s]Skill Card that bestows[n]Muzzle Shot.[n][e]

[msg skill_card_05C]
[s]Skill Card that bestows[n]Seal Bomb.[n][e]

[msg skill_card_05D]
[s]Skill Card that bestows[n]Arm Chopper.[n][e]

[msg skill_card_05E]
[s]Skill Card that bestows[n]Atom Smasher.[n][e]

[msg skill_card_05F]
[s]Skill Card that bestows[n]Cell Breaker.[n][e]

[msg skill_card_060]
[s]Skill Card that bestows[n]Mustard Bomb.[n][e]

[msg skill_card_061]
[s]Skill Card that bestows[n]Brain Shake.[n][e]

[msg skill_card_062]
[s]Skill Card that bestows[n]Navas Nebula.[n][e]

[msg skill_card_063]
[s]Skill Card that bestows[n]Black Spot.[n][e]

[msg skill_card_064]
[s]Skill Card that bestows[n]Rainy Death.[n][e]

[msg skill_card_065]
[s]Skill Card that bestows[n]Rampage.[n][e]

[msg skill_card_066]
[s]Skill Card that bestows[n]Aeon Rain.[n][e]

[msg skill_card_067]
[s]Skill Card that bestows[n]Agneyastra.[n][e]

[msg skill_card_068]
[s]Skill Card that bestows[n]Cruel Attack.[n][e]

[msg skill_card_069]
[s]Skill Card that bestows[n]Vile Assault.[n][e]

[msg skill_card_06A]
[s]Skill Card that bestows[n]Dia.[n][e]

[msg skill_card_06B]
[s]Skill Card that bestows[n]Diarama.[n][e]

[msg skill_card_06C]
[s]Skill Card that bestows[n]Diarahan.[n][e]

[msg skill_card_06D]
[s]Skill Card that bestows[n]Media.[n][e]

[msg skill_card_06E]
[s]Skill Card that bestows[n]Mediarama.[n][e]

[msg skill_card_06F]
[s]Skill Card that bestows[n]Mediarahan.[n][e]

[msg skill_card_070]
[s]Skill Card that bestows[n]Salvation.[n][e]

[msg skill_card_071]
[s]Skill Card that bestows[n]Amrita.[n][e]

[msg skill_card_072]
[s]Skill Card that bestows[n]Recarm.[n][e]

[msg skill_card_073]
[s]Skill Card that bestows[n]Samarecarm.[n][e]

[msg skill_card_074]
[s]Skill Card that bestows[n]Tarunda.[n][e]

[msg skill_card_075]
[s]Skill Card that bestows[n]Matarunda.[n][e]

[msg skill_card_076]
[s]Skill Card that bestows[n]Sukunda.[n][e]

[msg skill_card_077]
[s]Skill Card that bestows[n]Masukunda.[n][e]

[msg skill_card_078]
[s]Skill Card that bestows[n]Rakunda.[n][e]

[msg skill_card_079]
[s]Skill Card that bestows[n]Marakunda.[n][e]

[msg skill_card_07A]
[s]Skill Card that bestows[n]Dekunda.[n][e]

[msg skill_card_07B]
[s]Skill Card that bestows[n]Tarukaja.[n][e]

[msg skill_card_07C]
[s]Skill Card that bestows[n]Matarukaja.[n][e]

[msg skill_card_07D]
[s]Skill Card that bestows[n]Sukukaja.[n][e]

[msg skill_card_07E]
[s]Skill Card that bestows[n]Masukukaja.[n][e]

[msg skill_card_07F]
[s]Skill Card that bestows[n]Rakukaja.[n][e]

[msg skill_card_080]
[s]Skill Card that bestows[n]Marakukaja.[n][e]

[msg skill_card_081]
[s]Skill Card that bestows[n]Dekaja.[n][e]

[msg skill_card_082]
[s]Skill Card that bestows[n]Energy Shower.[n][e]

[msg skill_card_083]
[s]Skill Card that bestows[n]Debilitate.[n][e]

[msg skill_card_084]
[s]Skill Card that bestows[n]Power Charge.[n][e]

[msg skill_card_085]
[s]Skill Card that bestows[n]Mind Charge.[n][e]

[msg skill_card_086]
[s]Skill Card that bestows[n]Tetrakarn.[n][e]

[msg skill_card_087]
[s]Skill Card that bestows[n]Makarakarn.[n][e]

[msg skill_card_088]
[s]Skill Card that bestows[n]Tetra Break.[n][e]

[msg skill_card_089]
[s]Skill Card that bestows[n]Makara Break.[n][e]

[msg skill_card_08A]
[s]Skill Card that bestows[n]Tetraja.[n][e]

[msg skill_card_08B]
[s]Skill Card that bestows[n]Rebellion.[n][e]

[msg skill_card_08C]
[s]Skill Card that bestows[n]Revolution.[n][e]

[msg skill_card_08D]
[s]Skill Card that bestows[n]Fire Break.[n][e]

[msg skill_card_08E]
[s]Skill Card that bestows[n]Ice Break.[n][e]

[msg skill_card_08F]
[s]Skill Card that bestows[n]Wind Break.[n][e]

[msg skill_card_090]
[s]Skill Card that bestows[n]Elec Break.[n][e]

[msg skill_card_091]
[s]Skill Card that bestows[n]Red Wall.[n][e]

[msg skill_card_092]
[s]Skill Card that bestows[n]White Wall.[n][e]

[msg skill_card_093]
[s]Skill Card that bestows[n]Blue Wall.[n][e]

[msg skill_card_094]
[s]Skill Card that bestows[n]Green Wall.[n][e]

[msg skill_card_095]
[s]Skill Card that bestows[n]Trafuri.[n][e]

[msg skill_card_096]
[s]Skill Card that bestows[n]Recarmdra.[n][e]

[msg skill_card_097]
[s]Skill Card that bestows[n]Traesto.[n][e]

[msg skill_card_098]
[s]Skill Card that bestows[n]Resist Physical.[n][e]

[msg skill_card_099]
[s]Skill Card that bestows[n]Absorb Physical.[n][e]

[msg skill_card_09A]
[s]Skill Card that bestows[n]Resist Fire.[n][e]

[msg skill_card_09B]
[s]Skill Card that bestows[n]Absorb Fire.[n][e]

[msg skill_card_09C]
[s]Skill Card that bestows[n]Resist Ice.[n][e]

[msg skill_card_09D]
[s]Skill Card that bestows[n]Absorb Ice.[n][e]

[msg skill_card_09E]
[s]Skill Card that bestows[n]Resist Elec.[n][e]

[msg skill_card_09F]
[s]Skill Card that bestows[n]Absorb Elec.[n][e]

[msg skill_card_0A0]
[s]Skill Card that bestows[n]Resist Wind.[n][e]

[msg skill_card_0A1]
[s]Skill Card that bestows[n]Absorb Wind.[n][e]

[msg skill_card_0A2]
[s]Skill Card that bestows[n]Repel Light.[n][e]

[msg skill_card_0A3]
[s]Skill Card that bestows[n]Repel Dark.[n][e]

[msg skill_card_0A4]
[s]Skill Card that bestows[n]Null Panic.[n][e]

[msg skill_card_0A5]
[s]Skill Card that bestows[n]Null Exhaust.[n][e]

[msg skill_card_0A6]
[s]Skill Card that bestows[n]Null Mute.[n][e]

[msg skill_card_0A7]
[s]Skill Card that bestows[n]Null Fear.[n][e]

[msg skill_card_0A8]
[s]Skill Card that bestows[n]Null Rage.[n][e]

[msg skill_card_0A9]
[s]Skill Card that bestows[n]Null Poison.[n][e]

[msg skill_card_0AA]
[s]Skill Card that bestows[n]Null Dizzy.[n][e]

[msg skill_card_0AB]
[s]Skill Card that bestows[n]Null Enervate.[n][e]

[msg skill_card_0AC]
[s]Skill Card that bestows[n]Unshaken Will.[n][e]

[msg skill_card_0AD]
[s]Skill Card that bestows[n]Dodge Physical.[n][e]

[msg skill_card_0AE]
[s]Skill Card that bestows[n]Evade Physical.[n][e]

[msg skill_card_0AF]
[s]Skill Card that bestows[n]Dodge Fire.[n][e]

[msg skill_card_0B0]
[s]Skill Card that bestows[n]Evade Fire.[n][e]

[msg skill_card_0B1]
[s]Skill Card that bestows[n]Dodge Ice.[n][e]

[msg skill_card_0B2]
[s]Skill Card that bestows[n]Evade Ice.[n][e]

[msg skill_card_0B3]
[s]Skill Card that bestows[n]Dodge Wind.[n][e]

[msg skill_card_0B4]
[s]Skill Card that bestows[n]Evade Wind.[n][e]

[msg skill_card_0B5]
[s]Skill Card that bestows[n]Dodge Elec.[n][e]

[msg skill_card_0B6]
[s]Skill Card that bestows[n]Evade Elec.[n][e]

[msg skill_card_0B7]
[s]Skill Card that bestows[n]Angelic Grace.[n][e]

[msg skill_card_0B8]
[s]Skill Card that bestows[n]Fire Boost.[n][e]

[msg skill_card_0B9]
[s]Skill Card that bestows[n]Fire Amp.[n][e]

[msg skill_card_0BA]
[s]Skill Card that bestows[n]Ice Boost.[n][e]

[msg skill_card_0BB]
[s]Skill Card that bestows[n]Ice Amp.[n][e]

[msg skill_card_0BC]
[s]Skill Card that bestows[n]Elec Boost.[n][e]

[msg skill_card_0BD]
[s]Skill Card that bestows[n]Elec Amp.[n][e]

[msg skill_card_0BE]
[s]Skill Card that bestows[n]Wind Boost.[n][e]

[msg skill_card_0BF]
[s]Skill Card that bestows[n]Wind Amp.[n][e]

[msg skill_card_0C0]
[s]Skill Card that bestows[n]Counter.[n][e]

[msg skill_card_0C1]
[s]Skill Card that bestows[n]Counterstrike.[n][e]

[msg skill_card_0C2]
[s]Skill Card that bestows[n]High Counter.[n][e]

[msg skill_card_0C3]
[s]Skill Card that bestows[n]Regenerate 1.[n][e]

[msg skill_card_0C4]
[s]Skill Card that bestows[n]Regenerate 2.[n][e]

[msg skill_card_0C5]
[s]Skill Card that bestows[n]Regenerate 3.[n][e]

[msg skill_card_0C6]
[s]Skill Card that bestows[n]Invigorate 1.[n][e]

[msg skill_card_0C7]
[s]Skill Card that bestows[n]Invigorate 2.[n][e]

[msg skill_card_0C8]
[s]Skill Card that bestows[n]Invigorate 3.[n][e]

[msg skill_card_0C9]
[s]Skill Card that bestows[n]Growth 1.[n][e]

[msg skill_card_0CA]
[s]Skill Card that bestows[n]Growth 2.[n][e]

[msg skill_card_0CB]
[s]Skill Card that bestows[n]Growth 3.[n][e]

[msg skill_card_0CC]
[s]Skill Card that bestows[n]Auto-Tarukaja.[n][e]

[msg skill_card_0CD]
[s]Skill Card that bestows[n]Auto-Rakukaja.[n][e]

[msg skill_card_0CE]
[s]Skill Card that bestows[n]Auto-Sukukaja.[n][e]

[msg skill_card_0CF]
[s]Skill Card that bestows[n]Alertness.[n][e]

[msg skill_card_0D0]
[s]Skill Card that bestows[n]Sharp Student.[n][e]

[msg skill_card_0D1]
[s]Skill Card that bestows[n]Apt Pupil.[n][e]

[msg skill_card_0D2]
[s]Skill Card that bestows[n]Firm Stance.[n][e]

[msg skill_card_0D3]
[s]Skill Card that bestows[n]Spell Master.[n][e]

[msg skill_card_0D4]
[s]Skill Card that bestows[n]Arms Master.[n][e]

[msg skill_card_0D5]
[s]Skill Card that bestows[n]Divine Grace.[n][e]

[msg skill_card_0D6]
[s]Skill Card that bestows[n]Endure.[n][e]

[msg skill_card_0D7]
[s]Skill Card that bestows[n]Enduring Soul.[n][e]

[msg skill_card_0D8]
[s]Skill Card that bestows[n]Survive Light.[n][e]

[msg skill_card_0D9]
[s]Skill Card that bestows[n]Survive Dark.[n][e]

[msg skill_card_0DA]
[s]Skill Card that bestows[n]Auto-Maraku.[n][e]

[msg skill_card_0DB]
[s]Skill Card that bestows[n]Auto-Mataru.[n][e]

[msg skill_card_0DC]
[s]Skill Card that bestows[n]Auto-Masuku.[n][e]

[msg skill_card_0DD]
[s]Skill Card that bestows[n]Panic Boost.[n][e]

[msg skill_card_0DE]
[s]Skill Card that bestows[n]Poison Boost.[n][e]

[msg skill_card_0DF]
[s]Skill Card that bestows[n]Exhaust Boost.[n][e]

[msg skill_card_0E0]
[s]Skill Card that bestows[n]Silence Boost.[n][e]

[msg skill_card_0E1]
[s]Skill Card that bestows[n]Fear Boost.[n][e]

[msg skill_card_0E2]
[s]Skill Card that bestows[n]Rage Boost.[n][e]

[msg skill_card_0E3]
[s]Skill Card that bestows[n]Dizzy Boost.[n][e]

[msg skill_card_0E4]
[s]Skill Card that bestows[n]Enervate Boost.[n][e]

[msg skill_card_0E5]
[s]Skill Card that bestows[n]Ailment Boost.[n][e]

[msg skill_card_0E6]
[s]Skill Card that bestows[n]Hama Boost.[n][e]

[msg skill_card_0E7]
[s]Skill Card that bestows[n]Mudo Boost.[n][e]

[msg skill_card_0E8]
[s]Skill Card that bestows[n]Endure Light.[n][e]

[msg skill_card_0E9]
[s]Skill Card that bestows[n]Endure Dark.[n][e]

[msg skill_card_0EA]
[s]Skill Card that bestows[n]Cool Breeze.[n][e]

[msg skill_card_0EB]
[s]Skill Card that bestows[n]Victory Cry.[n][e]

[msg skill_card_0EC]
[s]Skill Card that bestows[n]Resist Poison.[n][e]

[msg skill_card_0ED]
[s]Skill Card that bestows[n]Resist Panic.[n][e]

[msg skill_card_0EE]
[s]Skill Card that bestows[n]Resist Fear.[n][e]

[msg skill_card_0EF]
[s]Skill Card that bestows[n]Resist Exhaust.[n][e]

[msg skill_card_0F0]
[s]Skill Card that bestows[n]Resist Enervate.[n][e]

[msg skill_card_0F1]
[s]Skill Card that bestows[n]Resist Rage.[n][e]

[msg skill_card_0F2]
[s]Skill Card that bestows[n]Resist Dizzy.[n][e]

[msg skill_card_0F3]
[s]Skill Card that bestows[n]Resist Mute.[n][e]

[msg skill_card_0F4]
[s]Skill Card that bestows[n]Fast Heal.[n][e]

[msg skill_card_0F5]
[s]Skill Card that bestows[n]Insta-Heal.[n][e]

[msg skill_card_0F6]
[s]Skill Card that bestows[n]Patra.[n][e]

[msg skill_card_0F7]
[s]Skill Card that bestows[n]Me Patra.[n][e]

[msg skill_card_0F8]
[s]Skill Card that bestows[n]Re Patra.[n][e]

[msg skill_card_0F9]
[s]Skill Card that bestows[n]Posumudi.[n][e]

[msg skill_card_0FA]
[s]Skill Card that bestows[n]Mutudi.[n][e]

[msg skill_card_0FB]
[s]Skill Card that bestows[n]Nervundi.[n][e]

[msg skill_card_0FC]
[s]Skill Card that bestows[n]Heat Riser.[n][e]

[msg skill_card_0FD]
[s]Skill Card that bestows[n]Single Shot.[n][e]

[msg skill_card_0FE]
[s]Skill Card. Deals severe fire[n]damage to all foes.[n][e]

[msg skill_card_0FF]
[s]リザーブ[n][e]

