[msg MSG_000 [ ]]
[f 0 5 -258][f 2 1]> Central shopping district...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You decided to walk Rise home after[n]eating at Aiya...[n][f 1 1][e]

[msg MSG_001 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 2 -1 1][f 3 1 1 0 0 341]The flavor was a little strong,[n]but it was good.[n][f 1 1][e]
[f 0 5 -258][f 2 1]My grandma's food is kind of bland.[n]Though tofu is good for you, so...[n][f 1 1][e]

[msg MSG_002 [ ]]
[f 0 5 -258][f 2 1]> There is a suspicious man in front of[n]Rise's house...[n][f 1 1][e]

[msg MSG_003 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 337]Is that a reporter...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]Or... a stalker?[n][f 1 1][e]

[msg MSG_004 [ ]]
[f 0 5 -258][f 2 1]> Rise is worried...[n][f 1 1][e]

[sel SEL_005]
[f 0 5 -258][f 2 1]Yell[e]
[f 0 5 -258][f 2 1]Call the police +2/3[e]
[f 0 5 -258][f 2 1]Grab her hand and run +3/3[e]

[msg MSG_006 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1]...W-Wait, Senpai![n][f 1 1][e]
[f 0 5 -258][f 2 1]We shouldn't cause a scene...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n]> Rise looks troubled...[n][f 1 1][e]

[msg MSG_007 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 1 -1 1]Y-Yeah, go ahead...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 3 5 10]> Rise looks relieved...[n][f 1 1][e]

[msg MSG_008 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 5 -1 1]Uh, th-that's alright. We don't know[n]if he's really dangerous or not.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Let's just wait and see, okay?[n][f 1 1][e]
[f 0 5 -258][f 2 1]But... thanks for that.[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 3 15 10]> Rise no longer seems worried.[n][f 1 1][e]

[msg MSG_009 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1]Hmm, but still... That guy...[n]Where have I...?[n][f 1 1][e]

[msg MSG_010 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 5 -1 1][f 3 1 1 0 0 335]Inoue-san, is that you!?[n][f 1 1][e]

[msg MSG_011 [Inoue]]
[f 0 5 -258][f 2 1][f 4 6 61 2 0 1]Rise-chan![n][f 1 1][e]

[msg MSG_012 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 5 -1 1]Wh-Why are you here...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]I already settled everything with[n]the agency...![n][f 1 1][e]

[msg MSG_013 [Inoue]]
[f 0 5 -258][f 2 1][f 4 6 61 1 0 1]I'm here because... Personally, I can't[n]accept that.[n][f 1 1][e]
[f 0 5 -258][f 2 1]I've watched over you this entire time[n]as your manager...[n][f 1 1][e]

[msg MSG_014 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 3 -1 1]I'm no longer a "personality"![n][f 1 1][e]
[f 0 5 -258][f 2 1]My private time doesn't belong to[n]a manager anymore![n][f 1 1][e]
[f 0 5 -258][f 2 1]Go home. If you don't, I'll call the police.[n][f 1 1][e]

[msg MSG_015 [Inoue]]
[f 0 5 -258][f 2 1][f 4 6 61 6 0 1]W-Wait![n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 61 4 0 1]Could you just think it over? I strongly[n]believe that no other actress can play[n]that role better than Rise Kujikawa.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Your fans were looking forward to[n]the movie, too...[n][f 1 1][e]

[msg MSG_016 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 3 -1 1]You still want me to act...!?[n][f 1 1][e]

[msg MSG_017 [Inoue]]
[f 0 5 -258][f 2 1][f 4 6 61 5 0 1]Huh...?[n][f 1 1][e]

[msg MSG_018 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 3 -1 1]...Anyway, I'm through with it! I have[n]nothing to do with showbiz and all that[n]stuff now![n][f 1 1][e]
[f 0 5 -258][f 2 1]I...[n][f 1 1][e]

[msg MSG_019 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 3 -1 1]I-I've decided to marry this man once[n]we graduate high school![n][f 1 1][e]

[msg MSG_020 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 3 -1 1]I said before it was only a hiatus, but[n]I've changed my mind! There's no way[n]I'm coming back![n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 2] sees the real me...[n][f 1 1][e]
[f 0 5 -258][f 2 1]He's so gentle...![n][f 1 1][e]

[msg MSG_021 [ ]]
[f 0 5 -258][f 2 1]> Rise is desperate...[n][f 1 1][e]

[sel SEL_022]
[f 0 5 -258][f 2 1]Go along with her +3/3[e]
[f 0 5 -258][f 2 1]Deny it[e]

[msg MSG_023 [ ]]
[f 0 5 -258][f 2 1]> You went along with her story...[n][f 1 1][e]

[msg MSG_024 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 2 -1 1]S-See? I told you...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 3 15 10]> Rise looks relieved...[n][f 1 1][e]

[msg MSG_025 [ ]]
[f 0 5 -258][f 2 1]> You denied Rise's story.[n][f 1 1][e]

[msg MSG_026 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 5 -1 1]...H-He's just too shy to admit it![n][f 1 1][e]
[f 0 5 -258][f 2 1]A-And why wouldn't he be? I-It's a big deal[n]to marry Risette![n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n]> Rise is trying to fix her story as[n]her face reddens...[n][f 1 1][e]

[msg MSG_027 [Inoue]]
[f 0 5 -258][f 2 1]......[n][f 1 1][e]
[f 0 5 -258][f 2 1]I understand. I'll go home... for today.[n][f 1 1][e]
[f 0 5 -258][f 2 1]B-But I...[n][f 1 1][e]

[msg MSG_028 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 3 -1 1]Go away! Now![n][f 1 1][e]

[msg MSG_029 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 1 -1 1][f 3 1 1 0 0 318]Oh... U-Ummm...[n][f 1 1][e]
[f 0 5 -258][f 2 1]...That was Inoue-san. He was...[n]my manager.[n][f 1 1][e]
[f 0 5 -258][f 2 1]I'm his daughter's age, so he treated me[n]like one of the family...[n][f 1 1][e]

[msg MSG_030 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1]But... he's a stranger now.[n][f 1 1][e]
[f 0 5 -258][f 2 1]......[n][f 1 1][e]

[msg MSG_031 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1]S-Senpai, umm...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 325]I'm sorry... Lying about marrying you[n]and all...[n][f 1 1][e]

[sel SEL_032]
[f 0 5 -258][f 2 1]"I don't mind." +3/3[e]
[f 0 5 -258][f 2 1]"Lying is wrong."[e]
[f 0 5 -258][f 2 1]"It... It was a lie?" +3/3[e]

[msg MSG_033 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 2 -1 1][f 3 1 1 0 0 323]Senpai...[n][f 1 1][e]
[f 0 5 -258][f 2 1]You're so mature...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 3 15 10]> Rise smiled a smile of relief.[n][f 1 1][e]

[msg MSG_034 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 314]That's... true, but... It was just a little[n]white lie...[n][f 1 1][e]
[f 0 5 -258][f 2 1]Senpai, do you really want me to get[n]dragged back into showbiz...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]Could you solve the murders if I wasn't[n]here? I mean, without me...[n][f 1 1][e]
[f 0 5 -258][f 2 1]......[n][f 1 1][e]
[f 0 5 -258][f 2 1]...N-Never mind.[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n]> Rise looks gloomy...[n][f 1 1][e]

[msg MSG_035 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 5 -1 1][f 3 1 1 0 0 336]Huh...?[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 5 6 -1 1]"Was it a lie?" O-Oh... Senpai...[n][f 1 1][e]
[f 0 5 -258][f 2 1]W-Wow...[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n][f 5 13 3 10 10]> Somewhat at a loss, Rise is smiling[n]sheepishly...[n][f 1 1][e]

[msg MSG_036 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 1 -1 1]You really are a nice guy.[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 5 6 -1 1]Th-This isn't good... I feel like I'm going to[n]depend on you even more...[n][f 1 1][e]

[msg MSG_037 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 2 -1 1][f 3 1 1 0 0 341]...J-Just kidding![n][f 1 1][e]

[msg MSG_038 [ ]]
[f 0 5 -258][f 2 1]> Perhaps due to her relief, Rise is[n]smiling sheepishly...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You feel your relationship with Rise[n]has grown deeper...[n][f 1 1][e]

[msg MSG_039 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 1 -1 1]I wish I could spend more time with you,[n]but... I'll save it for next time.[n][f 1 1][e]
[f 0 5 -258][f 2 1]See you later, Senpai.[n][f 1 1][e]

[msg MSG_040 [ ]]
[f 0 5 -258][f 2 1]> You watched Rise walk in and went home.[n][f 1 1][e]

[msg MSG_KIRI [ ]]
[f 0 5 -258][f 2 1]> Fog has enveloped the area...[n][f 1 1][e]

[msg MSG_042 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 314]That's... true, but... It was just a little[n]white lie...[n][f 1 1][e]
[f 0 5 -258][f 2 1]Senpai, do you really want me to get[n]dragged back into showbiz...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]You're okay with me not being not around...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]......[n][f 1 1][e]
[f 0 5 -258][f 2 1]...N-Never mind.[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 1 5] [n]> Rise looks sad...[n][f 1 1][e]

