[msg MSG_000 [ ]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Souzai Daigaku...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You came with Rise, who seems[n]enthusiastic about eating out...[n][f 1 3 -1][f 1 1][e]

[msg MSG_001 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 1 -1 1][f 3 1 1 0 0 1]What should I have...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 2]Heck, maybe our shop should do something[n]like this.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 3]How about a "ganmo kebab"?[n]Or a "tofu croquette"?[n][f 1 3 -1][f 1 1][e]

[msg MSG_002 [Middle-aged man]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 4]Well, if it isn't Rise-chan.[n][f 1 3 -1][f 1 1][e]

[msg MSG_003 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 1 -1 1][f 3 1 1 0 0 5]Ummm, you're the deputy mayor... right?[n]Good afternoon...[n][f 1 3 -1][f 1 1][e]

[msg MSG_004 [Deputy mayor]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 6]I heard the news! You know, about the[n]upcoming film![n][f 1 3 -1][f 1 1][e]

[msg MSG_005 [Deputy mayor]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 7]...Hm? You haven't heard yet?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 8]You know Kanamin, right? Kanami Mashita![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 9]They're going to be filming nearby, right?[n]I hope they stop by Inaba, too.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 10]Oh, I know! Why don't you ask?[n][f 1 3 -1][f 1 1][e]

[msg MSG_006 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 11]Kanamin...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 12]...I don't have anything to do with[n]them anymore.[n][f 1 3 -1][f 1 1][e]

[msg MSG_007 [Deputy mayor]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 13]But wait... How many are coming?[n]We only have small bed-and-breakfasts[n]around here...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 14]Got it! They can stay at the Amagi Inn![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 15]Alright, I need to go tell that manager guy[n]I was just talking to![n][f 1 3 -1][f 1 1][e]

[msg MSG_008 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 16]......[n][f 1 3 -1][f 1 1][e]

[msg MSG_009 [Inoue]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 17][f 4 6 61 2 0 1]Oh, Rise-chan. Nice to see you.[n][f 1 3 -1][f 1 1][e]

[msg MSG_010 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 18]Inoue-san... What do you want today...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_011 [Inoue]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 19][f 4 6 61 1 0 1]I'm down here scouting film locations,[n]so I thought I'd come see you.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 20][f 4 6 61 3 0 1]I wanted to hear your answer one more[n]time, face to face.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 21][f 4 6 61 4 0 1]...Are you sure you're not coming back?[n][f 1 3 -1][f 1 1][e]

[msg MSG_012 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 22]......[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 23]I...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 24]I'm not going back...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 25]......[n][f 1 3 -1][f 1 1][e]

[msg MSG_013 [Inoue]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 26][f 4 6 61 4 0 1]I see...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 27][f 4 6 61 1 0 1]Okay... I understand. Well, now I can focus[n]on my new job.[n][f 1 3 -1][f 1 1][e]

[msg MSG_014 [Inoue]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 28][f 4 6 61 1 0 1]I signed up as Kanami Mashita's manager.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 29]Remember how we were talking about[n]doing that movie? They picked Kanami[n]as your replacement.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 30]...We're going to sell Kanami.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 31][f 4 6 61 2 0 1]I have every confidence she'll be just[n]as popular... no, even MORE popular[n]than Risette.[n][f 1 3 -1][f 1 1][e]

[msg MSG_015 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 32]I-I see...[n][f 1 3 -1][f 1 1][e]

[msg MSG_016 [Inoue]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 33][f 4 6 61 1 0 1]Although... Kanami is an ordinary girl.[n]We have to "polish" her so she sells...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 34][f 4 6 61 4 0 1]......[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 35][f 4 6 61 1 0 1]But you had that spark...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 36][f 4 6 61 2 0 1]You learned fast, adapted well to new[n]situations, had that smile that could be[n]as strong or weak as you needed...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 37]And those acting skills of yours![n]You were like an old pro.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 38]You could have reached heights most girls[n]could never dream of...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 39][f 4 6 61 4 0 1]...That's what I think, anyway.[n][f 1 3 -1][f 1 1][e]

[msg MSG_017 [Inoue]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 40][f 4 6 61 1 0 1]So... I just had to hear it from your[n]own mouth.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 41]Well, then... goodbye.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 42][f 4 6 61 2 0 1]Stay healthy, okay?[n][f 1 3 -1][f 1 1][e]

[msg MSG_018 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 43]......[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 44]What the heck... That's not fair...[n]After he made me answer...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 45]He never told me any of that when we[n]were still working together...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 46]Acting skills...? Of course I have 'em.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 47]What the heck...? Telling me all that stuff[n]now... It's too late...![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 5 7 -1 1][f 3 1 1 0 0 48]......[n][f 1 3 -1][f 1 1][e]

[msg MSG_019 [ ]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> It seems Rise is crying...[n][f 1 3 -1][f 1 1][e]

[msg MSG_020 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 49]Hey... Why... am I crying...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 50]There's no reason to cry...[n]There's nothing... to be sad about...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 51]Nothing... [n][f 1 3 -1][f 1 1][e]

[msg MSG_021 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 7 -1 1][f 3 1 1 0 0 52]Senpai... I... I don't know why I'm crying...[n][f 1 3 -1][f 1 1][e]

[sel SEL_022]
[f 0 5 -258][f 2 1]"You mustn't cry!"[e]
[f 0 5 -258][f 2 1]"Cry all you want."[e]

[msg MSG_023 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 7 -1 1][f 3 1 1 0 0 53]Haha... It's too late now...[n][f 1 3 -1][f 1 1][e]

[msg MSG_024 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 54]Haha... I can't... My eyes will be all[n]swollen tomorrow...[n][f 1 3 -1][f 1 1][e]

[msg MSG_025 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 55]I... I lost... everything...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 56]I don't know how... but...[n]I lost everything...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 57]I'm scared... I'm sad... What's going on...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 58]Senpai...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 59]Please, stay here...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 60]Stay by... my side...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 61]Senpai...![n][f 1 3 -1][f 1 1][e]

[msg MSG_026 [ ]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> ...You sense this is an important moment.[n]There's no turning back.[n][f 1 3 -1][f 1 1][e]

[sel SEL_027]
[f 0 5 -258][f 2 1]Hold her (Love)[e]
[f 0 5 -258][f 2 1]Stand there[e]

[msg MSG_028 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 5 -1 1][f 3 1 1 0 0 62]S-Senpai...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 5 7 -1 1][f 3 1 1 0 0 63]Senpai...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 7 0 0 0][f 3 1 1 0 0 0][f 1 5] [n]> Rise began pouring out tears...[n][f 1 3 -1][f 1 1][e]

[msg MSG_029 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 64]Senpai...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 65]I have you... I have the others...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 66]I didn't lose everything...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 67]There are people who need me, right...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_030 [ ]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Rise is smiling through her tears...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You feel your relationship with Rise[n]has grown deeper...[n][f 1 3 -1][f 1 1][e]

[msg MSG_031 [ ]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> ......[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You can feel Rise's warmth as[n]she trembles...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> There's no turning back...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> [f 0 1 2]Your relationship with Rise has[n]become intimate[f 0 1 0].[n][f 1 3 -1][f 1 1][e]

[msg MSG_032 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 68]I'm going home now.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 69]My head's all messed up...[n][f 1 3 -1][f 1 1][e]

[msg MSG_033 [Rise]]
[f 0 5 -258][f 2 1][f 4 6 5 4 -1 1][f 3 1 1 0 0 70]I need time to think it all over.[n]About how I feel now...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 71]I don't want to lose anything more...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 72]Goodbye, Senpai...[n][f 1 3 -1][f 1 1][e]

[msg MSG_034 [ ]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You watched Rise walk off and[n]went home.[n][f 1 3 -1][f 1 1][e]

[msg MSG_KIRI [ ]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Fog has enveloped the area...[n][f 1 3 -1][f 1 1][e]

