[sel LIBRARY_SEL]
[f 0 5 -258][f 2 1]Read a book[e]
[f 0 5 -258][f 2 1]Study[e]
[f 0 5 -258][f 2 1]Never mind[e]

[msg READ_AT_HOME]
[f 0 5 -258][f 2 1]> The library is noisy so you decided[n]to go home to read.[n][f 1 1][e]

[msg CHECK_SOFA]
[f 0 5 -258][f 2 1]> You don't have any books to read.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should get a book to read...[n][f 1 1][e]

[msg CHECK_SOFA_NOREAD_BOOK]
[f 0 5 -258][f 2 1]> You have read all the books[n]you have.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should get another book to read...[n][f 1 1][e]

[msg CHECK_SOFA_ALLREAD_BOOK]
[f 0 5 -258][f 2 1]> You have read all the books[n]you have.[n][f 1 1][e]

[msg CHECK_SOFA_READBOOK_2ND]
[f 0 5 -258][f 2 1]> Because you have read "Hyperspeed[n]Reading," not as much time has passed[n]as you had expected.[n][f 1 1][e]

[msg CHECK_SOFA_READBOOK_AGAI]
[f 0 5 -258][f 2 1]> You decided to continue reading.[n]What book will you read?[n][f 1 1][e]

[msg CHECK_SOFA_READBOOK_FINI]
[f 0 5 -258][f 2 1]> Maybe you should stop reading...[n][f 1 1][e]

[msg LIBRARY_FIRST_TIME]
[f 0 5 -258][f 2 1]> This is the library.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You can read and study here.[n][f 1 1][e]
