[msg CHISHIKI_UP1]
[f 0 5 65278][f 2 1]>“[f 0 1 1]知識[f 0 1 0]"が高まった![n][f 1 1][e]

[msg DENTATU_UP2]
[f 0 5 65278][f 2 1]>“[f 0 1 1]知識[f 0 1 0]"が“[f 2 4 0]"から[n] “[f 2 4 1]"になった![n][f 1 1][e]

[msg MSG_003]
[f 0 5 65278][f 2 1]>苦手な問題がスラスラ解ける。[n][f 1 1][e]
[f 0 5 65278][f 2 1]>今日は頭がさえているようだ。[n][f 1 1][e]
[f 0 5 65278][f 2 1]>不思議な力が増していくのを感じる…[n][f 1 1][e]

[msg MSG_004]
[f 0 5 65278][f 2 1]>装備ペルソナの“魔力"が1上がった。[n][f 1 1][e]

[msg CHECK_SOFA_5]
[f 0 5 65278][f 2 1]> You begin reading [f 2 4 0]...[n][f 1 1][e]

[msg CHECK_SOFA_6]
[f 0 5 65278][f 2 1]> You decide to continue reading[n][f 2 4 0]...[n][f 1 1][e]

[sel CHECK_READ_Q top]
[f 0 5 65278][f 2 1]さらっと読む[e]
[f 0 5 65278][f 2 1]じっくり読む[e]

[msg CHECK_SOFA_7]
[f 0 5 65278][f 2 1]>“[f 2 4 0]"を[n] じっくり読むことにした…[n][f 1 1][e]

[msg CHECK_SOFA_8]
[f 0 5 65278][f 2 1]>“[f 2 4 0]"を[n] さらっと読むことにした…[n][f 1 1][e]

[msg CHECK_SOFA_9]
[f 0 5 65278][f 2 1]> There's still some pages of[n][f 2 4 0] left.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You decide to save them to read next time.[n][f 1 1][e]

[msg CHECK_SOFA_10]
[f 0 5 65278][f 2 1]> You have finished reading[n][f 2 4 0]![n][f 1 1][e]

[msg CHECK_SOFA_11]
[f 0 5 65278][f 2 1]> You finished the entire[n]Amazing Kahn series...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You feel a little empty inside...[n][f 1 1][e]

[msg CHECK_SOFA_12]
[f 0 5 65278][f 2 1]> You finished the entire[n]Bullied Teacher series...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You feel a little empty inside...[n][f 1 1][e]

[msg CHECK_SOFA_13]
[f 0 5 65278][f 2 1]> You finished the entire[n]series of Manuals...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You feel a little empty inside...[n][f 1 1][e]

[msg CHECK_SOFA_14]
[f 0 5 65278][f 2 1]> You finished the entire series for[n]young readers...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You feel a little empty inside...[n][f 1 1][e]

[msg CHECK_SOFA_15]
[f 0 5 65278][f 2 1]> You finished reading the entire series of[n]reference books...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You feel a little empty inside...[n][f 1 1][e]

[msg ALL_BOOK_READ]
[f 0 5 65278][f 2 1]> Obtained [f 4 4 3 1 758].[n][f 1 1][e]

[msg BOOK_01]
[f 0 5 65278][f 2 1]> Every chapter begins: "All men have[n]the great spirit of masculinity within[n]themselves."[n][f 1 1][e]
[f 0 5 65278][f 2 1]> This spirit of true manhood transcends[n]space and time, and all people, of all[n]cultures and genders, feel its call...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You feel more like a real man[n]than ever before.[n][f 1 1][e]

[msg BOOK_02]
[f 0 5 65278][f 2 1]> Every chapter begins: "All men have[n]the great spirit of masculinity within[n]themselves."[n][f 1 1][e]
[f 0 5 65278][f 2 1]> What is true manhood? The Amazing[n]Kahn set out on a journey to find the[n]Platonic ideal of masculinity...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You feel more like a real man[n]than ever before.[n][f 1 1][e]

[msg BOOK_03]
[f 0 5 65278][f 2 1]> Every chapter begins: "All men have[n]the great spirit of masculinity within[n]themselves."[n][f 1 1][e]
[f 0 5 65278][f 2 1]> The Amazing Kahn learns to accept[n]life and death through the rigorous[n]application of manhood.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You feel more like a real man[n]than ever before.[n][f 1 1][e]

[msg BOOK_04]
[f 0 5 65278][f 2 1]> Every chapter begins: "All men have[n]the great spirit of masculinity within[n]themselves."[n][f 1 1][e]
[f 0 5 65278][f 2 1]> The Amazing Kahn spends 500 days in[n]the mountains, seeking to prove a rumor[n]about the true masters of manliness.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You feel more like a real man[n]than ever before.[n][f 1 1][e]

[msg BOOK_05]
[f 0 5 65278][f 2 1]> Every chapter begins: "All men have[n]the great spirit of masculinity within[n]themselves."[n][f 1 1][e]
[f 0 5 65278][f 2 1]> The Amazing Kahn attempts to retreat[n]from the world of masculinity, but its[n]powerful call torments him...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You feel more like a real man[n]than ever before.[n][f 1 1][e]

[msg BOOK_06]
[f 0 5 65278][f 2 1]> The story is about a weak-willed[n]milquetoast of a teacher who has a hard[n]time getting his students to learn...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> The book begins with a story in which[n]the teacher's outlook on life changes[n]from "I give up" to "I can do this."[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You are filled with tender feelings.[n][f 1 1][e]

[msg BOOK_07]
[f 0 5 65278][f 2 1]> The story is about a weak-willed[n]milquetoast of a teacher who has a hard[n]time getting his students to learn...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> This story is a comedy, and describes[n]the misadventures of the teacher as he[n]flees from psychopathic bill collectors.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You are filled with tender feelings.[n][f 1 1][e]

[msg BOOK_08]
[f 0 5 65278][f 2 1]> The story is about a weak-willed[n]milquetoast of a teacher who has a hard[n]time getting his students to learn...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> The teacher changes jobs, but his new[n]job requires too much physical labor.[n]Later, his students welcome him back.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You are filled with tender feelings.[n][f 1 1][e]

[msg BOOK_09]
[f 0 5 65278][f 2 1]> The story is about a weak-willed[n]milquetoast of a teacher who has a hard[n]time getting his students to learn...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> A sitcom-like story with the cowardly[n]teacher and his companions, the snooty[n]teacher, shady teacher, and hot teacher.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You are filled with tender feelings.[n][f 1 1][e]

[msg BOOK_10]
[f 0 5 65278][f 2 1]> The story is about a weak-willed[n]milquetoast of a teacher who has a hard[n]time getting his students to learn...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> This is about the teacher's last[n]lecture to his classes that year, and[n]his students' eyes filled with tears.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You are filled with tender feelings.[n][f 1 1][e]

[msg BOOK_11]
[f 0 5 65278][f 2 1]> The various tea ceremonies from many[n]regions are described here in great[n]detail...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You feel that you could teach[n]anyone about performing tea ceremonies.[n][f 1 1][e]

[msg BOOK_12]
[f 0 5 65278][f 2 1]> Various Judo techniques are described[n]here, along with the origins of their[n]names and other Judo trivia...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You don't feel any stronger, but[n]you feel that you could teach these[n]forms to someone.[n][f 1 1][e]

[msg BOOK_13]
[f 0 5 65278][f 2 1]> This book describes Shinto rituals and[n]oral traditions, with some helpful[n]illustrations.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You understand the material, but you[n]don't feel that you could teach this to[n]someone else...[n][f 1 1][e]

[msg BOOK_14]
[f 0 5 65278][f 2 1]> This book explains different ways to[n]prepare noodles from a variety of[n]different regions.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...It sounds delicious. Maybe you[n]should talk to someone about it...[n][f 1 1][e]

[msg BOOK_15]
[f 0 5 65278][f 2 1]> This book shows how one should live as[n]a punk, along with some illustrations...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You understand the material, but you[n]know better than to follow the[n]information in this book.[n][f 1 1][e]

[msg BOOK_16]
[f 0 5 65278][f 2 1]> A ploddingly written romantic comedy[n]about a girl on her first day of school[n]in a new town. Vampires are involved.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...The content of this book was almost[n]physically painful for you to read.[n][f 1 1][e]

[msg BOOK_17]
[f 0 5 65278][f 2 1]> A textbook that teaches the very[n]fundamentals of mathematics and the[n]concept of numbers...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...Did Kou really learn math from[n]this book?[n][f 1 1][e]
[f 0 5 65278][f 2 1]> The conversation between "Mr. Plus"[n]and "Miss Minus" makes learning math[n]needlessly complicated...[n][f 1 1][e]

[msg BOOK_18]
[f 0 5 65278][f 2 1]> An enthusiastically written book about[n]pests. Each pest is described in two[n]full-color pages with lots of trivia.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> There are many diagrams illustrating[n]the shapes of skeletons and digestive[n]systems...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...It gave you goosebumps.[n][f 1 1][e]

[msg BOOK_19]
[f 0 5 65278][f 2 1]> Riddles submitted from children across[n]the country are listed in this book...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> The gold medal-winning riddle is:[n]"Q: What do you call the cutest girl in[n]the world? A: Me."[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You become upset from the unsolvable[n]and exceedingly stupid riddles in this[n]book.[n][f 1 1][e]

[msg BOOK_20]
[f 0 5 65278][f 2 1]> The connections between gods, the[n]truth of the universe, and human life[n]is detailed in this book...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...In fact, the lack of basic[n]explanation makes the material quite[n]difficult to follow.[n][f 1 1][e]

[msg BOOK_21]
[f 0 5 65278][f 2 1]> The book contains tips on how to concentrate[n]during class and take notes effectively in[n]order to increase knowledge retention...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> Though while reading it, you wonder if it[n]really is that easy to follow all the advice[n]in it...[n][f 1 1][e]

[msg BOOK_21_END]
[f 0 5 65278][f 2 1]> You feel as if your [f 0 1 1]Knowledge[f 0 1 0] will increase[n]faster when studying at your desk or in the[n]library...[n][f 1 1][e]

[msg BOOK_22]
[f 0 5 65278][f 2 1]> It's a collection of illustrated sample[n]conversations for many common situations,[n]from "good morning" to "good night"...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You wonder how often this will actually[n]be useful while living in Inaba...[n][f 1 1][e]

[msg BOOK_22_END]
[f 0 5 65278][f 2 1]> You feel as if your [f 0 1 1]Expression[f 0 1 0] will increase[n]faster, allowing you to be more efficient[n]when doing translation work...[n][f 1 1][e]

[msg BOOK_23]
[f 0 5 65278][f 2 1]> One hundred unexplainable stories, which[n]have been passed down since ancient times,[n]are anthologized in this book...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> But as you read on, you feel as if you've[n]heard a number of them before...[n][f 1 1][e]

[msg BOOK_23_END]
[f 0 5 65278][f 2 1]> You feel as if your [f 0 1 1]Courage[f 0 1 0] will increase[n]faster when doing part-time janitorial work[n]at the hospital...[n][f 1 1][e]

[msg BOOK_24]
[f 0 5 65278][f 2 1]> The manual contains useful tips on ways to[n]be more efficient when doing office work.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You feel as if this will be a great help[n]for when you work at your part-time job...[n][f 1 1][e]

[msg BOOK_24_END]
[f 0 5 65278][f 2 1]> You feel as if your [f 0 1 1]Diligence[f 0 1 0] will increase[n]faster, and you will be more efficient when[n]folding envelopes...[n][f 1 1][e]

[msg BOOK_25]
[f 0 5 65278][f 2 1]> According to the book, the way you fold[n]your pattern will drastically change how[n]the final product looks...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You read on, hoping that this will help[n]you to learn different ways of folding[n]origami...[n][f 1 1][e]

[msg BOOK_25_END]
[f 0 5 65278][f 2 1]> You feel as if your [f 0 1 1]Understanding[f 0 1 0] will[n]increase faster and you'll be able to[n]fold cranes more efficiently...[n][f 1 1][e]

[msg BOOK_26]
[f 0 5 65278][f 2 1]>自由奔放でワガママな子供たちの面白話を交え[n] どう接していけば良いか書かれている…[n][f 1 1][e]
[f 0 5 65278][f 2 1]>子供と接する機会では、かなり有用だ、[n] と思いながら読み進めた…[n][f 1 1][e]

[msg BOOK_26_END]
[f 0 5 65278][f 2 1]>学童保育のお手伝いで、[n] [f 0 1 1]“寛容さ"[f 0 1 0]の上がりが良くなった気がする…[n][f 1 1][e]

[msg BOOK_27]
[f 0 5 65278][f 2 1]>接客業とは何か? と哲学的な小難しい話が[n] ズラズラと書かれている…[n][f 1 1][e]
[f 0 5 65278][f 2 1]>小難しい話でも、読めば理解出来るように[n] なるのか不安になりながら、読み進めた…[n][f 1 1][e]

[msg BOOK_27_END]
[f 0 5 65278][f 2 1]>スナック紫路宮の皿洗いで、お客さんの話を[n] よく聞けるようになった気がする…[n][f 1 1][e]

[msg BOOK_28]
[f 0 5 65278][f 2 1]>書かれた物語を、より楽しみながら[n] 読むコツが書かれている…[n][f 1 1][e]
[f 0 5 65278][f 2 1]>物語のある本でないと効果がないのは[n] 残念に思いながら、読み進めた…[n][f 1 1][e]

[msg BOOK_28_END]
[f 0 5 65278][f 2 1]>物語のある本をより楽しめるように[n] なった気がする…[n][f 1 1][e]

[msg BOOK_29]
[f 0 5 65278][f 2 1]>プラモデルを作る過程で、より少ない労力で[n] 完成させる為の極意が書かれている…[n][f 1 1][e]
[f 0 5 65278][f 2 1]>自分も完成まで時間をかけずに出来るように[n] なりそうだ、と思いながら読み進めた…[n][f 1 1][e]

[msg BOOK_29_END]
[f 0 5 65278][f 2 1]>プラモデルを完成させるのに[n] 少ない日数で出来るようになった気がする…[n][f 1 1][e]

[msg BOOK_30]
[f 0 5 65278][f 2 1]> It says that the essence of Chinese dining[n]is to eat everything that is served...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You do feel that if you put this advice[n]into practice, it will toughen your body[n]and mind...[n][f 1 1][e]

[msg BOOK_30_END]
[f 0 5 65278][f 2 1]> You feel as if you'll be able to train[n]yourself even better by eating Chinese food...[n][f 1 1][e]

[msg BOOK_31]
[f 0 5 65278][f 2 1]> The author's advice for those just learning[n]how to fish is to not lose heart after hours[n]of waiting for a bite...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> It seems willpower is very important for[n]a fisherman...[n][f 1 1][e]

[msg BOOK_31_END]
[f 0 5 65278][f 2 1]> You feel as if you will be able to fish[n]longer now...[n][f 1 1][e]

[msg BOOK_32]
[f 0 5 65278][f 2 1]> It says that when going after big game,[n]when opportunity strikes, you must reel it[n]in at once with all your might...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> It appears that if you don't seize such[n]moments, it will be difficult to catch the[n]biggest game...[n][f 1 1][e]

[msg BOOK_32_END_000]
[f 0 5 65278][f 2 1]> You feel as if you've learned the proper[n]technique to quickly reel in a fish...[n][f 1 1][e]

[msg HELP_BOOK_32_BONUS_TURI]
[f 0 5 65278][f 2 1]From now on, when you see the [f 0 1 2]Command Menu button[f 0 1 0][n]icon under the gauge, [f 0 1 2]Command Menu button[f 0 1 0][n]to [f 0 1 2]boost your reel speed[f 0 1 0].[n][f 1 1][e]

[msg BOOK_32_END_010]
[f 0 5 65278][f 2 1]> You resolve to try it out the next time[n]you go fishing...[n][f 1 1][e]

[msg BOOK_33]
[f 0 5 65278][f 2 1]> The basics of bug-catching are explained[n]here, along with a funny anecdote from the[n]author...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> The methods sound simple enough and may[n]help you to catch more bugs.[n][f 1 1][e]

[msg BOOK_33_END]
[f 0 5 65278][f 2 1]> You feel as if you'll be able to catch[n]more bugs now...[n][f 1 1][e]

[msg BOOK_34]
[f 0 5 65278][f 2 1]> Some practical advice for learning the[n]habits of bugs in order to catch them is[n]outlined here...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> If you study these techniques, you may be[n]able to catch even more bugs.[n][f 1 1][e]

[msg BOOK_34_END]
[f 0 5 65278][f 2 1]> You feel as if you'll be able to catch[n]even more bugs now...[n][f 1 1][e]

[msg BOOK_35]
[f 0 5 65278][f 2 1]> The book is full of tips on how to maintain[n]a home garden for those who are just getting[n]started...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> Your mouth waters to imagine the delicious[n]vegetables you could grow as you turn[n]the pages...[n][f 1 1][e]

[msg BOOK_35_END_000]
[f 0 5 65278][f 2 1]> You feel as if you'll be able to grow your[n]vegetables better now...[n][f 1 1][e]

[msg HELP_BOOK_35_BONUS_FARM]
[f 0 5 65278][f 2 1]From here on, the amount of time it takes[n]for the vegetables in your garden to be[n]ready to harvest will be [f 0 1 2]reduced by a day[f 0 1 0].[n][f 1 1][e]

[msg BOOK_35_END_010]
[f 0 5 65278][f 2 1]> You wonder if you should try replanting[n]one of your seedlings...[n][f 1 1][e]

[msg BOOK_35_END_010_WINTER]
[f 0 5 65278][f 2 1]> But it's snowing this time of year, so you[n]can't grow any vegetables for now...[n][f 1 1][e]

[msg BOOK_36]
[f 0 5 65278][f 2 1]> The book explains a method for greatly[n]enhancing your reading speed and recall[n]when reading books...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You read on, thinking that this could be[n]effective for all kinds of books...[n][f 1 1][e]

[msg BOOK_36_END_000]
[f 0 5 65278][f 2 1]> You feel as if you'll be able to read more[n]in the same amount of time now...[n][f 1 1][e]

[msg HELP_BOOK_36_BONUS_READ]
[f 0 5 65278][f 2 1]You will now be able to read [f 0 1 2]two chapters[f 0 1 0][n]in a book each time you sit down with it.[n] [n]If you have any books that you haven't[n]read yet, try going back to them.[n][f 1 1][e]

[msg BOOK_36_END_010]
[f 0 5 65278][f 2 1]> You decide to read some other time...[n][f 1 1][e]

[msg RAIN_BONUS]
[f 0 5 65278][f 2 1]> You read your book as the rain spatters[n]against the window...[n][f 1 1][e]

[msg KAMINARI_BONUS]
[f 0 5 65278][f 2 1]> You read your book as the heavy rain and[n]thunder block out all distractions...[n][f 1 1][e]

[msg YUKI_BONUS]
[f 0 5 65278][f 2 1]> You read your book as it quietly snows[n]outside...[n][f 1 1][e]

[msg MSG_RECIPE_GET]
[f 0 5 65278][f 2 1]>[f 2 5 3 65535 5]のレシピを手に入れた。[n][f 1 1][e]

[msg BOOK_READ36_BONUS]
[f 0 5 65278][f 2 1]> Since you've finished [f 2 4 10],[n]you were able to read more than normal.[n][f 1 1][e]

[msg BOOK_READ28_BONUS]
[f 0 5 65278][f 2 1]>“[f 2 4 10]"を読み終えているので、[n] 本の内容をより深く理解する事ができたようだ。[n][f 1 1][e]

[msg READ_MORE]
[f 0 5 -258][f 2 1]> Because you have read "Hyperspeed[n]Reading," not as much time has passed[n]as you had expected.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You decided to continue reading.[n]Which book will you read?[n][f 1 1][e]

[msg CANT_READ_MORE]
[f 0 5 -258][f 2 1]> Because you have read "Hyperspeed[n]Reading," not as much time has passed[n]as you had expected.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> However, you have already finished reading all[n]the books you have...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You may wish to return here once you[n]find something new to read.[n][f 1 1][e]
